### ISSUE TITLE
Syntax Error when using "sudo"

### ISSUE THREAD

**Issue by ARustyOven** [LukeSmithxyz/LARBS#1]
So I attempted to do the command "sudo pacman -S firefox" since firefox doesn't seem to be installed. However, when I use "sudo" I get spat a syntax error in a bunch of lines. I can go around this when logged into root (without doing startx) but then the wifi doesn't work since the network manager doesn't execute.

**Comment by LukeSmithxyz** [comment]
It should be fixed now, although still, use these scripts at your own risk until I officially release them on YouTube.

**Comment by LukeSmithxyz** [comment]
I should add, if you want a quick fix without reinstalling, as the root user, run:
`curl https://raw.githubusercontent.com/LukeSmithxyz/LARBS/master/sudoers > /etc/sudoers`
