### ISSUE TITLE
Changing colours in .Xresources breaks terminal and shortcuts.

### ISSUE THREAD

**Issue by AffectionateNouns** [LukeSmithxyz/LARBS#100]
I had an earlier version of LARBS on a VM and I was able to change .Xresources with no issues. I ran it on my actual machine a couple days ago and now when I edit colours it borks everything. Mod+Enter doesn't work, and neither do any shortcuts that rely on terminal (i.e. Mod+r for ranger, etc), nor can I launch terminal-based applications through dmenu. No idea what to do to fix.

**Comment by Dazage** [comment]
I suggest going switching to another tty, make a backup of your current .Xresources and replace it with the original.

1. CTRL+ALT+F2 (then log in to your user)
2. mv ~/.Xresources ~/.Xresources.bak
3. curl https://raw.githubusercontent.com/LukeSmithxyz/voidrice/master/.Xresources > ~/.Xresources

Failing that, try editing the TERMINAL environmental variable to use xterm or some other terminal you're familiar with.

**Comment by LukeSmithxyz** [comment]
Closing this issue as Xresources is no longer a part of LARBS. If someone has an issue that prevents st from opening, he should open an issue on the st repo.
