### ISSUE TITLE
Changing wallpaper without feh (hsetroot)

### ISSUE THREAD

**Issue by astier** [LukeSmithxyz/LARBS#104]
In your sxiv video you mention that you only keep on using feh because you don't know how else to change the wallpaper. *hsetroot* is made just for this purpose and can be installed via pacman.

**Comment by LukeSmithxyz** [comment]
Check the voidrice repo, the `setbg` script now uses xwallpaper. hsetroot can work for some use cases, but xwallpaper handles multiple monitors exceptionally well compared to other minimal tools, so I went with it.
