### ISSUE TITLE
Can you please add clipboard history

### ISSUE THREAD

**Issue by dr3mro** [LukeSmithxyz/LARBS#105]
please add clipboard history to dmenu like the menu for emoji

**Comment by luukvbaal** [comment]
https://github.com/cdown/clipmenu/
https://www.archlinux.org/packages/community/any/clipmenu/

**Comment by LukeSmithxyz** [comment]
No. I don't want this feature as default as I would feel dirty with it. See @luukvbaal 's links above if you want it for yourself.
