### ISSUE TITLE
Containerize LARBS

### ISSUE THREAD

**Issue by waltsims** [LukeSmithxyz/LARBS#107]
Wouldn’t it make sense to build a container/dockerimage for this install?

**Comment by LukeSmithxyz** [comment]
How?

**Comment by jzlotek** [comment]
Way too much bloat for what it's worth. Why can't you just pull it onto your system and run it normally, or if you want it dockerized, put it as a build step in your docker-compose.yml file

**Comment by waltsims** [comment]
Though I get the bloat point it seems maintenance would be easier if larbs.sh was containerized.

**Comment by waltsims** [comment]
Or migrate larbs.sh into a docker.yml. would make maintaining and upgrading
easier no? Just an idea I thought I would throw out there. Bloat is
relative.

**Comment by LukeSmithxyz** [comment]
How?

The idea of having every user install (and learn to use) docker to run a shell script sounds so absolutely absurd to me that I'm going to assume you have some knock-down reason for it that I can't see.

**Comment by waltsims** [comment]
I'll create a pull request in the future for this until then I'm closing
the issue closes #107
