### ISSUE TITLE
Are there some sort of minimum requirements?

### ISSUE THREAD

**Issue by thebeastgamer25** [LukeSmithxyz/LARBS#11]
I'm running on a VM, and it's awful. Polybar not loading, terminal black, manual not working, etc.
I allocated 2GB of ram, is that enough?

Edit: wallpaper not showing up either ;(

**Comment by LukeSmithxyz** [comment]
There were some errors at the last update. Give me the output of your `pacman -Qn`.

**Comment by thebeastgamer25** [comment]
I am installing with the latest commit after a fresh install. I'll update you...

**Comment by thebeastgamer25** [comment]
@LukeSmithxyz https://ghostbin.com/paste/vbgou
latest commit. wallpaper now set, terminal not working, etc

**Comment by LukeSmithxyz** [comment]
I can't replicate this problem on a fresh install. Does the terminal not pull up on windows+enter? Is polybar there now? Are st and polybar installed?

**Comment by thebeastgamer25** [comment]
ST loads after a minute, and I cant type. Polybar... is installed, but not showing. Maybe I can package up the VM for you to take a look?
null

**Comment by LukeSmithxyz** [comment]
Oh it's a VM. VMs don't handle the scripts well for reasons I'm unsure about, and I don't use them so I can't debug them. It might be memory, I don't know. Obviously there's not much memory overhead in a system like this, but VMs might be different animals.

If you want to try the setup, you should install it on a new parition or machine. As I said before I just reinstalled it to check and it's working fine at the current commits.

**Comment by thebeastgamer25** [comment]
Aw, that sucks... Maybe I could help debug and help you? What would I need to do?
null

**Comment by LukeSmithxyz** [comment]
As I said, I don't know anything about VMs or what could be wrong here. You're welcome to try to troubleshoot the problem yourself, but I couldn't help you.

**Comment by thebeastgamer25** [comment]
Has this issue been reported before? Have oher users installed LARBS on a VM just fine?
null

**Comment by voidanix** [comment]
@thebeastgamer25 Open a tty and type `pkill compton` then head back to i3.
That usually fixes most of the issues.

**Comment by thebeastgamer25** [comment]
@voidanix That worked! Thanks so much!

**Comment by LukeSmithxyz** [comment]
@voidanix  Is there a principled reason for this problem in VMs?

**Comment by voidanix** [comment]
@LukeSmithxyz I'm not sure, but the 3D acceleration feature apparently is bugged in VBox 5.0 (and newer) for compton users.

**Comment by LukeSmithxyz** [comment]
Okay I see. I think I'll put a note about this on the README or website, because I'm sure it's the cause of some confusion for VM users. Thanks for the hint.
