### ISSUE TITLE
chinese language support in LARBS

### ISSUE THREAD

**Issue by wilfredgithuka** [LukeSmithxyz/LARBS#112]
Do you have Chinese characters support in LARBS? Am having a challenge with fcitx support after installing it.

**Comment by jcguu95** [comment]
If you read Chinese, follow this wiki page and you will be set.

https://wiki.archlinux.org/index.php/Localization/Simplified_Chinese_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)
