### ISSUE TITLE
Potential tap to click support via libinput

### ISSUE THREAD

**Issue by ayoung012** [LukeSmithxyz/LARBS#118]
Noticed you have tap to click support on your todo list. Thought I'd outline my research into it.

Ideally you have a catchall for touchpads using xorg config:
```
$ cat /etc/X11/xorg.conf.d/40-libinput.conf
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
	# Enable left mouse button by tapping
	Option "Tapping" "on"
EndSection
```
However I completely understand being hesitant to touch users configuration like this.

In order to achieve this during startup of i3 you could go the xinput command route. As far I know there is no capacity for a catchall touchpad like the above "MatchIsTouchpad". So you might end up with something as ugly as the following...
```
for id in $(xinput list | grep -i 'touchpad' |  grep pointer | cut -d '=' -f 2 | cut -f 1)
do
  xinput set-prop $id 286 1 # libinput Tapping Enabled (286)
done
```
https://wiki.archlinux.org/index.php/libinput#Configuration

Some more creative methods on filtering touchpads:
https://stackoverflow.com/questions/18755967/how-to-make-a-program-that-finds-ids-of-xinput-devices-and-sets-xinput-some-set/18756948

**Comment by sarpik** [comment]
Hello,

I was wondering what does "tap to click support" actually mean?

Do you mean that you just tap the mousepad and it acts as a mouse button click or is this explanation too simple and I'm missing something?

**Comment by xlxs4** [comment]
@sarpik tap to click means that you can press the touchpad to click, instead of having to press the corresponding touchpad button. Nothing less, nothing more :)

**Comment by sarpik** [comment]
Hey @xlxs4 
I thought about recommending https://wiki.archlinux.org/index.php/Touchpad_Synaptics but just noticed the warning and now @ayoung012's intentions are clear.
Best of luck implementing the solution with libinput!

**Comment by MuntashirAkon** [comment]
I think it is beyond the scope of this project. If Luke is interested, I also suggest this config:

```conf
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "Tapping" "on"
        Option "ClickMethod" "clickfinger"
        Option "NaturalScrolling" "true"
EndSection
```

**Comment by rojinmroy** [comment]
This is a rather lazy work around that I used. I enabled tap to click using `xinput` I installed xinput using pacman
Get device id using `xinput` look for something like Synaptics (11 in my case)
Get property id using `xinput list-props <device-id>` (Look for the number beside libinput tapping enabled)
xinput set-prop <device-id> <property-id> 1

Add `xinput set-prop <device-id> <property-id> 1` to $HOME/.xprofile so that it is enabled everytime that I log into the DE.

**Comment by rojinmroy** [comment]
Wouldn't recommend xinput as a permanent fix because, the device id for my synaptics touchpad just changed.
Going the libinput way will be better though. 
As much as I would like to contribute, my attention is drawn to other matters.
