### ISSUE TITLE
Use of "banner" instead of hard coded char sequence

### ISSUE THREAD

**Issue by makidoko** [LukeSmithxyz/LARBS#12]
Hi Luke,

I made a quick review on your scripts. Here's a suggestion : 
Use the banner command to display bannered texts (pacman -S banner && banner some text # you know how to use man for more options ;) )

https://github.com/LukeSmithxyz/LARBS/blob/d58aa68c3e973d84a5978e6f2a152c1afb525e48/src/larbs.sh#L51-L68

Regards, Mirko

**Comment by makidoko** [comment]
I lauched the script in a VM and saw what was the point of your endless cat << EOF \ termcap-list \  EOF

So banner could be useful for these parts to, except for coloring, that you could parse with some python or else, to insert your coloring termcap sequences and make it rainbowish, with an offset shifting of the colors table line by line, couple chars by couple chars

**Comment by LukeSmithxyz** [comment]
Thanks for the hint, but once I merge the devel branch, this won't be relevant anymore as there will be an ncurses menu on the screen for the entirity of the install process. All of the decorative text will be removed anyway.
