### ISSUE TITLE
Control + grave (`) prints old notifications, need help unbinding

### ISSUE THREAD

**Issue by sarpik** [LukeSmithxyz/LARBS#120]
Hello,

I want to unbind the `Control + grave` shortcut, but can't seem to find a way to do it.

Currently it brings up old notifications, such as "Welcome to LARBS", "Weather forecast updated", "<something> copied to clipboard." etc.

---

I've re-installed arch following the tutorial & then bootstrapped using larbs.

I'm using the provided i3's config, `$mod + grave` is bound for `dmenuunicode`, but `Control + grave` is **not** bound to anything. Disabling i3's config does **not** help.

I also understand that this might not be larbs/voidrice-specific, but since I used this configuration & got this behaviour - I thought that others might benefit from it. Thanks ahead!

---

```bash
xev -event keyboard
```

and pressing CTRL + ` (grave) yields

```console
Outer window is 0x2800001, inner window is 0x2800002

KeymapNotify event, serial 24, synthetic NO, window 0x0,
    keys:  0   0   0   0   16  0   0   0   0   0   0   0   0   0   0   0
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

KeyRelease event, serial 25, synthetic NO, window 0x2800001,
    root 0x1ca, subw 0x0, time 4766246, (-342,277), root:(633,368),
    state 0x10, keycode 36 (keysym 0xff0d, Return), same_screen YES,
    XLookupString gives 1 bytes: (0d) "
"
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x2800001,
    root 0x1ca, subw 0x0, time 4767395, (-342,277), root:(633,368),
    state 0x10, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeymapNotify event, serial 28, synthetic NO, window 0x0,
    keys:  4294967242 0   0   0   32  0   0   0   0   0   0   0   0   0   0   0
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

KeyRelease event, serial 28, synthetic NO, window 0x2800001,
    root 0x1ca, subw 0x0, time 4768375, (-342,277), root:(633,368),
    state 0x14, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

**Comment by LukeSmithxyz** [comment]
These are dunst bindings: `~/.config/dunst/dunstrc`

**Comment by sarpik** [comment]
Thank you my lord & savior - I wouldn't have been able to fix it as quickly myself!

For anyone looking for a fix:
comment out / change the `history` binding from `ctrl+grave` to whatever.

Thanks again @LukeSmithxyz!
