### ISSUE TITLE
Slow out of hibernate

### ISSUE THREAD

**Issue by tcpaul** [LukeSmithxyz/LARBS#122]
Hi I'm wondering if I can speed up my computer to get out of hibernate. (Its slower on opening the lid than booting from off, by 1 sec) I have big RAM 16G and big swap 18G and i7 cpu.

I'm looking at .config/i3/config but there isnt much about hibernate.

any suggestions?

**Comment by xlxs4** [comment]
I don't think this is the place to ask such questions, try [searching][] the web

**Comment by xlxs4** [comment]
I don't think this is the right place to ask such questions. Consider [searching][] the web or posting on relevant forums, such as the Arch Linux [forums][].

On an aside, your problem could theoretically be way simpler. Ubuntu recommends having a _20GB_ swap for 16GB of RAM if you want to have a system which supports hibernation.

[searching]: https://www.reddit.com/r/archlinux/comments/87aa78/very_slow_wake_after_suspension/
[forums]: https://bbs.archlinux.org/
