### ISSUE TITLE
Cant find where i can reverse mouse scroll

### ISSUE THREAD

**Issue by tcpaul** [LukeSmithxyz/LARBS#123]
cant find it in any config file

**Comment by LukeSmithxyz** [comment]
What does that mean?

**Comment by tcpaul** [comment]
I means I cant figure out where in the config files I can configure the touchpad

**Comment by tcpaul** [comment]
*queue stop using the touchpad memes

**Comment by tcpaul** [comment]
If this genuinly is because im not specific enough, I mean the two finger gesture going up or down scrolling the page, but it could also be middle mouse wheel (and I want it reversed) 
- on a side note I very much appreciate your work and effort making LARBS Luke +1

**Comment by lhindir** [comment]
I searched “arch touchpad scroll”, and the first result was for Touchpad Synaptics on the ArchWiki. The angry red box at the top told me to go to libinput. There, the first result for C-f “scroll” was an option for natural scrolling. Just below that you’ll find an example touchpad config file to be stored at `/etc/X11/xorg.conf.d/30-touchpad.conf`. Hopefully you can figure it out from here, get used to it :D. Read some more of the surrounding material in the libinput article to get an idea of how configuring input devices is structured.

**Comment by xlxs4** [comment]
https://jlk.fjfi.cvut.cz/arch/manpages/man/libinput.4

**Comment by DannyDannyDanny** [comment]
In a fresh install of LARBS add the option `NaturalScrolling` to `/etc/X11/xorg.conf.d/40-libinput.conf`.

```
Section "InputClass"
  Identifier "libinput touchpad catchall"
  MatchIsTouchpad "on"
  MatchDevicePath "/dev/input/event*"
  Driver "libinput"
  # Enable left mouse button by tapping
  Option "Tapping" "on"
  Option "NaturalScrolling" "on"   # <-- ADD THIS LINE
EndSection
```

A quick reboot and natural scrolling should be on. Also there's probably a way without rebooting.
