### ISSUE TITLE
Mod + u doesnt work

### ISSUE THREAD

**Issue by tcpaul** [LukeSmithxyz/LARBS#124]
It just flashes a small black box for a frame or two and disappears

**Comment by webkernel** [comment]
>It just flashes a small black box for a frame or two and disappears

@tcpaul same here

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xlxs4** [comment]
@tcpaul @webkernel Did this start happening after a specific commit? Can you provide logs?

**Comment by webkernel** [comment]
Hi Luke,
I would be very happy to provide a log, but I really don't know what logfile do you need! Can you help?

**Comment by brandon-garner** [comment]
This is working fine for me and I just pulled latest.

**Comment by webkernel** [comment]
can I find what the problem is by checking journalctl ?

**Comment by TomJansen** [comment]
do you have tmux installed?

**Comment by webkernel** [comment]
Yes. I have. But I made a reinstall and now it works. Thanks!

**Comment by tcpaul** [comment]
reinstall + restart + refresh + reinstall + refresh did not work at any point for me

**Comment by tcpaul** [comment]
if I run `ddspawn tmuxdd` in terminal I get: Window not detected... spawning [{"success":true}]

but still no dropdown

**Comment by tcpaul** [comment]
SOLVED: run tmux in terminal, if your error message is: need UTF-8 locale (LC_CTYPE) but have *x*

change /etc/locale.gen and uncomment the language you want 
then run `locale-gen`

mod+u should work after this
