### ISSUE TITLE
Improvement - Screen resolution

### ISSUE THREAD

**Issue by 1337tester** [LukeSmithxyz/LARBS#125]
Description
Include a way (or mention in manual) to set the screen resolution, this was a struggle for me while installing it on a VM

**Comment by LukeSmithxyz** [comment]
I assume you mean for the dotfiles themselves and not the LARBS installer?

The "built in" way is to use the prompt with `super+F3` and select "manual selection" which brings up arandr, or you could just run arandr directly.

If you want something persistent, you just have to add an xrandr command to the i3 config.
