### ISSUE TITLE
(n)vim unknown function: plug#begin 

### ISSUE THREAD

**Issue by Mesysz** [LukeSmithxyz/LARBS#137]
I tried a few times to install LARBS (first dwm but i3 for a few times, too) and everytime I had this error. It's not something unfixable but I guess you might want to know it. Maybe sth is missing or it's just me who missed some crucial part to make your vim config working like a charm from the begining.

`
Error detected while processing ~/.config/nvim/init.vim:
line   10:
E117: Unknown function: plug#begin
line   11:
E492: Not an editor command: Plug 'tpope/vim-surround'
line   12:
E492: Not an editor command: Plug 'scrooloose/nerdtree'
line   13:
E492: Not an editor command: Plug 'junegunn/goyo.vim'
line   14:
E492: Not an editor command: Plug 'PotatoesMaster/i3-vim-syntax'
line   15:
E492: Not an editor command: Plug 'jreybert/vimagit'
line   16:
E492: Not an editor command: Plug 'lukesmithxyz/vimling'
line   17:
E492: Not an editor command: Plug 'vimwiki/vimwiki'
line   18:
E492: Not an editor command: Plug 'bling/vim-airline'
line   19:
E492: Not an editor command: Plug 'tpope/vim-commentary'
line   20:
E492: Not an editor command: Plug 'kovetskiy/sxhkd-vim'
line   21:
E117: Unknown function: plug#end
Press ENTER or type command to continue
`

I'm still kind of a newbie with vim, so if you need, just tell me what else should I report here. Some logs or sth.
From what I know, in `:scriptnames` there should be plug.vim listed, but it isn't.

**Comment by Sercurio** [comment]
Can u plz enter vim, switch to normal mode and type : 
```
:PlugInstall
```
let us know if something has changed

**Comment by Mesysz** [comment]
After `:PlugInstall` I get 
`E492: Not an editor command: PlugInstall`

**Comment by Sercurio** [comment]
Ok, i suppose you use the neovim bundle of luke so ur config is in ~/.config/nvim/ ?

Can u post a 
```
cat ~/.config/nvim/init.vim
```

If it is try to reinstall the vim-plug plugin for neovim: 
```
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```
It's curious because at the beginning of the init.vim of Luke there is a condition for download the plugin

**Comment by Mesysz** [comment]
<details>
<summary>cat ~/.config/nvim/init.vim</summary>

```
let mapleader =","

if ! filereadable(expand('~/.config/nvim/autoload/plug.vim'))
	echo "Downloading junegunn/vim-plug to manage plugins..."
	silent !mkdir -p ~/.config/nvim/autoload/
	silent !curl "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" > ~/.config/nvim/autoload/plug.vim
	autocmd VimEnter * PlugInstall
endif

call plug#begin('~/.config/nvim/plugged')
Plug 'tpope/vim-surround'
Plug 'scrooloose/nerdtree'
Plug 'junegunn/goyo.vim'
Plug 'PotatoesMaster/i3-vim-syntax'
Plug 'jreybert/vimagit'
Plug 'lukesmithxyz/vimling'
Plug 'vimwiki/vimwiki'
Plug 'bling/vim-airline'
Plug 'tpope/vim-commentary'
Plug 'kovetskiy/sxhkd-vim'
call plug#end()

set bg=light
set go=a
set mouse=a
set nohlsearch
set clipboard+=unnamedplus

" Some basics:
	nnoremap c "_c
	set nocompatible
	filetype plugin on
	syntax on
	set encoding=utf-8
	set number relativenumber
" Enable autocompletion:
	set wildmode=longest,list,full
" Disables automatic commenting on newline:
	autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Goyo plugin makes text more readable when writing prose:
	map <leader>f :Goyo \| set bg=light \| set linebreak<CR>

" Spell-check set to <leader>o, 'o' for 'orthography':
	map <leader>o :setlocal spell! spelllang=en_us<CR>

" Splits open at the bottom and right, which is non-retarded, unlike vim defaults.
	set splitbelow splitright

" Nerd tree
	map <leader>n :NERDTreeToggle<CR>
	autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" vimling:
	nm <leader>d :call ToggleDeadKeys()<CR>
	imap <leader>d <esc>:call ToggleDeadKeys()<CR>a
	nm <leader>i :call ToggleIPA()<CR>
	imap <leader>i <esc>:call ToggleIPA()<CR>a
	nm <leader>q :call ToggleProse()<CR>

" Shortcutting split navigation, saving a keypress:
	map <C-h> <C-w>h
	map <C-j> <C-w>j
	map <C-k> <C-w>k
	map <C-l> <C-w>l

" Check file in shellcheck:
	map <leader>s :!clear && shellcheck %<CR>

" Open my bibliography file in split
	map <leader>b :vsp<space>$BIB<CR>
	map <leader>r :vsp<space>$REFER<CR>

" Replace all is aliased to S.
	nnoremap S :%s//g<Left><Left>

" Compile document, be it groff/LaTeX/markdown/etc.
	map <leader>c :w! \| !compiler <c-r>%<CR>

" Open corresponding .pdf/.html or preview
	map <leader>p :!opout <c-r>%<CR><CR>

" Runs a script that cleans out tex build files whenever I close out of a .tex file.
	autocmd VimLeave *.tex !texclear %

" Ensure files are read as what I want:
	let g:vimwiki_ext2syntax = {'.Rmd': 'markdown', '.rmd': 'markdown','.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
	map <leader>v :VimwikiIndex
	let g:vimwiki_list = [{'path': '~/vimwiki', 'syntax': 'markdown', 'ext': '.md'}]
	autocmd BufRead,BufNewFile /tmp/calcurse*,~/.calcurse/notes/* set filetype=markdown
	autocmd BufRead,BufNewFile *.ms,*.me,*.mom,*.man set filetype=groff
	autocmd BufRead,BufNewFile *.tex set filetype=tex

" Copy selected text to system clipboard:
	vnoremap <C-c> "+y
	map <C-p> "+P

" Save file as sudo on files that require root permission
	cnoremap w!! execute 'silent! write !sudo tee % >/dev/null' <bar> edit!

" Enable Goyo by default for mutt writting
	autocmd BufRead,BufNewFile /tmp/neomutt* let g:goyo_width=80
	autocmd BufRead,BufNewFile /tmp/neomutt* :Goyo | set bg=light
	autocmd BufRead,BufNewFile /tmp/neomutt* map ZZ :Goyo\|x!<CR>
	autocmd BufRead,BufNewFile /tmp/neomutt* map ZQ :Goyo\|q!<CR>

" Automatically deletes all trailing whitespace on save.
	autocmd BufWritePre * %s/\s\+$//e

" When shortcut files are updated, renew bash and ranger configs with new material:
	autocmd BufWritePost files,directories !shortcuts
" Run xrdb whenever Xdefaults or Xresources are updated.
	autocmd BufWritePost *Xresources,*Xdefaults !xrdb %
" Update binds when sxhkdrc is updated.
	autocmd BufWritePost *sxhkdrc !pkill -USR1 sxhkd
```

</details>

After that i checked everything and 

```
:PlugInstall
```
was still not an editor command. 

What I did is **I removed** `~/.config/nvim/autoload/plug.vim` (i mv it to be safe :D) and started vim. Then vim just downloaded everything, which didn't happen at first time. Now it's working. Maybe somewhere in the scripts there is sth that downloads old version of it. I don't know. 
The solution that worked was just to remove it and let it reinstall, but it's not one-time situation. I removed everything, reinstalled LARBS and it all looked the same.

**Comment by Sercurio** [comment]
Thx for ur report, it's actually weird because it's actually downloaded during larbs installation but it seems to not be linked with nvim...

**Comment by jcguu95** [comment]
@Mesysz did you install LARBS to a freshly installed arch? Or you ran a new version LARBS on top of an arch that has older versions of LARBS installed?
