### ISSUE TITLE
Selecting dwm version begins install of i3?

### ISSUE THREAD

**Issue by drake-newell** [LukeSmithxyz/LARBS#139]
Upon selecting the DWM version, LARBS runs as if I selected the i3 version.

**Comment by lukerb52** [comment]
The same issue happened to me.

**Comment by LukeSmithxyz** [comment]
As I said elsewhere, the i3 and dwm choice is what the default WM is. Both are installed in both cases. If you're wandering why i3 takes so long to install, it's because since it is first installed, it pulls all the required X dependencies.

**Comment by drake-newell** [comment]
I should've added that when LARBS was done, it booted into i3 even though I selected to install dwm.
