### ISSUE TITLE
zsh alias not persisting 

### ISSUE THREAD

**Issue by sudo-ghost** [LukeSmithxyz/LARBS#141]
i reinstalled larbs but my zsh alias's are not working now. im  not sure if its an issue on my end or if reinstalling larbs messed with my alias's. like the alias's are still in the config but non of them are working

**Comment by sudo-ghost** [comment]
never mind i managed to fix it by not only editing the .zshrc but i had to edit the /etc/zsh/zshrc to actually make it work. i also had to common out some of the stuff in your aliasrc to work with my preferences

**Comment by LukeSmithxyz** [comment]
The user zshrc for LARBS is in `~/.config/zsh`.
