### ISSUE TITLE
Terminal automaticaly closes when i try to open i3blocks config or any status bar files such as cpu, battery, etc. [NEW LARBS]

### ISSUE THREAD

**Issue by prakash2033** [LukeSmithxyz/LARBS#143]
**ISSUE:** Today, I did fresh install of latest version of LARBS with i3wm & facing below issues.

**Scenario 1:**
`vim .config/i3blocks/config` => This command automatically closes terminal. I'm not able to edit i3blocks config.

**Scenario 2:**
`vim .local/bin/statusbar/cpu` => This command automatically closes terminal. Same for all files in statusbar folder.

Also tried opening above file using `nano`, that also results in same issue, it closes terminal.

**Note:** Whereas i'm able to open all other files such as i3 config, .bashrc, etc. Also able to view i3blocks config successfully in `tty1`

**CAUSE:** This is especially a problem because if unicode characters aren't rendering correctly, st especially has a tendency to crash when rendering them.

**Comment by prakash2033** [comment]
Thanks for the [update](https://lukesmith.xyz/2019.html#two-more-videos-and-important-larbs-problem) Luke. Will keep issue open, until we get a permanent fix.

**Comment by focus85** [comment]
i am having the same issue, cant even open neomutt.

**Comment by prakash2033** [comment]
@focus85 Please use any other terminal, which doesn't crash if it fails to render unicode character. I'm using urxvt (rxvt-unicode) for neomutt.

**Comment by LukeSmithxyz** [comment]
Update st to the newest commit that I put out earlier. I believe that should prevent crashes, even in the event of color emojis (they should just not appear, while viable emojis will).

**Comment by prakash2033** [comment]
Awesome, thank you Luke. You rock as always :) :+1:

**Comment by prakash2033** [comment]
It stopped crashing for few things such as neomutt, but not for all. It's still crashing for few things such as
`vim .local/bin/statusbar/battery` and few other files.

**Comment by focus85** [comment]
As always thanks for your endless support Luke. @prakash2033 try this method, which fix almost every issue, 

https://github.com/LukeSmithxyz/voidrice/issues/424#issuecomment-562217653

**Comment by prakash2033** [comment]
@focus85 which particular package needs to be downloaded and installed from [here](https://martchus.no-ip.biz/repoindex/#packages)?

**Comment by focus85** [comment]
@prakash2033 download ttf-symbola and install it with pacman -U packagename

**Comment by prakash2033** [comment]
Got it, i installed ttf-symbola from there and fixed the problem. Also installed nerd-fonts-complete from AUR. Thanks
