### ISSUE TITLE
DWM using way too many resources consistently

### ISSUE THREAD

**Issue by lukerb52** [LukeSmithxyz/LARBS#144]
DWM is consistently seen using 30% of a core on my ThinkPad Edge 0578 with an i3 CPU.

**Comment by lukerb52** [comment]
![dwm_slow](https://user-images.githubusercontent.com/43391582/70179319-dc550700-16ab-11ea-819e-2e80c0b8907c.png)

**Comment by LukeSmithxyz** [comment]
Strange... Does killing dwmblocks change anything?

**Comment by lukerb52** [comment]
> Strange... Does killing dwmblocks change anything?
> […](#)
> On 19/12/04 12:36PM, Luke Bubar wrote: ![dwm_slow](https://user-images.githubusercontent.com/43391582/70179319-dc550700-16ab-11ea-819e-2e80c0b8907c.png) -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#144 (comment)](https://github.com/LukeSmithxyz/LARBS/issues/144#issuecomment-561828119)

```
[lukerb52@BatPad ~]$ sudo kill dwmblocks
[sudo] password for lukerb52:
kill: cannot find process "dwmblocks"
[lukerb52@BatPad ~]$
```
If there is a better command to use please let me know

**Comment by MuntashirAkon** [comment]
> If there is a better command to use please let me know

Use `pkill` instead of `kill` as `kill` only takes process id, not command/program name.
