### ISSUE TITLE
load different keymap. (doesn't want to comply)

### ISSUE THREAD

**Issue by levaritie** [LukeSmithxyz/LARBS#145]
I am sorry to bother you.
But I cant get the keymap for my UK keyboard to load. even writing the intire thing in the ttymaps.kmap file in .local/share/larbs doesnt seem to have any effect.

the things I tried, loadkeys, localectl, setxkbmap,
in all of those  I at first simply tried to set it to uk, then tried to give it the ttymaps.kmap file.

I did at some point had a "pt"(not that I know what it stands for) keyboard.. how that happend I have no clue but if any of you have a idea, I would be gratefull! 

in the mean time I will puzzle some more.

**Comment by decantr** [comment]
add `-layout gb` to the `setxkbmap` command in your `.local/bin/remaps` so it looks like;

```
setxkbmap -layout gb -option caps:super
```

**Comment by levaritie** [comment]
that was something I completely overlooked, it works!
Thanks!
