### ISSUE TITLE
Unable to follow links in zathura

### ISSUE THREAD

**Issue by lyh970817** [LukeSmithxyz/LARBS#150]
It seems that when typing in f I do get the right selection prompt and on typing in a number plus enter there is no error. But no browser is opened.

**Comment by LukeSmithxyz** [comment]
This is an issue with Brave at the moment I believe. I'll try and figure it out.

**Comment by lukerb52** [comment]
Issue replicated here.

**Comment by lukerb52** [comment]
Issure replicated on my machine

Although on my machine, I have the $BROWSER var set to qutebrowser. Shouldn't that let it handle links?

**Comment by LukeSmithxyz** [comment]
Well I should say the problem is with chromium-based browsers generally and qutebrowser is one.

**Comment by LukeSmithxyz** [comment]
Fixed in https://github.com/LukeSmithxyz/voidrice/commit/426979aa7250e1d09b1f6044020d3f2b538425a9
