### ISSUE TITLE
Missing tag definitions for progs.csv column in README.md

### ISSUE THREAD

**Issue by Traap** [LukeSmithxyz/LARBS#151]
README.md provides column definitions for progs.csv.  The first column is a "tag".  README.md lines 44 through 46 define "A" for AUR, "G" for git, and blank "" for main repository, but does not include the definition for "I" and "V" which are used progs.csv.

larbs.sh installationloop() lines 122 through 135 use tags "A", "G", "P", and default to * for maininstall.

I suggest including "I" and "V" definitions in README.md.

**Comment by LukeSmithxyz** [comment]
Those are for distribution-specific packages, which has not been fully implemented.

Yes, they should be run by `maininstall` and therefore `installpkg`. The difference is that on say Void Linux, we grep out only untagged programs (programs installed on every distro), the `G` tag for git programs and `V` for Void-specific programs.  See:

```
if type xbps-install >/dev/null 2>&1; then
	installpkg(){ xbps-install -y "$1" >/dev/null 2>&1 ;}
	grepseq="\"^[PGV]*,\""
elif type apt >/dev/null 2>&1; then
	installpkg(){ apt-get install -y "$1" >/dev/null 2>&1 ;}
	grepseq="\"^[PGU]*,\""
else
	installpkg(){ pacman --noconfirm --needed -S "$1" >/dev/null 2>&1 ;}
	grepseq="\"^[PGA]*,\""
fi
```

Either way, I haven't had time to test this feature.

**Comment by Traap** [comment]
Thank you for the response.
