### ISSUE TITLE
/repos/ folder not in $HOME directory

### ISSUE THREAD

**Issue by adamac2** [LukeSmithxyz/LARBS#156]
Newbie question admittedly, but in _A Friendly Guide to LARBS!_ it says that some of the customization binds for dwm are in ~/repos/dwm/config.h but there is no repos folder. Was it moved somewhere else?

**Comment by youoralovedone** [comment]
newbie here, I am also having this issue
I ran `find / -type d -name "repos"` without any avail

**Comment by adamac2** [comment]
My guess is that Luke (or other contributors) didn't document changes. I just created the directory and started `git clone`ing what should be in there, and then just used that instead. So far it works for me.

**Comment by DearRude** [comment]
I also have this issue...

**Comment by LukeSmithxyz** [comment]
In new installs, this directory will be in `~/.local/src/` now. There was a period where compiled programs were not kept, and many of you might've installed it then, in which case you'd have to manually clone the repositories from Github.

The documentation is out of date, I really need to write that up.
