### ISSUE TITLE
Switching Shell to Bash?

### ISSUE THREAD

**Issue by NotKudo** [LukeSmithxyz/LARBS#158]
Hey Larbs,

Love using this script for my machines but being new to linux - I tried changing my shell to bash through the proper terminal commant for my user - however it seems this breaks larbs shortcuts and such as on a reboot larbs begins to have a gray screen set and many functions and shortcuts stop working. When I revert the shell from bash to the original zsh everything comes back again. What is the proper procedure for changing the shell to bash in LARBS beside just the usual terminal command?

Thanks!

**Comment by Segdon** [comment]
I suppose that you are doing it correctly, but the bashrc file hasn't got the same settings and aliases as the zshrc one. you could copy everything over or look for the equivalent settings and write those to the config-file (for example, bash doesn't refer to .config/aliasrc by default in LARBS.) however, before you start doing all that labour, ask youself: why would i change back to bash. unless you have a clear reason, the need can't be that high, as zsh is as compatible as possible with bash.

**Comment by LukeSmithxyz** [comment]
The important file will be the `~/.profile` file. If you have a `~/.bash_profile` file, bash will read that instead of `~/.profile`, which is the file that sets the updated `PATH` variable and other stuff generally necessary for operation. You can either delete the `~/.bash_profile`, link it to `~/.profile` or copy the content of `~/.profile` or `~/.zprofile` into `~/.bash_profile`.

**Comment by NotKudo** [comment]
You actually convinced me to keep on using zsh with pure logic and words,
but your solution will be useful for others who need to do the same thing.
Thanks for all that you do

**Comment by MuntashirAkon** [comment]
> What is the proper procedure for changing the shell to bash in LARBS beside just the usual terminal command?

Just add `~/.profile` in the `~/.bash_profile` like this:
```sh
echo '[[ -f ~/.profile ]] && . ~/.profile' >> ~/.bash_profile
```
