### ISSUE TITLE
cant change the keyboard layout

### ISSUE THREAD

**Issue by ROMSY-SAN** [LukeSmithxyz/LARBS#16]
Hey Luke, 
so after making a fresh install of Arch i decided to try your larbs, which is kinda looking good :)

Problem is, i cant change my keyboard layout.
i tried to edit ~/.scripts/remap 
line 5 changed us to de
no changes
commented line 5 and uncommented line 9
no changes
tried in terminal loadkeys de-latin1
got the message:
 Couldn't get a file descriptor referring to the console 
same command as sudo: no message but still no change.

before i forget: after every change i logged out and logged in again.

**Comment by LukeSmithxyz** [comment]
Keep line 5 commented, then change line 9 to `setxkbmap -layout de -option caps:super`. See what happens on the next login. Remove the `xmodmap` command in the script if it doesn't work.

**Comment by ROMSY-SAN** [comment]
good morning, so after fidgeting around with the configs the only solution to change the keyboard was to edit the ~/.config/i3/config directly and add exec setxkbmap de in there.

i dunno why everything else failed (even your suggestion didnt worked) but i think its an i3 thing itself.

**Comment by LukeSmithxyz** [comment]
Are you sure you didn't delete the `exec --no-startup-id ~/.scripts/remaps` line in the i3 config then?

I just tried it myself and I get the German mapping just by editing the `remaps` file.

**Comment by Vollblut** [comment]
ive got it to work correctly like youve stated Luke. But the terminal shows no Umlauts (ÄÖÜ) and sharp s (ß). 
they show up in the TTY and GUI applications. do I have to reconfigure st?

**Comment by LukeSmithxyz** [comment]
@Vollblut Have you changed/installed new fonts? It sounds like your mono font is lacking those characters. What does `fc-match mono` show?

**Comment by Vollblut** [comment]
no i haven't yet.Inconsolata-Regular.ttf: "Inconsolata" "Regular" 

everywhere i get ö, ä, ü and so on just fine, only in st

**Comment by LukeSmithxyz** [comment]
Okay, good.

**Comment by Gfast2** [comment]
@Vollblut ,

Thanks! But perhaps its a typo: ```/etc/local.conf``` => ```/etc/locale.conf``` I believe.
```
# For the Problem here discussed
LANG=de_DE.UTF-8
# For a english language enviroments
LANGUAGE=en_US:en_GB:en
```

**Comment by Sam-Vega** [comment]
I'm having the same issue, keyboard stuck on english. It's been 2 years and the config files discussed above are not in the same place. Found them elsewhere but the lines are not as described. Has this changed since? Thanks
