### ISSUE TITLE
Manjaro i3 not working after LARBS installation 

### ISSUE THREAD

**Issue by n4vho** [LukeSmithxyz/LARBS#161]
Hey Luke,
I tried to install LARBS in manjaro i3(community edition). But after restarting it just prompts the login. After that it just shows a blank key with a cursor and then keeps on bringing up the login. What should I do to resolve this issue?

**Comment by s3p1ol** [comment]
Facing the same issue..kinda. I'm able to use everything except there is no bar and the guide is blank

**Comment by LukeSmithxyz** [comment]
A lot has changed since this issue was opened, but I just tested it out on Manjaro i3 and it's installing and running fine. Bar works, help guide works. There are one or two binds I haven't updated but I'll fix that in a bit.
