### ISSUE TITLE
Poor video performance caused by xcompmgr in i3

### ISSUE THREAD

**Issue by KarolBank** [LukeSmithxyz/LARBS#162]
I get poor video performance while playing high resolution videos, especially when scaled up on my external monitor (2560 x 1440). This includes youtube videos in Brave and video files in mpv. The same video files work just fine in mplayer.
I'm using a Thinkpad x200.

I figured out that the problem is caused by xcompmgr. When I turn it off, mpv and mplayer perform identical. Is there any way to fix it, other than temporarily disabling xcompmgr?

**Comment by goldcoders** [comment]
install picom instead
