### ISSUE TITLE
Error with the volume module

### ISSUE THREAD

**Issue by JP-tech-sh** [LukeSmithxyz/LARBS#163]
Hi Luke, I recently installed LARBS on a fresh arch install, I'm using the i3-gaps version, Whenever I change the volume i get an error tha says, "The configured command for this shortcut not be run succesfully", volume itself is working, changes when I press the volume keys but the volume module isn't working at all. I don't think is a bug, I think I'm doing something wrong, do you have any idea what can cause this problem? :)
The show error result: https://pastebin.com/s7RgnXvh

**Comment by LukeSmithxyz** [comment]
This was fixed a couple commits ago. The commands need to be joined by `&&`, not `;`. You can get the newest version of the i3 config and it will be fixed.
