### ISSUE TITLE
[Feature Request] - LightDM for login

### ISSUE THREAD

**Issue by Pwhitcomb** [LukeSmithxyz/LARBS#165]
Would you consider adding LightDM as a display manager to login to i3? Or are you going for a more minimalist approach?

**Comment by LukeSmithxyz** [comment]
Why

**Comment by Pwhitcomb** [comment]
I thought that implementing a DM would be nice for some people to choose their own if they wanted to, but outside of the reason "Just because" I don't have one

**Comment by Weirdei** [comment]
I personally dont like i3lock, because it doesnt have indication of currently enabled keyboard layout.

**Comment by LukeSmithxyz** [comment]
> I thought that implementing a DM would be nice for some people to choose their own if they wanted to, but outside of the reason "Just because" I don't have one

People could choose DMs as it is, more so if I forced one on it. It brings up issues of compatibility with people's preexisting systems, not to mention that I (and most of the powerusers) flatly would never use a DM.

**Comment by Pwhitcomb** [comment]
Make sense
