### ISSUE TITLE
Not an issue, but a query

### ISSUE THREAD

**Issue by kcallis** [LukeSmithxyz/LARBS#166]
I know that there are changes to LARBS that are made occasionally.  I do know that once I have installed LARBS, I know that there is no option to "upgrade". So how does one update if for instance, Luke makes changes to his configuration files to fix a problem, and it need to installed in the local machine, or he decides to add (or remove) applications. 

I have finally started using **git**, my knowledge is limited. I suppose that I should have cloned his repository and be able to make changes. More importantly, how to I retain my changes in the various changes in configuration?

**Comment by drake-newell** [comment]
@kcallis while in your home directory, just run git pull to update. This does the same thing as git fetch followed by git merge.
