### ISSUE TITLE
Audio control not working properly

### ISSUE THREAD

**Issue by KarukSophia** [LukeSmithxyz/LARBS#167]
In the top bar, the volume is not shown only the percentage character. The keyboard shortcuts (including the F-keys) does not work either. I can change volume manually in alsamixer though. My computer is a ThinkPad T440s, if it is of any relevance. Any idea why the audio control doesn't work?

**Comment by LukeSmithxyz** [comment]
The bindings by default look for the default alsa output, so it might be that your intended output is not the default. Or did you install pulseaudio on top of everything?

**Comment by KarukSophia** [comment]
You might be right. When I open up alsamixer the labels are as follows: HDMI = 0, PCH = 1 and my external USB sound card = 2. It seems to prioritize USB -> PCH -> HDMI which is correct though. I did have PulseAudio installed, I used it to see if I could solve this issue, but it didn't help so I uninstalled it.

**Comment by seliwia** [comment]
I'm interesting on that one too. I installed pulseaudio to quickly switch from my usb headphones to inbuild. Now, if I mute sound with my keyboard I can't unmuted with the same bind. I have to open pavucontrol and unmute from output device.

**Comment by ramzan3019** [comment]
The audio is not working. I also deleted pulseaudio,pipewire and alsa. and installed them afterwards but it is not working still.
