### ISSUE TITLE
cant start after qxl

### ISSUE THREAD

**Issue by ameeno** [LukeSmithxyz/LARBS#168]
Hello, I tried to install larbs into a qemu-kvm vm (a normal procedure for testing)

after installing xf86-video-qxl the script refuses to launch x with an error after a reboot.

all I wanted to do was to have this VM automatically resize display's as the window does, so I can actually read the thing and view the thing.

not sure how this is tested, One would expect that it would be tested in a VM.

The error looks like this:

xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)

**Comment by badspelr** [comment]
I have a similar issue, installed into a kvm about a month ago, all was fine until I did a full system upgrade this morning (pacman -Syyu). 

I never had the qxl driver installed but if I do install it I get the same error plus some.

Has something to do with the current Arch release I'm assuming.

I can post all the logs if anyone is interested.

**Comment by badspelr** [comment]
Running 4 different instances of Arch as VM's, they all broke with the latest version. 5.5.3-arch-1. Seems to have nothing to do with LARBS.

**Comment by badspelr** [comment]
This is the package that got upgraded and wreaked havoc:
`[2020-02-14T05:00:34-0500] [ALPM] upgraded mesa (19.3.2-2 -> 19.3.4-1)`
_

For me downgrading the mesa package fixed all the issues.

`cd /var/cache/pacman/pkg`

`pacman -U mesa-19.3.2-2-x86_64.pkg.tar.zst`


`

**Comment by LukeSmithxyz** [comment]
Seems like it's not our problem then.
