### ISSUE TITLE
st crash 

### ISSUE THREAD

**Issue by focus85** [LukeSmithxyz/LARBS#169]
st still have a problem with displaying emoji with the new larb and st update

**Comment by drake-newell** [comment]
You might want to do a fresh install of st by cloning a new copy of the repo and doing a make/sudo make install. It worked for me when updating it didn't fix emojis.

**Comment by focus85** [comment]
@drake-newell no luck with that instruction. Thank you tho for your response :)

**Comment by drake-newell** [comment]
@focus85 Do you have libxft-bgra installed? It's the patched program that allows st emojis

**Comment by focus85** [comment]
@drake-newell ah, yes that's fixed it, i had libxft not libxft.bgra. Thank you!!
