### ISSUE TITLE
website points to a 404

### ISSUE THREAD

**Issue by DickThomas** [LukeSmithxyz/LARBS#171]
Hello,
Thanks for such an awesome config and while reading the site I spotted the link in line 
"You can check out the programs list that LARBS parses for installation right here! It also gives a brief explanation of why the program is included."

Is a 404 it points to https://github.com/LukeSmithxyz/LARBS/blob/master/archi3/progs.csv

regards
Dick Thomas

**Comment by LukeSmithxyz** [comment]
Should be fixed now.
