### ISSUE TITLE
Dual welcoming message

### ISSUE THREAD

**Issue by jcguu95** [LukeSmithxyz/LARBS#172]
This issue is not crucial, but it bugged my mind a while and I just found out why.

After a fresh install of arch and LARBS, logging into i3 arises two welcoming messages (so one is bloated, sorry to have misused this word). One is coming from `~/.config/i3/config`

```
exec_always --no-startup-id notify-send -i ~/.local/share/larbs/larbs.png 'Welcome to LARBS:' 'Press Super+F1 for the manual.' -t 10000
```

which has been inserted during LARBS installation. Another is coming from the current `~/.xprofile` in `/voidrice`

```
notify-send -i ~/.local/share/larbs/larbs.png "Welcome to LARBS" "Press super+F1 for the help menu." # LARBSWELCOME
```

**Comment by vladdoster** [comment]
I think this has been resolved.

**Comment by LukeSmithxyz** [comment]
Yeah, I forgot to close it.
