### ISSUE TITLE
Unable to find where keys are mapped?

### ISSUE THREAD

**Issue by rublev** [LukeSmithxyz/LARBS#174]
Hey I'm still pretty new to arch and this setup is fantastic to get up and running. Love it. My only problem is I'm trying to rebind super/alt on my thinkpad and change the font system wide (well, replacing the serif one is really all I need).

I want to add the following to xmodmap:

```
! Exchange left Alt and left Win
remove mod1 = Alt_L
remove mod4 = Super_L
add mod1 = Super_L
add mod4 = Alt_L
```

But have no idea where to find it. I also don't have a scripts directory inside ~/.config, or ~, or ~/.config/i3. Where do these remappings happen?

Also how can I change the font system-wide? Don't like the serif.

Thanks Luke.

**Comment by LukeSmithxyz** [comment]
Scripts are in `~/.local/bin/` the `remaps` script there is where I keep the keyboard changes, but it's not an xmodmap file. You could just add one yourself and source it there.
