### ISSUE TITLE
libxft-bgra doesn't get installed

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/LARBS#179]
the libxft-bgra package doesn't get installed on a fresh larbs install even thou it is is in the list of programs

**Comment by LukeSmithxyz** [comment]
Well then that's doubly weird because in 26e585d1592eac41703674a0c1ff2bb623cf230e yesterday I _removed_ it from the list of programs and had it installed individually at the end due to problems installing it during the main installation loop.

Are you sure you ran the most recent version?

**Comment by LukeSmithxyz** [comment]
I think I've found the issue. If you run the script as is on machine where you don't have the time/date a little off, curl when downloading `libxft-bgra` will yield a certificate error. I think I might have `ntpdate` automatically sync the time on the start of the script.

I'm not sure why this can happen only for `libxft-bgra`, but it might have to do when their SSL certificate expires now.

**Comment by LukeSmithxyz** [comment]
Okay, I've added this in f4cd777 and I'm going to guess that was the original problem, so I'm closing this issue, but I'll be doing more testing today to make sure.

**Comment by goldcoders** [comment]
use libxft-bgra-git instead

**Comment by neahahul** [comment]
> use libxft-bgra-git instead

that gives another error, i think it's an issue related to the macros

`BuG.am: error: 'install.sh' is an anachronism; use 'install-sh' instead
src/Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1
==> ERROR: A failure occured in build().
       Aborting. . .
Error making: libxft-bgra-git`

**Comment by neahahul** [comment]
> > use libxft-bgra-git instead
> 
> that gives another error, i think it's an issue related to the macros
> 
> `BuG.am: error: 'install.sh' is an anachronism; use 'install-sh' instead src/Makefile.am: installing './depcomp' autoreconf: automake failed with exit status: 1 ==> ERROR: A failure occured in build(). Aborting. . . Error making: libxft-bgra-git`

the signature issue was probably solved now, i just had to get the key and download it
https://aur.archlinux.org/packages/libxft-bgra/
they updated the package on the aur website so i think you won't have any problems downloading it, just use `git clone https://aur.archlinux.org/libxft-bgra.git` then `makepkg` and you're good to go.
it works perfectly.

**Comment by crabtreee** [comment]
Guys, none of above solutions doesn't work for me, i always get "wrong pgp" error :/

**Comment by mohamadali-halwani** [comment]
> Guys, none of above solutions doesn't work for me, i always get "wrong pgp" error :/

please post the error message

**Comment by crabtreee** [comment]
@mohamadali-halwani 
`gpg: keyserver receive failed: General error` after `yay -S libxft-bgra` and `ERROR: One or more PGP signatures could not be verified!` after `git clone https://aur.archlinux.org/libxft-bgra.git` `cd libxft-bgra` `makepkg`. I'm wondering is it possible to download and add that pgp key manually?

**Comment by mohamadali-halwani** [comment]
> they updated the package on the aur website so i think you won't have any problems downloading it, just use `git clone https://aur.archlinux.org/libxft-bgra.git` then `makepkg` and you're good to go.
> it works perfectly.

@crabtreee try this one
while it is possible to add the pgp key manually, but you don't need to do so now if you applied the steps presented above

**Comment by crabtreee** [comment]
@mohamadali-halwani 
> @crabtreee try this one, it worked for me pretty well

As I have written above, i tried `git clone https://aur.archlinux.org/libxft-bgra.git` and I still get `FAILED (unknown public key .... ERROR: One or more PGP signatures could not be verified!`

**Comment by mohamadali-halwani** [comment]
> @mohamadali-halwani
> 
> > @crabtreee try this one, it worked for me pretty well
> 
> As I have written above, i tried `git clone https://aur.archlinux.org/libxft-bgra.git` and I still get `FAILED (unknown public key .... ERROR: One or more PGP signatures could not be verified!`

try ```gpg --recv-key <the key number>```

**Comment by crabtreee** [comment]
I solved it! I downloaded https://raw.githubusercontent.com/clearlinux-pkgs/setxkbmap/master/CFDF148828C642A7.pkey and `gpg --import CFDF148828C642A7.pkey` and above steps worked! Hurray ;-)
