### ISSUE TITLE
No terminal (st) installed in Void

### ISSUE THREAD

**Issue by ovinsnes** [LukeSmithxyz/LARBS#180]
$mod+Return returns no terminal in void i3
It appears neither `st` or `dmenu` have been installed

Is this intended or a bug?

**Comment by LukeSmithxyz** [comment]
Lol, no it's not intended. I haven't tested LARBS on Void yet and it's experimental there.

There are some compile time packages I believe are needed for Void; I'm just not entire sure what they are. Have you tried installing my st or dmenu builds manually? What kind of errors pop up?

**Comment by ovinsnes** [comment]
sudo make install yields:

c99 -I/usr/X11R6/include  `pkg-config --cflags fontconfig`  `pkg-config --cflags freetype2` -DVERSION=\"0.8.2\" -D_XOPEN_SOURCE=600  -O1 -c x.c
Package fontconfig was not found in the pkg-config search path.
Perhaps you should add the directory containing `fontconfig.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fontconfig' found
Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'freetype2' found
x.c:15:10: fatal error: X11/Xft/Xft.h: No such file or directory
   15 | #include <X11/Xft/Xft.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:22: x.o] Error 1

**Comment by LukeSmithxyz** [comment]
Okay. Install `libXft-devel` and see if that fixes it.

**Comment by ovinsnes** [comment]
Just what the doctor ordered. Thanks!

**Comment by LukeSmithxyz** [comment]
That fix dmenu too? I've added it to the programs to autoinstall now.

**Comment by ovinsnes** [comment]
Oh, I didn't compile dmenu but installed it from the package manager
