### ISSUE TITLE
Autostart sxhkd

### ISSUE THREAD

**Issue by lyh970817** [LukeSmithxyz/LARBS#181]
I am not able to find in the script where to put `sxhkd` to autostart - done some code searching on github for your dotfiles with no results. Not really an issue since when I installed the entire larbs they both work fine and I got `sxhkd` to work following your suggestions in the video by putting it in `.xinitrc` but this doesn't seem to be where it is now.

Thanks so much!

**Comment by LukeSmithxyz** [comment]
I don't use sxhkd anymore at all. All the bindings are in their respective window managers.
