### ISSUE TITLE
Icons not shown properly after snap install.

### ISSUE THREAD

**Issue by rldmt** [LukeSmithxyz/LARBS#183]
I installed snap. After restarting it , the icons are not shown correctly although they are clickable and functional.

**Comment by rldmt** [comment]
![pic-full-200314-0234-32](https://user-images.githubusercontent.com/19992681/76672404-bee1e400-659c-11ea-8ae5-6235e7a93d51.png)

**Comment by LukeSmithxyz** [comment]
I'm not sure what snap is, but it looks like it enforced a font change that overwrote the default fonts in LARBS. Did it change your fontconfig file?

**Comment by rldmt** [comment]
Snaps as in linux packages format from snapcraft . I installed snappy then after I installed some snap packages from snappy store it maybe broke the font. Basically I bloated it a little bit. I don't know what .fontconfig folder looked before but now two files ." 923e285e415b1073c8df160bee08820f-le64.cache-7" file has this content:
`
���
@XX��k^5�
/usr/share/fonts/noto������1Yq�	��
����)9I!Y"q#�$�%�(./10A2Q3aNoto Color EmojienRegularenNoto Color EmojienT@Y@@[@dGOOG/usr/share/fonts/noto/NotoColorEmoji.ttf������0Pp����0Pp����0Pp��� !#$%&')+02������������ ���@x@2!M���i��`0��'$�T �P���0�! ���@������������������������������������������������������������������������������?~������<a0p
��������������������?�'?���������������{�����������������?���������otlayout:DFLTTrueTypeNotoColorEmoji@
`
 the other file "CACHEDIR.TAG" has some signature .

**Comment by LukeSmithxyz** [comment]
There is no `.fontconfig/` directory in LARBS, only `~/.config/fontconfig/`. If it takes precedence, it nearly certainly is the root of the problem. Try renaming `.fontconfig/` to something else and see what it does.

> Snaps as in linux packages format from snapcraft . I installed snappy, then I installed some snap packages from snappy store.

As someone who doesn't know what this is, this sentence sounds like one of the most ridiculous ever from some kind of Dr. Seuss dimension.

**Comment by rldmt** [comment]
Forgive me if I am not clear enough. Thanks for the clarification. What I wanted to say is that I installed some snap packages from snapcraft.io.  Maybe that caused the problem since it requires root privileges to install any snap packages.

**Comment by rldmt** [comment]
I renamed the folder name. restarted and still no good.

**Comment by LukeSmithxyz** [comment]
Okay, so after reading, snap is some kind of distro-independent package manager? Is that right?

I'll go ahead and tell you that's not a good idea and it will nearly certainly cause irreparable conflicts with Arch's configurations. It would probably be better to use the AUR or install a package manually.

Probably some package or snap itself edited system font settings. You'll have to change them match to get the correct font. If you don't know anything about font config, check the documentation; the bar should usually look for your default monospace font, and you can run `fc-match monospace` to see what that is at the moment.

Anyway, I'm going to close this issue because it's not a LARBS problem.

**Comment by rldmt** [comment]
You are right. Probably I should have stayed with arch packages. Still I am very pleased about LARBS.

**Comment by vicprk** [comment]
snapopolis

**Comment by rldmt** [comment]
What can I do haha. It didn't came out good because my grammar is lacking a little bit. Anyway all is good.
