### ISSUE TITLE
lf makes st crash

### ISSUE THREAD

**Issue by morphingSamurai** [LukeSmithxyz/LARBS#184]
I installed the i3 variant and if I press mod+r st opens but crashes instantly.
If I open ranger from the terinal it opens fine though.

**Comment by drake-newell** [comment]
Luke recently changed the file manager from ranger to lf, so mod+r is actually trying to open lf, which you don't have installed. You can either install lf or change that keybind to ranger in your i3 config

**Comment by morphingSamurai** [comment]
Thank you for the reply
After the installation of lf (I noticed that it was alredy installed) the issue persists. I tried also to open lf from the terminal and it crashes, so what is the problem?

**Comment by drake-newell** [comment]
@morphingSamurai Frankly I'm not sure, but you could just change the binding to ranger in your i3 config

**Comment by morphingSamurai** [comment]
Yes as a workaround I changed the setting to ranger, for now this is the only solution I found
