### ISSUE TITLE
Font spacing too big?!

### ISSUE THREAD

**Issue by adamkali** [LukeSmithxyz/LARBS#186]
Hi, after doing a full system update and upgrade on my computer and restarting, I found that the text spacing in the terminal and dmenu was too large. I expect that this has something to do with the ttf size but i cant even navigate the terminal to change anything... any ideas? Everything works peachy except for the ttf size so this may be a dumb question, but i still do not understand why the update would change the spacing. thanks in advance.

Here is what I mean:
![pic-full-200322-1007-29](https://user-images.githubusercontent.com/43151285/77251505-129b9f80-6c25-11ea-9012-43d6663b4895.png)

**Comment by LukeSmithxyz** [comment]
That's not font size but font spacing. What does `fc-match mono` return? Have you added any unique fonts or change font/Xresources settings?

**Comment by adamkali** [comment]
`fc-match mono` returns the following: `Inconsolata-Regular.ttf: "Inconsolata" "Regular" `. I may be wrong but isn't this the default ttf for larbs? 

To answer your second question, no I have not changed anything to do with the font/Xresources settings. 

Also thank you for your quick response! :)

**Comment by persakiss** [comment]
Issue replicated on my system with LARBS dwm and full-system upgrade.

**Comment by LukeSmithxyz** [comment]
Yeah okay, it's an upstream issue with `ttf-inconsolata`. Not sure exactly what's wrong now. A temporary fix would be replacing Inconsolata with Liberation Mono or Nimbus Mono or your own desired monospace font in `~/.config/fontconfig/fonts.conf`.

**Comment by LukeSmithxyz** [comment]
Or of course you can downgrade to the old version of inconsolata and tell pacman to ignore it for now.

**Comment by adamkali** [comment]
Well temporary fix works well for right now. I am using Space Mono for now... I hope that there will be some fix in the future. 
Thanks again!

**Comment by sudo-ghost** [comment]
this issue was driving crazy all day. im glad i checked lukes website to see if he had said anything about it.

**Comment by awelton85** [comment]
Thank you. I couldn't read the terminal font well enough to find anything to troubleshoot.

**Comment by DarkAdin** [comment]
Downgrading the font to the previously installed package and ignoring its updates in pacman worked like a charm for me. Thank you!

**Comment by Abh15h3k** [comment]
Another temp fix would be changing cwscale (in ~/.local/src/st.git/config.h) to about 0.3 (from 1.0)

**Comment by ShipwreckSiren** [comment]
Did this affect NetworkManager in anyway? I'm new to Arch and LARBS (less than a week) and noticed yesterday that my NetworkManager was not working with WiFi. I suspected I may have done something wrong while messing with NetworkManager on Raspberry Pi, so I reinstalled LARBS and have rebooted to this loveliness.

**Comment by slappy96** [comment]
I did not see any impact to NetworkManager while affected (fixed now thanks to Luke's suggested fix in ~/.config/fontconfig) by the Inconsolata font bug

**Comment by majamin** [comment]
I downgraded `ttf-inconsolata` with `pacman -U /var/cache/pacman/pkg/ttf-inconsolata-1:2.0.0.1-3-any.pkg.tar.xz` then added `IgnorePkg = ttf-inconsolata` to `/etc/pacman.conf`. Now you can full system update (minus the offending update).

**Comment by MobleVortex** [comment]
Was able to fix this issue by installing the ttf-liberation package as it's listed in ~/.config/fontconfig/fonts.conf.

**Comment by gutobyte** [comment]
same problem here. :(

**Comment by jwestraadt** [comment]
For the absolute beginners like me...
Changing the `~/.config/fontconfig/fonts.conf` file alone won't help. 

You need to install the font(s) you want as well: `pacman -S ttf-liberation`

**Comment by jcguu95** [comment]
Sorry for asking the same issues.. also I appreciate your default choice of `Inconsolata`. Other fonts are not even close aesthetically.

**Comment by kcallis** [comment]
I am in the same boat here... I did install liberation, but still no joy. I added liberation to ~/.config/fontconfig/fonts.conf, rebooted and still having the same issue. What am I missing when trying to resolve this issue?

**Comment by jcguu95** [comment]
## Temporary solution

```
# Downgrade `ttf-inconsolata` to older version
sudo pacman -U https://archive.archlinux.org/packages/t/ttf-inconsolata/ttf-inconsolata-1%3A2.0.0.1-3-any.pkg.tar.xz

# Tell pacman to ignore auto-upgrading ttf-inconsolata in the future.
echo "IgnorePkg = ttf-inconsolata" >> /etc/pacman.conf
```

You can always take that line away from `pacman.conf` in the future, while it's hopefully fixed.

**Comment by kcallis** [comment]
I have already did that previously and still no changes.

**Comment by slappy96** [comment]
The only thing I see not mentioned is I replaced inconsolata with libertine where it was actually mentioned in fonts.conf.  apologies if that was implied above as a step already taken

**Comment by charlie39** [comment]
Yap I got today, changed font to Libertine, didn't like it , downgraded inconsolata, told pacman to ignore it.
Thanks for the suggestions

**Comment by kcallis** [comment]
For the cavemen that are still out here... I have downgraded inconsolata and no changes to the font (meaning it still looks like crap). I have tried installing libertine, with no change in look and still when I do a ```fc-match mono```, I still end up with *Noto Sans* as the default font, although I have (at least in my mind) removed Noto Sans and all of the family. 

What what am I missing?

```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>

 <alias>
    <family>serif</family>
    <prefer><family>Linux Libertine</family></prefer>
  </alias>
  <alias>
    <family>sans-serif</family>
    <prefer><family>Linux Biolinum</family></prefer>
  </alias>
  <alias>
    <family>sans</family>
    <prefer><family>Linux Biolinum</family></prefer>
  </alias>
  <alias>
    <family>monospace</family>
  <alias>
    <family>sans</family>
    <prefer><family>Linux Biolinum</family></prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer><family>Liberation Mono</family></prefer>
  </alias>

   <!-- This sets Symbola as the final fallback font for the monospace font family. -->
  <match target="pattern">
        <test name="family"><string>monospace</string></test>
        <edit name="family" mode="append"><string>Symbola</string></edit>
    </match>

</fontconfig>
```

**Comment by LukeSmithxyz** [comment]
Well, delete the stray extra `monospace` line in the middle and the unmatched `<alias>` above it for one.

You can model yours after mine if needbe: https://github.com/LukeSmithxyz/voidrice/blob/master/.config/fontconfig/fonts.conf

**Comment by kcallis** [comment]
Luke,

Even using your ```fonts.conf```, rebooting and even installing the noto-fonts, everything is still off. Although, I will say that for some reason apps like Firefox looks very sharp.

**Comment by kronikpillow** [comment]
I wanted to report to @LukeSmithxyz that i recently did a reisntall of my system, and that the issue persists even thou you changed the default mono font from Inconsolatat to Liberation Mono, it seems to still use Inconsolata, now luckily I made a backup of my cache from my previous install and have a backed up version of ttf-inconsolata v2, and by removing inconsolata v3 and installing inconcolata v2 from a local package seems to completely remove the problem

**Comment by LukeSmithxyz** [comment]
Inconsolata has been totally removed from the install as of a couple days ago. I suppose if they ever fix the issue, someone can feel free to tell me and I'll consider readding it.

This has been the first _actual_ breackage in a package in LARBS in a while, so I'm a little annoyed and untrusting about it. I might go ahead and remove other non-essential packages.

I chose Inconsolata because of its good unicode coverage. If anyone knows of a _stable_ monospace font with similar coverage, feel free to tell me.

**Comment by jonmed** [comment]
What about [nerd-fonts-inconsolata](https://aur.archlinux.org/packages/nerd-fonts-inconsolata/)?
It doesn't, currently, have the same issue that the normal Inconsolata font has.

**Comment by jonmed** [comment]
Forget that. That nerd font has its own issues.
Like putting a phone icon everywhere a "fi" appears on brave browser.
