### ISSUE TITLE
How to completely remove LARBS with its configs?

### ISSUE THREAD

**Issue by sezermehmed** [LukeSmithxyz/LARBS#187]
I restored my system to remove LARBS. However, dotfiles (voidrice) could not remove. Now I can not do any customization to my zsh(My customs are not loading, old larbs's configs default). Is there any official or true way to uninstall LARBS?  Beceuse There are hundreds of files, not only old zsh configs.

**Comment by LukeSmithxyz** [comment]
Delete the config files you don't want. Assuming you're using `~/.zshrc`, that isn't read because `~/.zprofile` moves the `ZDOTDIR` out of the home directory to avoid mess. Remove that like if you don't want it.
