### ISSUE TITLE
not a bug, but why is the bashrc 'vanilla' even though it has Colour? How do I change the colour?

### ISSUE THREAD

**Issue by siggines** [LukeSmithxyz/LARBS#190]
When I edit bashrc (which is 'vanilla') it changes naught. What file determines the colour of whatever you call the bit which says [user@host], I notice there is also colour on the tty terminal so can't be anything in st config, and it isn't the bashrc. Sorry for laziness I should really figure this out myself but hay ho

**Comment by LukeSmithxyz** [comment]
zsh is the shell in LARBS.

**Comment by kronikpillow** [comment]
LOL

**Comment by siggines** [comment]
> zsh is the shell in LARBS.

oh I see! weird that there would even be a bashrc in my home directory
