### ISSUE TITLE
Cannot change keyboard layout

### ISSUE THREAD

**Issue by longestmt** [LukeSmithxyz/LARBS#195]
In my most recent installation of LARBS (both i3 and DWM) I started experiencing an issue when attempting to switch my keyboard layout to Colemak. 

`loadkeys colemak` returns the following error:
`Couldn't get a file descriptor referring to the console`

However `setxkbmap us -variant colemak` correctly loads the layout.

No idea what's going on.

Note: I’m also experiencing a font spacing issue but that issue has been submitted by someone else.

**Comment by danilovicente** [comment]
Did U try run loadkeys as root?

**Comment by longestmt** [comment]
@danilovicente running `loadkeys colemak` as root doesn't elicit an error however it also doesn't change the keyboard layout.

**Comment by g-w1** [comment]
@longestmt  ```loadkeys colemak``` only works in the tty terminal. ```setxkbmap``` sets the keyboard in X. If you want to always be in colemak, just modify .local/bin/remaps (or any file that gets run at startup of x) and put ```setxkbmap -variant colemak```. I hope this helps.

**Comment by longestmt** [comment]
> @longestmt `loadkeys colemak` only works in the tty terminal. `setxkbmap` sets the keyboard in X. If you want to always be in colemak, just modify .local/bin/remaps (or any file that gets run at startup of x) and put `setxkbmap -variant colemak`. I hope this helps.

This worked for me. Thank you!

I placed it above the other scripts so caps lock will still get bound to super.
