### ISSUE TITLE
Libxft-bgra

### ISSUE THREAD

**Issue by fuilip123** [LukeSmithxyz/LARBS#196]
LARBS is installing the wrong package, it installs libxft, not libxft-bgra, which makes the system crash and you need to manually install bgra and uninstall libxft (their in conflict)

**Comment by LukeSmithxyz** [comment]
Are you using an Arch distro or Void? It should be force-installed at the end of an Arch distro in the script, but I may've missed something.

**Comment by fuilip123** [comment]
Arch

**Comment by kronikpillow** [comment]
it installed the right package for me without any issues ...

```
aur/libxft-bgra 2.3.3-1 (+6 2.50%) (Installed)
    libXft with BGRA glyph (color emoji) rendering & scaling patches by Maxime Coste
```

I think you have installed from an outdated version of LARBS, the recent changes in the LARBS repo address this issue
