### ISSUE TITLE
The whole system lag on volume changing

### ISSUE THREAD

**Issue by behradjafari1** [LukeSmithxyz/LARBS#198]
I have larbs fresh install and when i change the volume the whole system start laging for 5sec , is anybody have this issue?

**Comment by kronikpillow** [comment]
yup, I have opened the issue on [lmc + pulseaudio](https://github.com/LukeSmithxyz/voidrice/issues/508)

**Comment by LukeSmithxyz** [comment]
It's definitely related to the pkill command. Not sure why it's doing this now as I don't think it's happened when using a setup like this before.

**Comment by behradjafari1** [comment]
yeah that was pkill command and i just comment it out for now and works fine

**Comment by luukvbaal** [comment]
`kill -RTMIN+10 $(pidof dwmblocks)` instead of `pkill` produces no such lag FYI.

**Comment by LukeSmithxyz** [comment]
Is that so? I'll try it out. If so, I wonder why...
