### ISSUE TITLE
(Void) LARBS didn't create a user

### ISSUE THREAD

**Issue by ProwlingPython** [LukeSmithxyz/LARBS#199]

**Comment by drake-newell** [comment]
Shouldn't you have made a user in the  void install process?

**Comment by ProwlingPython** [comment]
I did.

**Comment by drake-newell** [comment]
@ProwlingPython Then why would it be a problem that LARBS didn't create a user, or did you mean that LARBS didn't set up the user properly, in which case how specifically?

**Comment by ProwlingPython** [comment]
The new user doesn't show up when I use the users command, and I can't use it to log in

**Comment by LukeSmithxyz** [comment]
If you're using void, a user will be added, but the password will not. If you just use the script for the user you started with it should work although the password won't change. I haven't updated the interface to reflect this.

`users` only shows logged in users.

**Comment by ProwlingPython** [comment]
Doing that worked, but logging in briefly shows the graphical environment, then immediately logs me out .
