### ISSUE TITLE
can't download!!

### ISSUE THREAD

**Issue by Mesbah214** [LukeSmithxyz/LARBS#206]
I am using Manjaro Kyria 19.0.2 and i have been expecting to use LARBS.

To download i open konsole and type `sudo su root` and paste the first line. It goes without any error. But as soon as i enter `sh larbs.sh` i get error saying: 
```
ERROR:
Are you sure you're running this as the root user and have an internet connection?
```
I have an internet connection that's i am sure. Am i doing wrong any thing else? The system is not fresh. I have been using for about a month.

**Comment by LukeSmithxyz** [comment]
If you're running some Manjaro DE, chances are it started 50 thousand
background processes including pacman behind your back so if pacman is
already running it wouldn't be able to install the first program.

Run
pacman --noconfirm --needed -S dialog
manually and see what it says.

**Comment by Mesbah214** [comment]
Thanks brother. It is working. But i had to drop off the download process, my net is probably slower than yours. Took nearly one hour but couldn't wrap up. going to try tomorrow.
