### ISSUE TITLE
Keeps installing after wrong username input

### ISSUE THREAD

**Issue by louiswolfers** [LukeSmithxyz/LARBS#21]
Yesterday I tried LARBS and when typing the username I wrote a capital letter. LARBS kept installing everything and when finished, the user was never created, as the username can't have a capital letter.
It's not really a big deal, but ya know

**Comment by Hannibal-ad-Portas** [comment]
I had the same issue. Took me trying to use usreadd to figure out what the issue was

**Comment by LukeSmithxyz** [comment]
Sorry for the delay. It will now prompt users again until they give a valid UNIX username.
