### ISSUE TITLE
Xorg

### ISSUE THREAD

**Issue by fuilip123** [LukeSmithxyz/LARBS#210]
Lately I invested in a thinkpad x60, I did the standard arch installation procedure and then installed Larbs. Now when xorg is about to start it fails with the error message “Addscreen/ScreenInit failed for driver 0”
What do I do?

**Comment by fuilip123** [comment]
- Tried again now it says something about permission

**Comment by fuilip123** [comment]
Now it starts but crashes, in tty2 when I try to update the system eg it says that _user_ is not allowed to run usr/bin/Pac-Man as root

**Comment by fuilip123** [comment]
Now I can run sudo commands but xorg still crashes

**Comment by fuilip123** [comment]
![image](https://user-images.githubusercontent.com/62574714/79777033-f3cd1d80-8336-11ea-9078-6e0563be7980.png) here is a crappy picture of the error message

**Comment by g-w1** [comment]
Did you try running it in i3 instead of dwm?

**Comment by fuilip123** [comment]
I want dwm though

**Comment by drake-newell** [comment]
@fuilip123 Try installing the full xorg package

**Comment by fuilip123** [comment]
Problem persist

**Comment by fuilip123** [comment]
I3 works

**Comment by fuilip123** [comment]
Can’t run any of the scripts though. Eg if I type cpu in Terminal the window closes

**Comment by LukeSmithxyz** [comment]
this is the same issue as https://github.com/LukeSmithxyz/LARBS/issues/209

libxft-bgra isn't installing due to an upstream error and it's required to render emojis. dwm will crash instantly.

The problem only arose today, so they might fix it imminently.

See https://gitlab.freedesktop.org/xorg/lib/libxft/-/merge_requests/1

**Comment by fuilip123** [comment]
I don’t think so...![image](https://user-images.githubusercontent.com/62574714/79794316-554eb580-8352-11ea-9d36-5779cd34654a.jpeg)
Dwm won’t even display

**Comment by g-w1** [comment]
I just uninstalled libxft and installed libxft-bgra using yay and there were no error messages. Dwm also works. I think they patched it.

**Comment by LukeSmithxyz** [comment]
It could also be that `libxft-bgra` is failing in the installation. I'll add some failsafes.

**Comment by fuilip123** [comment]
Keep getting this error![Uploading 79794662...]()

**Comment by fuilip123** [comment]
Won’t wor

**Comment by fuilip123** [comment]
Kind of panicking

**Comment by fuilip123** [comment]
Now this![Uploading 79795341...]()

**Comment by LukeSmithxyz** [comment]
Stop spamming my inbox. Read what I said. Reinstall libxft-bgra.

**Comment by fuilip123** [comment]
Didn’t work

**Comment by LukeSmithxyz** [comment]
If it actually "didn't work." You might want to install driver packages like `xf86-video-intel`. Not sure for the X60. I've never tried the build on a 32 bit machine.

**Comment by fuilip123** [comment]
Is x60 32 bit? I have a dual core 2 cpu

**Comment by thevirtuoso1973** [comment]
I had an identical problem, but Installing `libxft-bgra` worked` to fix it. 
(Although, I had to skip pgp checking due to some _possibly unrelated_ issue with pgp keys.)

**Comment by vektorrr** [comment]
Just wanted to say I had the same issue. 

Fresh install of Arch.
Installed LARBS.
Went to log in and dwm crashed immediately. I uninstalled `noto-fonts-emoji` and I was okay but was obviously missing the emojis. 

Saw this issue and installed both `noto-fonts-emoji` via pacman and `libxft-bgra` via yay and everything is working correctly. `libxft` was uninstalled when libxft-bgra was installed.

Thank you Luke!
