### ISSUE TITLE
Cursor moves itself

### ISSUE THREAD

**Issue by jcguu95** [LukeSmithxyz/LARBS#218]
My cursor moves itself. Sometimes slightly, but sometimes quite drastically. And no, I don't live in a haunted house (TODO: make sure).

Not sure if this is an internal issue of LARBS, but I don't think it's obvious to fix after a quick search online. People suggest that this happens often with computers whose OS is freshly installed, and you need to tinker lower level configs to fix. My setup is proudly based on LARBS, so I wonder if others have similar issue that I have.

**Comment by fuilip123** [comment]
It could be your trackpoint that is bad, if you’ve got a thinkpad

**Comment by jcguu95** [comment]
I am going to clean it.. for the first time in my life.

**Comment by LukeSmithxyz** [comment]
What kind of computer are you using? Any change if `xf86-input-synaptics` is installed with restart?

**Comment by jcguu95** [comment]
I'm on X220. It has been dancing for the whole day, no matter what attempts I made. And then it stopped an hour ago. I hope it has been fixed magically. Otherwise, I will come back and report more I know.

**Comment by LukeSmithxyz** [comment]
This is nearly certainly a hardware problem.
