### ISSUE TITLE
Super+F1 not using latest changes to larbs.mom file

### ISSUE THREAD

**Issue by Malod219** [LukeSmithxyz/LARBS#219]
Under a larbs install, the config.h file for DWM is slightly incorrect. You can see this [here](https://github.com/LukeSmithxyz/dwm/blob/806bb2a2bfde3d50d7405126729ed2a2544f11ca/config.h#L206). The larbs.mom file is not found at /`usr/local/share/dwm/` but is found at `~/.local/src/dwm/`.

This means that any changes to the larbs.mom file won't be reflected when a user does Super+F1. I've fixed this on my end by changing that line of code. As for a more universal fix, I'm unsure if it's specifically a DWM issue or a Larbs installation issue? I'm also unsure why it works for first time install?

**Comment by LukeSmithxyz** [comment]
When you install or reinstall dwm, it installs the readme in the proper location in `/usr/local/share/dwm/`. Obviously it's supposed to read the installed manual, not one that is in a repository which could be located anywhere on the machine.
