### ISSUE TITLE
(Void) Cant login

### ISSUE THREAD

**Issue by DawaAwA** [LukeSmithxyz/LARBS#220]
I recently ran larbs.sh, no issues were found it said, but when I tried to log in it said login incorrect, I tried resetting the password with passwd and it didnt work, I tried using larbs with the user that the installer makes didnt work either, tried making my own user and that didnt work as well.

**Comment by LukeSmithxyz** [comment]
Duplicate https://github.com/LukeSmithxyz/LARBS/issues/177
