### ISSUE TITLE
How can I uninstall LARBS and all config files it has created? Having issues with 2009 Macbook Pro and want to isolate the issues

### ISSUE THREAD

**Issue by ShipwreckSiren** [LukeSmithxyz/LARBS#222]
I've been using Arch and LARBS since late March on my 2009 Macbook Pro. I have been having issues with suspend/hibernate, my display brightness, and battery. When suspending/hibernating my display opens to a black screen for many moments and will not respond. I am unable to adjust my display brightness even with pommed installed. Lastly, something seems to be running that is killing my battery quickly. I just replaced the battery prior to installing Arch so the battery shouldn't be the issue. I have tried troubleshooting the issues for weeks now and think that since my computer is so old that it might be better to just start fresh by removing LARBS and installing certain applications/configuration files manually. I'm still a new Linux/Arch user so I don't know how to figure out what's going on and don't want to mess something up by going through config files I'm not familiar with. Is there a way to remove everything from my laptop prior to installing LARBS without having to deleted everything except Arch base files or reinstall from a USB?

**Comment by notdeven** [comment]
I have a Macbook pro retina from 2012, I did my own configuration files and patches. It works flawlessly with no issues.
