### ISSUE TITLE
default color(s) setting

### ISSUE THREAD

**Issue by focus85** [LukeSmithxyz/LARBS#228]
This is not a big issue, but i just cant figure out why I have a different color scheme on startup (see Picture). If I re-run Xresource i get the original LARBS color setting but not on startup, same with dwmbar color and Dunst notification. any comment/suggestions are much appreciated. 
![pic-full-200512-1949-43](https://user-images.githubusercontent.com/17464413/81759717-114f5c00-948b-11ea-8dcd-27f228bcac94.png)

**Comment by LukeSmithxyz** [comment]
If you have pywal installed, the setbg script will automatically run it.
You can disable this by commenting out the relevant line in setbg.

**Comment by focus85** [comment]
ah, thanks Luke :)
