### ISSUE TITLE
Transparency in compton does not work

### ISSUE THREAD

**Issue by 7root** [LukeSmithxyz/LARBS#23]
(I have to note though that I tried these dotfiles in a VM with a Windows host. I will try to run them in a "real" Arch environment later this week)
The cool transparency effect in the terminal is not working. When I try to start compton manually, it throws the following error:
`vsync_drm_wait(): VBlank ioctl did not work, unimplemented in this drmver?`

**Comment by 7root** [comment]
Starting compton as superuser with the -b flag fixes it. It still throws a bunch of errors, but at least transparency works. I'll close this issue.

**Comment by Daenarii** [comment]
Looks like `vsync = "drm";` doesn't work properly for you.
I'm not sure what will work for you but try changing values of `backend` and `vsync` in `~/.config/compton.conf`. Here's the guide: https://github.com/chjj/compton/wiki/vsync-guide

I've also tested it right now and the driver you use makes a difference
I have an NVIDIA graphics card, a GT520M so I use nvidia 390, and here's my observation:

- `backend = "xrender";` works on _nouveau,_ but not on _nvidia-390xx_
- `backend = "glx";` works on _nvidia-390xx,_ but on _nouveau_ the transparent windows will become pink (much worse than not working at all)
