### ISSUE TITLE
arrow keys not working

### ISSUE THREAD

**Issue by sanjeebSubedi** [LukeSmithxyz/LARBS#234]
None of the arrow keys are working for me. I cannot move right or left on workspaces/tags with mod + left/right. None of these key bindings work for me
![pic-selected-200523-2125-10](https://user-images.githubusercontent.com/51266822/82734647-04a8ee80-9d3c-11ea-9adb-f608114a4a9f.png)

**Comment by LukeSmithxyz** [comment]
Well, you have to hold down shift as well.

**Comment by sanjeebSubedi** [comment]
I messed up there but holding down shift doesnot work as well. Out of all the shortcuts associated with arrow keys only the system volume and brightness keys work. Is it a problem specific to me only?
And how can I use the num pad as well while switching wokspaces?
