### ISSUE TITLE
switched to i3 after reboot

### ISSUE THREAD

**Issue by satiankit** [LukeSmithxyz/LARBS#238]
I am pretty new to dwm but have been using the i3 build to while. Recently decided to make the switch to dwm and all was going well until I rebooted and it switched to i3. How can I revert back to dwm?

**Comment by LukeSmithxyz** [comment]
It might be obvious, but there is no refresh i3 button in dwm.

Super+F2 opens up a tutorial videos list in dwm.

If you're in i3, you were always in i3.

**Comment by satiankit** [comment]
Yeah, my bad it automatically switched to i3 after restart. I solved it just now. It was because of  lightdm settings.
