### ISSUE TITLE
HiDPI

### ISSUE THREAD

**Issue by siddbudd** [LukeSmithxyz/LARBS#239]
Could you please give me some tips how to fix LARBS for a 4K 15 inch (HiDPI) screen? I tried 
Xft.dpi: 192 in ~/.Xresources but it did not do much, I think only dmenu got larger and nothing else. E.g. the default font in st is still incredibly small and I need to manually increase in every instance. Is there a best way to increase dpi for all applications?

**Comment by discapes** [comment]
@siddbudd edit .config/Xresources, and change this line: *.font: monospace:size=16

**Comment by LEsV1** [comment]
Did anyone manage to get scaling to work properly on HiDPI?

**Comment by chdrsto** [comment]
You can increase the font size for ST in .local/src/st/.config and build it again.
It worked for me by setting *font size=19 and *font[2] size=15

but this will just increase ST

**Comment by quickstar** [comment]
I cannot get this to work ether, @LukeSmithxyz any suggestion how to tackle this accordingly?

**Comment by decantr** [comment]
Personally, I think got it pretty close using a rube goldberg level of config
 editing. 

Standard

I do also set the Xresources option mentioned above as well as changing the font
 sizes compiled in the dependencies on a per machine basis on setup/update.

Make sure you uncomment the `xrdb` line in your `.xprofile` though!

Docking

By changing `xrandr`s `--dpi` option and setting the `GDK_SCALE` I have a
 acceptable laptop dock solution, though it requires _renewing_ dwm and
 reopening running programs.

You could view the steps I use [here](https://github.com/decantr/dotfiles/blob/master/bin/displayset).

**Comment by m0rtis0** [comment]
I think this is related to #291 in general. This lets you change all font sizes on the system, but @decantr 's response is also correct, if you want to use xrandr

**Comment by delightfuldude** [comment]
I'm on a fresh Arch and LARBS install, but this isn't usable on 4k monitors. I managed to increase the font for the statusbar an dmenu, but the fonts and icons in programs like firefox, thunderbird, audacious etc. are ridiculous small.
Isn't there a simple solution to use this on actual hidpi hardware?

**Comment by delightfuldude** [comment]
OK, I figured it out. This works:

```
- vim .config/x11/xresources
  - *.font: monospace:size=16
  - add (Line 7):
Xft.dpi: 134

- cd .local/src/dwm/
- vim config.h
  - Line 18:
static char *fonts[]          = { "monospace:size=16", "JoyPixels:pixelsize=16:antialias=true:autohint=true"  };
- sudo make install

```

**Comment by hadesagd** [comment]
The ArchWiki has a very good article on HiDPI here. [ArchWiki HiDPI](https://wiki.archlinux.org/index.php/HiDPI). What worked for me was setting the gtk and qt environment variables for each kit, and bumping up the font sizes for text based apps st, dmenu, etc.
