### ISSUE TITLE
vim configuration: file missing

### ISSUE THREAD

**Issue by gabriel-doriath-dohler** [LukeSmithxyz/LARBS#24]
After the install this file was missing:
https://github.com/LukeSmithxyz/voidrice/blob/master/.vim/luke/prose.vim
It's not a big issue but vim wasn't working properly.
Anyway, thank you for your videos, you got me into archlinux, i3wm and linux in general.
Sorry for my bad english.

**Comment by Daenarii** [comment]
This should be solved by https://github.com/LukeSmithxyz/voidrice/commit/80bbc0a036ca857e4b20a1ded7336a9ee5628545
Just add the new file to your corresponding local directory and it should fix the problem.
