### ISSUE TITLE
larbs.sh installs i3 instead of dwm

### ISSUE THREAD

**Issue by mmahmoudian** [LukeSmithxyz/LARBS#240]
I wanted to give dwm a try and larbs sounded easy and straight forward to get into suckless.
1. I created a virtual machine with QEMU and installed a fresh Manjaro GNOME on it (didn't want to go through arch setup for this test).
2. I download the larbs as it was mentioned on the README via `curl -LO` and 
3. ran `sudo sh larbs.sh`.
4. asked the script to create a new user for it as I didn't want any left-over dotfiles to intervene with the dwm experience.

Everything went smooth and selected dwm (first item in the list) but then half way through the installation I realized it is installing i3blocks! I didn't interrupt and let it finish, then logged out of gnome and from the bottom right corner I tried to select dwm, but all I got was GNOME and i3. I even logged in with i3 to confirm if it is really i3 and it was.

I went back to the GNOME user and ran the larbs again and this time I double-checked that the dwm option is selected. I also asked the script to create a new user again. After a quick run (everything was already installed once so things went quickly), I tried to log in and the only options were again GNOME and i3.

I read the larbs to see if there is any bug that I can quickly spot and fix, but found nothing.

![image](https://user-images.githubusercontent.com/390889/83335707-3deeda80-a2b7-11ea-99c1-d05d03aa3946.png)

**Comment by tallguyjenks** [comment]
if you look in [progs.csv](https://github.com/LukeSmithxyz/LARBS/blob/master/progs.csv) they're both installed but one one of the two will be activated by user choice. but all the dependencies for both are installed by LARBS

**Comment by mmahmoudian** [comment]
@tallguyjenks thank you for the reply, but as I explained I don't see the dwm in the DE list. how can I "activate" dwm and "deactivate" i3?

**Comment by LukeSmithxyz** [comment]
LARBS is not intended to be run with a display manager.

I suppose I should just go ahead and add a desktop file though since people running this on Manjaro keep asking this.

**Comment by bybv** [comment]
@LukeSmithxyz  Did you end up getting to this? I have found that I had to disable gdm or whatever else to get to a terminal prompt at reboot, and can not select LARBS in any drop-down. Thanks!
