### ISSUE TITLE
larbs.sh broken in last commit

### ISSUE THREAD

**Issue by BachoSeven** [LukeSmithxyz/LARBS#244]
After last commit on the file, I get ` larbs.sh: line 260: syntax error: unexpected end of file`, with the file from 5 days ago it runs fine.

**Comment by LukeSmithxyz** [comment]
I've reverted it.

**Comment by bartelemii** [comment]
Looks like the changes are already reverted, but what worked for me was just adding a semicolon at the end of both new functions.
