### ISSUE TITLE
Can't install libxft-bgra on fresh install of LARBS

### ISSUE THREAD

**Issue by SynysterGates23** [LukeSmithxyz/LARBS#245]
I just reinstalled Artix on my laptop and installed LARBS, but I cannot use the system because libxft-bgra will not install.
Edit: I also tried installing libxft-bgra-git, but that doesn't work either.

**Comment by wi-gett** [comment]
I am getting the same thing. The AUR libxft-bgra page has the package flagged out of date and the libxft-bgra-git gets an error with xorg-macros which I can't seem to find. Unless someone knows a work around we may have to wait until they fix the packages.

**Comment by Ruborcalor** [comment]
I had the same problem but was able to work around using a comment in the aur page.

> I get an error from git about the referenced commit being an "unadvertised object" when it runs the fetch.
> Worked around it by grabbing the diff via http instead: curl https://gitlab.freedesktop.org/xorg/lib/libxft/-/commit/${COMMIT_ID}.diff | patch -p1

The idea is to edit the PKGBUILD. Here are images of the before and after that worked for me.

Before:
![image](https://user-images.githubusercontent.com/47014480/83703783-68ee6c80-a5de-11ea-8ad5-d762db614928.png)
After:
![image](https://user-images.githubusercontent.com/47014480/83703823-83284a80-a5de-11ea-9f37-6a61eef6d391.png)

**Comment by SynysterGates23** [comment]
Thank you! I'll try it out now.

**Comment by alphalinux1** [comment]
I'm getting the same error when trying to install libxft-bgra. I've tried the recommended fixes, but nothing seems to be working. Without it, when I input startx, it shows the background briefly, and terminates back to command line.

**Comment by SynysterGates23** [comment]
Yeah the same thing is happening to me.

**Comment by Ruborcalor** [comment]
What error are you getting? If you comment out the `git fetch` line you shouldn't be getting the "unadvertised object" error.

**Comment by alphalinux1** [comment]
I don't know what changed, but it worked! I ran it 7 or 8 times earlier, and always encountered a failure; it pushed through this time for some reason. Thank you @Ruborcalor  for your help.
