### ISSUE TITLE
Emoji Not loaded Correctly in Staus Bar 

### ISSUE THREAD

**Issue by utkarsh190601** [LukeSmithxyz/LARBS#248]
![pic-full-200605-0740-29](https://user-images.githubusercontent.com/56307408/83829667-05a92b00-a701-11ea-9346-f5f42e10a738.png)

```
[utkarsh@archlinux ~]$ pacman -Qs libxft
local/libxft-bgra 2.3.3.r7.7808631e-1 (modified)
    libXft with BGRA glyph (color emoji) rendering & scaling patches by Maxime Coste
```
Noto Font :
```
[utkarsh@archlinux ~]$ pacman -Qs noto
local/noto-fonts 20190926-4
    Google Noto TTF fonts
local/noto-fonts-emoji 20191016-6
    Google Noto emoji fonts
local/python-monotonic 1.5-4
    An implementation of time.monotonic() for Python 2.
```

**Comment by LukeSmithxyz** [comment]
What exactly is supposed to be wrong here?

**Comment by utkarsh190601** [comment]
Sorry , there was a problem with noto-fonts package which was causing unequal scaling of emoji's .

**Comment by StoicIndividual** [comment]
> Sorry , there was a problem with noto-fonts package which was causing unequal scaling of emoji's .

I seem to have this exact issue, how exactly did you fix it?

**Comment by utkarsh181** [comment]
StoicIndividual <notifications@github.com> writes:

>> Sorry , there was a problem with noto-fonts package which was causing unequal scaling of emoji's .
>
> I seem to have this exact issue, how exactly did you fix it?

Currently I don't have DWM running so I cannot verify the solution but
here it is:

Remove noto-fonts and ensure you have noto-fonts-emoji installed.  Also
note that these package names are written with Arch Linux in mind.

Here is the snippet on my DWM config which deals with typeface:

static char* fonts[]                = { "monospace:size=10",
	"JoyPixels:pixelsize=10:antialias=true:autohint=true" };
-- 
Utkarsh Singh

**Comment by StoicIndividual** [comment]
> StoicIndividual <notifications@github.com> writes:
> > Sorry , there was a problem with noto-fonts package which was causing unequal scaling of emoji's . I seem to have this exact issue, how exactly did you fix it?
> Currently I don't have DWM running so I cannot verify the solution but here it is: Remove noto-fonts and ensure you have noto-fonts-emoji installed. Also note that these package names are written with Arch Linux in mind. Here is the snippet on my DWM config which deals with typeface: static char* fonts[] = { "monospace:size=10", "JoyPixels:pixelsize=10:antialias=true:autohint=true" }; -- Utkarsh Singh

I tried removing the noto-fonts package, but apparently, it was a dependency of brave and failed.
So I installed the ttf-liberation font (the alternate mono font specified in the fonts.conf) and changed the font snippet in the dwm config to:
`static char *fonts[] = {"Liberation Mono:size=10", "JoyPixels:pixelsize=10:antialias=true:autohint=true"}`
and that seemed to have fixed the alignment issue, thanks for the help.

**Comment by utkarsh181** [comment]
StoicIndividual <notifications@github.com> writes:

> I tried removing the noto-fonts package, but apparently, it was a dependency of brave and failed.

$ yay -Si brave-bin
:: Querying AUR...
Repository      : aur
Name            : brave-bin
Version         : 1:1.21.74-1
Depends On      : gtk3  nss  alsa-lib  libxss  ttf-font

I don't think brave browser depends on noto-fonts.  Which OS are you
using?
-- 
Utkarsh Singh
