### ISSUE TITLE
Fonts turned to serif in all programs

### ISSUE THREAD

**Issue by gtlsgamr** [LukeSmithxyz/LARBS#253]
As the title says, the fonts in firefox, brave, android studio, all have turned to serif, while they used to be sans before I ran the script. The fontconfig in ~/.config only has options to set the preferred font families. I was wondering if there's a way to change the default font throughout the system for GUI apps.

**Comment by LukeSmithxyz** [comment]
I assume you're running some preinstalled/configured distro? What is it?
You can comment out any lines in the font config you want and see if
that fixes it.
On 20/06/11 07:35AM, Hitarth Thummar wrote:
> As the title says, the fonts in firefox, brave, android studio, all have turned to serif, while they used to be sans before I ran the script. The fontconfig in ~/.config only has options to set the preferred font families. I was wondering if there's a way to change the default font throughout the system for GUI apps.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/LARBS/issues/253

--
https://lukesmith.xyz

**Comment by gtlsgamr** [comment]
No I use Arch, nothing pre-configured. I will try to do what you said and get back to you! Thanks!

**Comment by Roshak** [comment]
it's the same here, i'm running a clean artix install and i've commented out all the lines referring to serif fonts in fonts.conf, but still brave and other gui applications are showing with serif fonts.

**Comment by gtlsgamr** [comment]
@LukeSmithxyz I tried doing that like roshak here, but that didn't seem to work as well. But by now I'm used to the serifs so I'm not even sure I want to do it anymore.

**Comment by negativeExponent** [comment]
on a clean-arch install without any other fonts and just using LARBS, web browsers (im on firefox atm) will use the libertine font that larbs installed even when fontconfig is not used. installing another font, like liberation will override them without changing any config.

for the GUI, the default font is Sans 10, which just points to Libertine fonts or whatever is available (you can use **fc-match** to see). if you dont want to use lxappearance or similar themer, it should probably work by changing font settings in ~/.config/gtk-2.0 and gtk-3.0.

i has a similar issue before with monospace fonts being very thin: https://github.com/LukeSmithxyz/voidrice/issues/729
(the Monospace font was just Nimbus L in arch clean install)
