### ISSUE TITLE
Error when logging in as user

### ISSUE THREAD

**Issue by rescenic** [LukeSmithxyz/LARBS#254]
How to add custom monitor after installing LARBS? I use 1366x768 monitor.
![larbs](https://i.ibb.co/Jns5ts9/15-06-2020-829-04-58-56.png)
Error after typing startx:
![nomonitor](https://i.ibb.co/QdmVnNH/15-06-2020-833-05-37-22.png)
Log:
![log1](https://i.ibb.co/4YfHWTg/15-06-2020-830-05-33-21.png)
![log2](https://i.ibb.co/zPYN7RY/15-06-2020-831-05-33-35.png)
Help me, thanks.

**Comment by vladdoster** [comment]
I don't think this is a problem of larbs. It looks like (correct me if I'm wrong) you are running it with in a VM. You probably need to setup a virtual display of some sort. I can't quite tell what program that is since I run virtual box on arch, but if you aren't using virtual box, I suggest giving it a try.

**Comment by vladdoster** [comment]
I'd give these commands a shot. 

As root:
```
pacman -R nvidia nvidia-libgl lib32-nvidia-libgl
pacman -S xf86-video-fbdev
reboot
```

If you are using virtual box, did you install the modules?
```
sudo pacman -S virtualbox-guest-utils virtualbox-guest-modules-arch
```

**Comment by vladdoster** [comment]
A total non-sequiter, but I am working on an arch installer to fix these problems. Mind if I comment on this issue once it is finished? It will allow you to  use grub2 or bootctl, choose partition sizes, install dotfiles, ask if running in VM and fix these issues, and a few other features. I would love more beta testers. Only so much dog food I can eat.

**Comment by vladdoster** [comment]
The shell version works in virtual box, but I think I worked it for time being. I'm currently rewriting it in python. 

The python version will also be able to create an iso that has all dependencies loaded on so you won't need internet (you'll have to set timezone from a list rather than it being auto detected). Id say it should be done in a week or so.

**Comment by rescenic** [comment]
Wow, thank you so much for detailed explanations. Love it.
I saw the instructions in Hyper-V wiki: https://wiki.archlinux.org/index.php/Hyper-V
I used systemd-boot, so it works when adding options video:
Before that, I installed xf86-video-fbdev.
```
nano /boot/loader/entries/arch.conf
----------------------------------------
title Arch Linux
linux /vmlinuz-linux
initrd /initramfs-linux.img
options video=hyperv_fb:1366x768 root=PARTUUID=xxxx-xxxx rw
```
![works](https://i.ibb.co/6Z5NzLp/15-06-2020-834-15-51-58.png)

**Comment by rescenic** [comment]
@vladdoster Can you guide me how to show the weather icon in status bar. I middle-clicked the icon, and it's gone from statusbar? Thank you very much.

**Comment by rescenic** [comment]
I can't use VirtualBox at the moment, because I need Hyper-V for Linux WSL2 in Windows 10. But VMware works side by side with Hyper-V now.
I am interested with tiling window manager. I hope I can learn fast to catch up.

**Comment by vladdoster** [comment]
Mhm... I'm not too sure about the weather block. I personally don't use it in DWM.

**Comment by rescenic** [comment]
> A total non-sequiter, but I am working on an arch installer to fix these problems. Mind if I comment on this issue once it is finished? Using dialog, It will allow you to use grub2 or bootctl, choose partition sizes, install dotfiles, ask if running in VM and fix these issues, and a few other features. I would love more beta testers. Only so much dog food I can eat.
> 
> Here is a screencast of what it roughly looks like:
> 
> Select `arch-installer-demo.mp4` at [files.vdoster.com](http://files.vdoster.com)
> 
> https://github.com/vladdoster/system-bootstrap
> 
> The shell version works in virtual box, but I think I borked it for time being. I'm currently rewriting it in python.
> 
> The python version will also be able to create an iso that has all dependencies loaded on so you won't need internet (you'll have to set timezone from a list rather than it being auto detected). Id say it should be done in a week or so.
> 
> If you happen to have any feature requests that you would want to use it in the future, feel free to open an issue and I will add it.

I'll try in another machine which has VirtualBox on it. Thank you for your hard work.
