### ISSUE TITLE
LARBS issue with Artix

### ISSUE THREAD

**Issue by kcallis** [LukeSmithxyz/LARBS#257]
I decided to try my hand with Artix after watching @LukeSmithxyz  latest video. After installing Artix, I attempted to install LARBS, but regardless of the fact that I am running in the root account, this script will not execute. I am going to guess that LARBS is not going to play nicely since I was looking at the script and there was mention of the AUR.

**Comment by LukeSmithxyz** [comment]
LARBS has worked perfectly with Artix for months. In fact, I ran it on
the computer I installed Artix on right after that video. Something else
must be amiss.
On 20/06/27 06:53AM, K.C. Callis wrote:
> I decided to try my hand with Artix after watching @LukeSmithxyz  latest video. After installing Artix, I attempted to install LARBS, but regardless of the fact that I am running in the root account, this script will not execute. I am going to guess that LARBS is not going to play nicely since I was looking at the script and there was mention of the AUR.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/LARBS/issues/257

--
https://lukesmith.xyz

**Comment by drake-newell** [comment]
Update your pacman keyrings.

**Comment by BBDDAlex** [comment]
Hey, I had the same issue. You have to update Artix before using the script. Just run "sudo pacman -Syyuu" and try running the script again as root.

**Comment by kcallis** [comment]
I was trying to install artix wirelessly and after falling to get the base running, I thought I would cheat using  the run it-mate build. After installing LARBS, I could not get to the GUI login screen.

I have installed with the base again and now I am installing LARBS currently. What do I need to activate so that I can bring up the GUI login and be able to start dwm desktop. I know there is some gotcha before I am finished.

**Comment by drake-newell** [comment]
@kcallis there is no gui login by default. Just log in at tty1 and startx will automatically run.

**Comment by kcallis** [comment]
> @kcallis there is no gui login by default. Just log in at tty1 and startx will automatically run.

Thanks.... My life is now complete!!!
