### ISSUE TITLE
sxhkd will not update to a new keybinding

### ISSUE THREAD

**Issue by sbkucin** [LukeSmithxyz/LARBS#259]
Any change I try to make to the sxhkd config file doesn't work.  For example, changing super mod+r to open ranger instead of lf, even after change the $FILE to ranger (in .profile), didn't work.  Then I added it without the env variable (st -e ranger) still didn't work.  I know writing the file automatically updates the config file, but still nothing.  Not sure what I am doing wrong.  Using Manjaro if that matters.

**Comment by drake-newell** [comment]
Are you using DWM? Sxhkd is deprecated in LARBS now

**Comment by sbkucin** [comment]
Yes I am using DWM, what would you recommend doing?

**Comment by drake-newell** [comment]
@sbkucin Bindings in DWM are no longer managed by sxhkd. They are in the config.h of the DWM source code that can be found at ~/.local/src/dwm. After changing them, while in the dwm folder run "make && sudo make install" and restart dwm.

**Comment by sbkucin** [comment]
@drake-newell , thank you, that worked perfectly.
