### ISSUE TITLE
Shouldn't dunst be installed by default?

### ISSUE THREAD

**Issue by CecileGS** [LukeSmithxyz/LARBS#26]
It's by no means a _required_ dependency since all of the LARBS programs/scripts run fine without it. However, the LARBS greeting message definitely doesn't work as intended - it only works on my Arch Linux after I install dunst. Discord also crashes upon receiving a push notification, since there is no system notification daemon to which it can pipe its output.

**Comment by LukeSmithxyz** [comment]
Strange, I could've sworn this was in the programs list... I suppose I just forgot to add it, either way, it's a requirement now.

**Comment by CecileGS** [comment]
Better now than never. Thanks Luke!
