### ISSUE TITLE
Installing new programs doesn't reflect in Mod + D

### ISSUE THREAD

**Issue by BBDDAlex** [LukeSmithxyz/LARBS#262]
Hey, I just installed LARBS on my arch install today, and everything was working fine. When I installed Brave Nightly and Firefox Nightly, the programs didn't appear in Mod + D.

**Comment by LukeSmithxyz** [comment]
The run command will offer whatever is in your `$PATH`. I don't know anything about how you installed these programs, but they must not've placed their binaries in your `PATH`. Add them and they will show up.
