### ISSUE TITLE
Change keyboard language 

### ISSUE THREAD

**Issue by V1leDev** [LukeSmithxyz/LARBS#263]
So I set up LARBS on my artix machine and after logging in the keyboard language switches to american, normally I have German. I have KEYMAP=de-latin1 in my /etc/vconsole.conf but it seams to be overridden after I login. The login prompt still uses the German layout, after that the american is used. I probably failed to change something in a config file...

**Comment by kocotian** [comment]
@V1leDev are you solved this problem? if yes, can you say how you solved? i have the same problem too :<

**Comment by V1leDev** [comment]
Yes, so I've tried a lot of things by changing some config files for locale etc. but nothing worked. Then in my case I put the 
 following command into .xprofile (at the very end):
setxkbmap -layout de 
That worked. Now every time at login this command is executed and my keyboard layout is set to German.

**Comment by V1leDev** [comment]
> @V1leDev are you solved this problem? if yes, can you say how you solved? i have the same problem too :<

Yes, so I've tried a lot of things by changing some config files for locale etc. but nothing worked. Then in my case I put the
following command into .xprofile (at the very end):
setxkbmap -layout de
That worked. Now every time at login this command is executed and my keyboard layout is set to German.

**Comment by et-8** [comment]
I had this problem myself when just started out with LARBS.
@LukeSmithxyz maybe these instructions would be good to have in the LARBS guide?

_The reason is that Xorg  overwrite the vconsole.conf variable._
Another method than @V1leDev  is to create a **00-keyboard.conf** file in `/etc/X11/xorg.conf.d` with these settings.
Xorg reads the files in `/etc/X11/xorg.conf.d` in order with the lowest number first.

```
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "de"
        Option "XkbModel" "pc105"
EndSection
```
More information is in the Arch wiki:
https://wiki.archlinux.org/index.php/Xorg/Keyboard_configuration
