### ISSUE TITLE
Can't open anything in Manjaro

### ISSUE THREAD

**Issue by mynamedoge** [LukeSmithxyz/LARBS#264]
I was piggybacking in another closed thread but I suppose a new one is warranted

I just installed Manjaro/KDE and put LARBS over it
The LARBS interface has about 10% or so of the programs functional. The prominent non functional ones include the terminal, the file manager, and the network settings. Dmenu is also finicky, only scrolling works. I can't type in keywords. I can't connect to the internet. I've wiped the partition clean and Installed Manjaro twice with the same effect once LARBS is added. I've tried adding wmctrl with no effect.

The KDE environment also refuses to open anything once LARBS is added. Even as simple as system settings don't show up. The screen starts glitching hard in the center.

What might be going wrong?

**Comment by videla98** [comment]
You should try installing it over a clean Manjaro install, without a desktop environment. You can use Manjaro Arquitecht and install CLI system for that.

**Comment by negativeExponent** [comment]
you can probably create a new user if you don't mind. Larbs is able to let you create a user at he beginning. You may probably need to rename /etc/skel so the new user can use larbs config instead of their own one.
