### ISSUE TITLE
No Image Preview in Ranger

### ISSUE THREAD

**Issue by DeepGorilla22** [LukeSmithxyz/LARBS#265]
Preview images in ranger don't show up after "loading..." and sometimes show up as "binary".

```
Terminal: st 0.8.2
Ranger: ranger-git 1.9.3
ueberzug: python-ueberzug-git 18.1.5
```

rc.conf
`set preview_images true`
`set preview_images_method ueberzug`

I'm pretty new to arch so I'm pretty confused. Read around and installed all of ueberzug's dependencies then eventually just installed the aur git version but images still dont show up.

Also is this a typo in line 122 of rc.config
`map "<any>  tag_toggle tag=%any`
Everything is red after the double quote till the end of the file

Help a zoomer out!

**Comment by DeepGorilla22** [comment]
Wanted to sweep this under the rug because of my obvious mistake.
MOD + r - brings up lf (I though it brought up ranger)
remapped and the issue was solved

zoomer moment

**Comment by mateusgomes01** [comment]
@DeepGorilla22 Does lf have image preview already? If so mine doesn`t work. Can I change something in the lfrc file to make it work?
