### ISSUE TITLE
Opening Programs

### ISSUE THREAD

**Issue by HistoricGlint** [LukeSmithxyz/LARBS#268]
This is more of a question then an issue, but I was wondering if there was a way to search for, and open programs on larbs.

**Comment by DeepGorilla22** [comment]
You could use dmenu (MOD+d) to search for programs or run commands.

**Comment by Ri-go** [comment]
You could use dmenu (MOD+d) to search for programs or run commands.
I implore you too read the tutorial (MOD+f1) for the full list of shortcuts for opening programs.
