### ISSUE TITLE
Bad usage of $(whoami) - expanding to root instead of $USER

### ISSUE THREAD

**Issue by CecileGS** [LukeSmithxyz/LARBS#27]
My Ranger shortcut "nouns" didn't work properly after a fresh LARBS install, until I cloned the shortcut_sync repo and ran the script manually and then they started working again. The muttwizard doesn't appear in my home directory, either. LARBS requires you to run with root privilege so naturally it looks for `/home/root/` but can't find it.

Examples:
https://github.com/LukeSmithxyz/LARBS/blob/9314088923af251cc0396d064e38a8cd4899c4b5/src/larbs_user.sh#L49
https://github.com/LukeSmithxyz/LARBS/blob/9314088923af251cc0396d064e38a8cd4899c4b5/src/larbs_user.sh#L56

**Comment by CecileGS** [comment]
Oh, actually never mind this issue... I didn't read the code closely enough and after confirmation with my own testing the `sudo -u $name bash /tmp/larbs_user.sh` actually does make it expand to `/home/cecile/`

I was wrong and now the title is a false premise lol. I still have to manually clone the muttwizard and shortcut_sync repos and run them manually, though...

**Comment by CecileGS** [comment]
Apologies @LukeSmithxyz , I have been and currently am without reliable access to the internet for reasons due to personal life circumstances. It's going to be a long time before I can get back on my feet.

Yes I can confirm that my former dev machine had problems with both of them every time I did a fresh LARBS install - unfortunately I no longer have access to said machine and it's impossible for me to retrieve it. The way you write makes me think that this issue doesn't happen to you - it did for me so now I'm leaning towards "this is probably a hardware problem" rather than "this is probably a problem with LARBS". When I have the means to and time I'll update you with info on how to reproduce this bug though.

Shortcut sync: there is no `bash_shortcuts` in the `$HOME` directory
Mutt wizard: iirc the `~/.config/mutt/` wasn't empty and had the usual files in it, except for the weirdly missing `mutt-wizard.sh` script

**Comment by LukeSmithxyz** [comment]
That's very strange, but I can't imagine how it would be a hardware problem, thus making it all the more mysterious.

Honestly I think the most plausible answer is that Github had spotty connection when you were running the script. When `git` doesn't get a response in time, it has a tendency to just give up quickly, and that could've been what happened when it was cloning the `shortcut-sync`and `mutt-wizard` repos... maybe. Either way, I think I need to add some error-handling to that area to better diagnose what's going on in issues like these.

**Comment by CecileGS** [comment]
Yeah, your guess is more plausible than mine. Perhaps you can purchase a fallback VPS service for the purpose of mirroring the git repos? I have had a very good experience with DigitalOcean in the past, although you will definitely need some security sysadmin know-how because people will be trying to hack into your server.
