### ISSUE TITLE
libxft-bgra won't install

### ISSUE THREAD

**Issue by johnlrussell** [LukeSmithxyz/LARBS#270]
Installed on a computer last week, but decided to install on my laptop today and I'm getting an error when trying to install libxft-bgra using yay. Everything goes fine until it tries to import the PGP key. 

==> PGP keys need importing:
 -> 4A193C06D35E7C670FA4EF0BA2FB9E081F2D130E, required by: libxft-bgra
==> Import? [Y/n] 
:: Importing keys with gpg...
gpg: keyserver receive failed: General error
problem importing keys

One thing that I notice is that the package has been marked as out of date in the AUR - would this cause the error? I've tried manually importing the key and I get the same error.

**Comment by amnletta** [comment]
I had the same issue when trying to install LARBS.

**Comment by Ri-go** [comment]
Ran into the same problem. What I did was to clone libxft-bgra-git then makepkg.
If for some reason you run into another keyserver problem using the above method. You could manually recieve the key by doing `gpg --keyserver serverurl:port --recv-keys KeyID`

**Comment by themaster567** [comment]
> Ran into the same problem. What I did was to clone libxft-bgra-git then makepkg.
> If for some reason you run into another keyserver problem using the above method. You could manually recieve the key by doing `gpg --keyserver serverurl:port --recv-keys KeyID`

Having the exact dame issue as OP and I have no idea how to do either of those things. Most of the things you put in your command are placeholders and I don't know what the server url or port is.

**Comment by amnletta** [comment]
[Maybe this will help?](https://github.com/LukeSmithxyz/LARBS/issues/179)

**Comment by johnlrussell** [comment]
I was able to get it working by adding the following to ~/.gpupg/gpg.conf

keyserver hkp://ipv4.pool.sks-keyservers.net:11371

Originally, I didn't have the .conf file, and there wasn't one in skel, so I just copied the one from the pacman.d directory and edited that one.

**Comment by 666-demonkiller** [comment]
Guys I am also facing this issue. I am trying this on an arch install in virtualbox. Is this why is it happening or you guys have this error in physical arch install?

**Comment by cafougnette-1** [comment]
Just check the AUR page - in the comments there's this fix that worked for me : 

gpg --keyserver "hkp://ipv4.pool.sks-keyservers.net:11371" --recv-keys 4A193C06D35E7C670FA4EF0BA2FB9E081F2D130E
