### ISSUE TITLE
Shifting in hotkeys doesn't work

### ISSUE THREAD

**Issue by imnotadam** [LukeSmithxyz/LARBS#271]
I was trying to decrease gaps with Mod+Shift+z but it wouldn't work, but Mod+z worked fine to increase them. Any help please?

**Comment by themaster567** [comment]
Because that's not the command. Mod + z widens the gaps and Mod + x shrinks them.

**Comment by imnotadam** [comment]
Oh, it said that in the read me so I guess it's outdated then
