### ISSUE TITLE
dwm closes after turning on

### ISSUE THREAD

**Issue by 666-demonkiller** [LukeSmithxyz/LARBS#272]
Luke, at tty, I am prompted to install a package called libxfta-bgra. When I am trying to install it, I get this error
gpg: keyserver receive failed: General error
==> Error: Problem importing keys
When I type startx without installing the mentioned package, the WM starts, but then closes abruptly. Any workarounds or solutions here.?

BTW, I don't know if this matters, but I should tell that I am trying larbs in an Arch Install in VirtualBox. Even though I have physical Arch Installs, I just wanted to try larbs and the whole dwm thing in virtualbox before actually implementing it on my machine physically.

**Comment by themaster567** [comment]
https://github.com/LukeSmithxyz/LARBS/issues/270#issuecomment-662564132

**Comment by zengtianli** [comment]
gpg --keyserver "hkp://ipv4.pool.sks-keyservers.net:11371" --recv-keys 4A193C06D35E7C670FA4EF0BA2FB9E081F2D130E
then yay -S libxfta-bgra

it works for me

source from 
https://aur.archlinux.org/packages/libxft-bgra/
