### ISSUE TITLE
weather script issue

### ISSUE THREAD

**Issue by mohamadali-halwani** [LukeSmithxyz/LARBS#273]
![image](https://user-images.githubusercontent.com/68155980/89128244-9b401b80-d4f4-11ea-9733-970efe978642.png)
****

"spawn telnet rainmaker.wunderground.com 3000"
I reviewed the scripts in `.local/bin/statusbar/` and I couldn't find the script causing this behaviour
but I can say that weather script isn't working, also the file `.config/i3blocks/config` doesn't seem to work whether i comment out lines or not.

any ideas on how to fix this ?
Thanks in advance

**Comment by chdrsto** [comment]
Same issue here, but I guess it is related to dwm and not i3. This is the reason why changing i3blocks will not have any effect.

**Comment by mohamadali-halwani** [comment]
> Same issue here, but I guess it is related to dwm and not i3. This is the reason why changing i3blocks will not have any effect.

Thanks for pointing that out for me, since I used to use i3, and reused larbs to put dwm instead, I still have the packages related to i3, that's how I mixed things up, in addition to the `cfb`alias located in `.config/shortcutrc` that takes me right to `i3blocks` config which wasn't deleted when I reinstalled dwm(due to git's way of dealing with files i think).
.
I still see i3blocks in [voidrice .config/](https://github.com/LukeSmithxyz/voidrice/tree/master/.config) even though the package list in [progs.csv](https://github.com/LukeSmithxyz/LARBS/blob/master/progs.csv) states that `dwmblocks` will be installed instead, but larbs didn't get the config.h file in `.config/`, instead I found it in `.local/./src/dwmblocks/`.

So here we are, first step on diagnosing the issue.
I apologize in advance if my question is too simple to even ask, pardon me I'm a newbie to this.

**Comment by mohamadali-halwani** [comment]
UPDATE:
After modifying `config.h` and recompiling it, it turns out that **this specific problem is a result of the `weather` script.**
I checked to see if the weather script on my machine is identical to that on [voidrice weather script](https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/statusbar/weather) and they're identical.

that's how my `dwmblocks` looks like after commenting out the `weather` script
![dwmblocks](https://user-images.githubusercontent.com/68155980/89210209-fbe85a80-d5bf-11ea-8e93-92587c998729.png)

so, is there something wrong with the script itself or it's just something that I'm unable to see due to my lack of experience in scripting?
any help is appreciated, I'll edit the title for accuracy.

**Comment by mohamadali-halwani** [comment]
I tried running `weather`in my command line, here's the output : 
`[thedeathlord@ArcherMarcher ~]$ weather 
spawn telnet rainmaker.wunderground.com 3000 
Trying 35.160.169.47... 
Connected to rainmaker.wunderground.com. 
Escape character is '^]'. 
------------------------------------------------------------------------------ 
*               Welcome to THE WEATHER UNDERGROUND telnet service!            * 
------------------------------------------------------------------------------ 
*                                                                            * 
*   National Weather Service information provided by Alden Electronics, Inc. * 
*    and updated each minute as reports come in over our data feed.          * 
*                                                                            * 
*   **Note: If you cannot get past this opening screen, you must use a       * 
*   different version of the "telnet" program--some of the ones for IBM      * 
*   compatible PC's have a bug that prevents proper connection.              * 
*                                                                            * 
*           comments: jmasters@wunderground.com                              * 
------------------------------------------------------------------------------ 
Press Return to continue: 
Press Return for menu 
or enter 3 letter forecast city code-- 
                 WEATHER UNDERGROUND MAIN MENU 
                ****************************** 
                 1) U.S. forecasts and climate data 
                 2) Canadian forecasts 
                 3) Current weather observations 
                 4) Ski conditions 
                 5) Long-range forecasts 
                 6) Latest earthquake reports 
                 7) Severe weather 
                 8) Hurricane advisories 
                 9) Weather summary for the past month 
                10) International data 
                11) Marine forecasts and observations 
                12) Ultraviolet light forecast 
                 X) Exit program 
                 C) Change scrolling to screen 
                 H) Help and information for new users 
                 ?) Answers to all your questions 
                   Selection:C 
                OPTION TO CHANGE SCROLLING TO SCREEN 
                Select the number of lines printed to screen at one time: 
                --------------------------------------------------------- 
                1) 24 lines (default) 
                2) 48 lines 
                3) 60 lines 
                4) Unlimited 
                5) 12 lines 
                   Selection:4 
                 WEATHER UNDERGROUND MAIN MENU 
                ****************************** 
                 1) U.S. forecasts and climate data 
                 2) Canadian forecasts 
                 3) Current weather observations 
                 4) Ski conditions 
                 5) Long-range forecasts 
                 6) Latest earthquake reports 
                 7) Severe weather 
                 8) Hurricane advisories 
                 9) Weather summary for the past month 
                10) International data 
                11) Marine forecasts and observations 
                12) Ultraviolet light forecast 
                 X) Exit program 
                 C) Change scrolling to screen 
                 H) Help and information for new users 
                 ?) Answers to all your questions 
                   Selection:1 
                         CITY FORECAST MENU 
                --------------------------------------------------- 
                1) Print forecast for selected city 
                2) Print climatic data for selected city 
                3) Display 3-letter city codes for a selected state 
                4) Display all 2-letter state codes 
                M) Return to main menu 
                X) Exit program 
                ?) Help 
                   Selection:1 
          Enter 3-letter city code: WBC 
**Weather Conditions at 06:52 PM EDT on 17 May 2020 for Washington, DC.** 
Temp(F)    Humidity(%)    Wind(mph)    Pressure(in)    Weather 
======================================================================== 
  **67          68%         EAST at 9       30.13      Overcast 
Forecast for Washington, MD 
737 PM EDT sun may 17 2020** 
.Tonight...Mostly cloudy. A slight chance of showers after 
midnight. Patchy fog after midnight. Lows in the mid 50s. East 
winds 5 to 10 mph. Chance of rain 20 percent. 
.Monday...Patchy fog in the morning. Cloudy with a 40 percent 
chance of showers. Highs in the mid 60s. Northeast winds 5 to 
10 mph with gusts up to 20 mph. 
.Monday night...Mostly cloudy. A chance of showers, mainly in the 
evening. Lows in the lower 50s. Northeast winds around 10 mph 
with gusts up to 20 mph. Chance of rain 40 percent. 
.Tuesday...Partly sunny in the morning, then mostly cloudy with a 
chance of showers in the afternoon. Highs in the mid 60s. 
Northeast winds 10 to 15 mph with gusts up to 30 mph. Chance of 
rain 30 percent. 
.Tuesday night...Mostly cloudy with a 40 percent chance of 
showers. Lows in the upper 40s. Northeast winds 10 to 15 mph with 
gusts up to 30 mph. 
.Wednesday...Mostly cloudy with a 50 percent chance of showers. 
Highs around 60. 
.Wednesday night...Mostly cloudy with a 50 percent chance of 
showers. Lows around 50. 
.Thursday...Mostly cloudy with a 50 percent chance of showers. 
Highs in the mid 60s. 
.Thursday night...Showers likely. Lows in the upper 50s. Chance 
of rain 60 percent. 
.Friday...Showers likely. Highs in the lower 70s. Chance of rain 
60 percent. 
.Friday night...Mostly cloudy with a 50 percent chance of 
showers. Lows around 60. 
.Saturday...Partly sunny with a chance of showers. Highs in the 
upper 70s. Chance of rain 50 percent. 
.Saturday night...Partly cloudy. Lows around 60. 
.Sunday...Mostly sunny. Highs in the upper 70s. 
                         CITY FORECAST MENU 
                --------------------------------------------------- 
                1) Print forecast for selected city 
                2) Print climatic data for selected city 
                3) Display 3-letter city codes for a selected state 
                4) Display all 2-letter state codes 
                M) Return to main menu 
                X) Exit program 
                ?) Help 
                   Selection:X 
Connection closed by foreign host. 
`
It says Washington and i definitely don't live there, and ofc it not May 17.

**Conclusions so far : 
1- date detection issues
2- location detection issues
3- Can we relate these issues to the locale ? so the script is not dealing well with the locale ? I'm not sure**

**Comment by mohamadali-halwani** [comment]
The "weird text" that I reported here was the first line of the output 
`spawn telnet rainmaker.wunderground.com 3000
Trying 35.160.169.47...
Connected to rainmaker.wunderground.com.
Escape character is '^]'.`

I tried running `weather` in my command line, the output says that **my location is Washington(I'm definitely not there) and we're in May 17 2020**
**can we conclude that it's a locale issue ?**
Full output of the script :

**Comment by chdrsto** [comment]
The script is expecting a three letter code ... NYC for New York for instance. But I dont know what parameter it is reading

**Comment by mohamadali-halwani** [comment]
Running `curl wttr.in` out puts the normal weather report with no issues

**Comment by delightfuldude** [comment]
Same for me, I get this error message in the statusbar instead of the weather icons:
`spawn telnet rainmaker.wunderground.com 3000`

The weather script works fine when executed manually in the terminal.
Anyone an idea whats going wrong?
