### ISSUE TITLE
dwmblock/startus bar missing !!!

### ISSUE THREAD

**Issue by dlj2019** [LukeSmithxyz/LARBS#274]
For some reason i am not able to increase or decrease screen brightness.
**battery** ( But i cannot control it - " scroll  to change and adjust xbacklight " not working)

![pic-selected-200805-1430-47](https://user-images.githubusercontent.com/30886694/89450423-8350dd80-d728-11ea-9437-c250ca28650c.png)

Also not able to see all status bar : 
[user@arch ~sc/statusbar]$ ls

battery  cpubars  help-icon  kbselect  moonphase  nettraf      popupgrade  volume
clock    crypto   internet   mailbox   mpdup      news         price       weather
cpu      disk     iplocate   memory    music      pacpackages  torrent

Active:
**battery** 
**help-icon**
**volume**
 **weather**
**clock**
**internet** 
**news**  

Non -Active
cpubars    
nettraf  
memory 
cpu 
disk 
popupgrade  
pacpackages

========================
kbselect  moonphase      
crypto     mailbox   mpdup        price      
 iplocate      music        torrent

Do you guys have any idea how to fix this ?

Thanks in advance !

**Comment by themaster567** [comment]
Please read the manual with the windows key + F1. You'll learn what you need to do.

**Comment by dlj2019** [comment]
> Please read the manual with the windows key + F1. You'll learn what you need to do.

I've looked at the menual but i could not figure it out why its not showing and/or functioning ( in case : battery ( But i cannot control it - " scroll to change and adjust xbacklight " not working).

Do you or someone have any thoughts ?
