### ISSUE TITLE
Brave bar scaling

### ISSUE THREAD

**Issue by ierdna-c** [LukeSmithxyz/LARBS#275]
I have a FHD display and brave's bar is too tiny for my eyes. On desktop environments it is better scaled but I have no idea how to do it, searching on the net did not gave much results, any idea?

**Comment by Mar01** [comment]
have a look at https://wiki.archlinux.org/index.php/Xorg#Display_size_and_DPI

**Comment by ierdna-c** [comment]
[facepalm] Arch wiki, as always... 
Thank you
