### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by ethan55335** [LukeSmithxyz/LARBS#276]
Freshly installed Artix on a new laptop, and ran LARBS. I can't seem to get the audio to work. Any ideas? I have the proper output device selected and the volume turned up. I'm not sure where to begin troubleshooting this. I'm not asking for someone to hold my hand but if anyone can point me towards some documentation that might help, I would appreciate it. Thanks.

**Comment by LukeSmithxyz** [comment]
Is this audio from Brave? I think there was an issue on Artix of
Chromium browsers not properly interfacing with pulseaudio on start-up.

If you play some other audio first, like in mpv, it should work though.
I don't think I figured out a permanent fix yet.
On 20/08/18 10:39PM, ethan55335 wrote:
> Freshly installed Artix on a new laptop, and ran LARBS. I can't seem to get the audio to work. Any ideas? I have the proper output device selected and the volume turned up. I'm not sure where to begin troubleshooting this. I'm not asking for someone to hold my hand but if anyone can point me towards some documentation that might help, I would appreciate it. Thanks.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/LARBS/issues/276

--
https://lukesmith.xyz

**Comment by ethan55335** [comment]
Thanks Luke, this fixed it

**Comment by themaster567** [comment]
I know this was closed, but one little solution that would fix this issue would be adding a startup sound when you login.

**Comment by LukeSmithxyz** [comment]
The addition of edde6779d4c6c279cd43e61bec2e9cbc9227d804 will prevent this issue until it is fixed on the upstream.
