### ISSUE TITLE
Keybind for camtoggle script

### ISSUE THREAD

**Issue by Jdevilliersxyz** [LukeSmithxyz/LARBS#278]
It would seem that Mod + C no longer works as intended i.e. it does not run the camtoggle script.  Upon opening dwm's config file (since all the keybinds are neatly sorted, thx Luke!) I noticed the corresponding entry is missing.  Unfortunately my zoomer brain (I'm too young to be a boomer?) doesn't know to make it toggle properly.  I'm guessing it would be in a man page somewhere.  Either way, at least this is here now so you know. 

PS. i3 users wouldn't notice this since it is in the sxhkdrc and should work if you're running the daemon.

**Comment by LukeSmithxyz** [comment]
Yeah it was switched to super+F11 a while back and I forgot to update it.
