### ISSUE TITLE
A new forum would be a good idea

### ISSUE THREAD

**Issue by drake-newell** [LukeSmithxyz/LARBS#279]
This is an issue about issues. Currently, many people open issues in many of Luke's repos with suggestions, guides, or issues unrelated to LARBS or related programs and configs. Of course it is Luke's decision, but I think many would benefit from the creation of a new forum.  I realize that I contradict myself by posting this as an issue, but I feel it further illustrates my point.

**Comment by LukeSmithxyz** [comment]
We'll see. I'll hopefully have my LARBS XMPP service working soon. I might integrate a forum with my LDAP server as well. No promises.
