### ISSUE TITLE
Editing Xresources breaks dmenu and st

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/LARBS#281]
When I edit and save Xresources to change the color scheme, I can't use Mod+Enter to enter st or Mod+d to enter dmenu. That means that I cannot access st, and if I want to go to any other program through dmenu, it doesn't work. Also signing out and rebooting is through dmenu so I have to hold the power button down and reboot just to leave dwm.

I just might be doing something wrong, but is this an issue?

**Comment by LukeSmithxyz** [comment]
What manual changes did you make?
