### ISSUE TITLE
How do I configure the system to use dvorak layout?

### ISSUE THREAD

**Issue by menkaur** [LukeSmithxyz/LARBS#282]
After configuring the system with the install script, I tried switching to dvorak by executing 

`setxkbmap -model pc104 -layout cz,us -variant ,dvorak -option grp:alt_shift_toggle`

or writing 

```
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "cz,us"
        Option "XkbModel" "pc104"
        Option "XkbVariant" ",dvorak"
        Option "XkbOptions" "grp:alt_shift_toggle"
EndSection
```

to `/etc/X11/xorg.conf.d/00-keyboard.conf` as suggested [here](https://wiki.archlinux.org/index.php/Xorg/Keyboard_configuration), but for me it didn't work, the input remains in querty format.

Would love to eventually see configuration option which would let me select dvorak as input method

**Comment by LukeSmithxyz** [comment]
Read the LARBS manual.
