### ISSUE TITLE
Screen Tearing

### ISSUE THREAD

**Issue by bsg8376** [LukeSmithxyz/LARBS#287]
I recently switched to LARBS and found that when watching videos, there is considerable screen tearing. It is present even when scrolling in a browser; however, in that case it is much less pronounced. Googling for screen tearing issues with DWM did not turn up any relevant results. Any ideas what could be the issue? I'm on an HP Envy 5 if that helps.

**Comment by Dark-Matter7232** [comment]
uninstall the default compositor and install picom, that would fix screen tearing issues

**Comment by LukeSmithxyz** [comment]
Screen tearing is solved here in any of the same ways it is solved on any other Linux system. It depends on your graphics drivers, etc.

**Comment by ergpopler** [comment]
@Dark-Matter7232 what is the default compositor?
