### ISSUE TITLE
Statusbar weather icon broken

### ISSUE THREAD

**Issue by delightfuldude** [LukeSmithxyz/LARBS#289]
Hi!
I'm on a complete fresh Arch installation on real hardware (librebooted Thinkpad X200). 
Instead of the weather icons this text is displayed in the statusbar:

`spawn telnet rainmaker.wunderground.com 3000`

Thats weird, because the weather script output works perfect when executed manually in the terminal.

**Comment by LukeSmithxyz** [comment]
Yeah this has come up before. There's another script/program called `weather`, I forget what pulls it, but you must've installed it and the statusbar is attempting to run it.

I've gone and renamed `weather` to `forecast` now to prevent that problem. You can rename the script in dwmblocks and the file or you can state its full path in dwmblock to get the `weather` you want.
