### ISSUE TITLE
How to Change Font of dwm-blocks

### ISSUE THREAD

**Issue by siddhantgoyal44** [LukeSmithxyz/LARBS#291]
Hey, the size of font of  dwm-blocks and the font size SystemWide also after fresh install of LARBS is too [small](https://ibb.co/cXV00XS), is there a way to increase it ?
BTW Thanks! For the awesome build.

**Comment by thalesglessa** [comment]
The font size, as well as the default font systemwide, can be changed in ~/.config/Xresources.

**Comment by siddhantgoyal44** [comment]
I tried changing that but it doesn't seem to work. I  recompiled both dwm and dwm-blocks but there were no visible changes. 
![pic-selected-201021-1711-10](https://user-images.githubusercontent.com/20769914/96715034-ab171f80-13c0-11eb-97e2-df7a7a98a3a6.png)

**Comment by thalesglessa** [comment]
I'm a bit of a noob myself so I really don't know how to troubleshoot correctly, but try running
> xrdb .config/Xresources

**Comment by katrushenkov** [comment]
To change dwmblocks font you should change this line at dwm config.h:
`static const char *fonts[]          = { "**Hack:size=9**", "JoyPixels:pixelsize=9:antialias=true:autohint=true"};`

After that recompile dwm and renew it

**Comment by m0rtis0** [comment]
Hi, another LARBS user here! I have wanted to change the font size of the system, dwmblocks and st, too. This is what I discovered:

- To change the font size for dwm and dwmblocks (the status bar), you have to edit ~/.local/src/dwm/config.h at lines 18 and 19:
`static const char *fonts[]          = { "JetBrainsMono Nerd Font:size=12", "JoyPixels:pixelsize=12:antialias=true:autohint=true"  };
static char dmenufont[]             = "monospace:size=10";
`
where you can edit the size= parameter and then run `sudo make install` in this directory. After, you can reload dwm with Super+Backspace and then "renew dwm"
Note: this only applies if you have `#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources &	` in ~/.xprofile (commented out).
If you don't have the # at the beginning of the line you can edit the size in ~/.config/Xresources at line 5: `*.font: JetBrainsMono Nerd Font:size=12
`
- For GUI applications and dialogs on your system to be displayed bigger I would recommend you installing lxappearance with pacman, and then running it. There you can tweak these parameters
- For st, the terminal, you can edit ~/.local/src/st/config.h at lines 8 and 9: `static char *font = "JetBrainsMono Nerd Font:pixelsize=18:antialias=true:autohint=true";
static char *font2[] = { "JoyPixels:pixelsize=10:antialias=true:autohint=true", "icons-in-terminal:style=in-terminal" };
` and then run sudo make install in this directory. Then reopen st.

**Comment by siddhantgoyal44** [comment]
Trying what @m0rtis0  said works, Thanks.

**Comment by Walkability** [comment]
I was able to manually get all my fonts to work except to Qt apps. If anyone else runs into this, check out this [link](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#Tips_and_tricks) . The solution was to use dconf-editor. Worked like a charm.

**Comment by Nomukov** [comment]
For some reason my fonts get smaller (terminal and bar itself), I didn't touch anything. Also I can't zoom in/out with hotkeys in terminal to see something... And I don't have Xresources in my configs, I wonder why.
