### ISSUE TITLE
Larbs installs then doesn’t let me boot into a desktop

### ISSUE THREAD

**Issue by rosekeyq** [LukeSmithxyz/LARBS#293]
I have tried to install larbs multiple times and it does the same thing. i enter dwm or i3, it's a black screen and then it puts me back to the login screen

**Comment by katrushenkov** [comment]
I have such issue, for example, at Arcolinux.  I couldn't fix it with .xinitrc/.zprofile/DM's settings and just deleted DM (LightDM). Then login became ok.

**Comment by LukeSmithxyz** [comment]
Make sure `libxft-bgra-git` is installed. Show your error logs if the problem persists.

LARBS is not intended to work with DMs without further configuration.

**Comment by 5833tP2** [comment]
Same issue here. New vanilla Manjaro-ARM, installed LARBS via Luke's script, installation runs fine up to the very end then there's a split-second error message (too fast to read) and then the normal screen asking to logout and log back in.

I'm now in a kind of boot loop that @rosekeyq describes: login screen, black screen, back to login screen.

How can I get into the system now to install `libxft-bgra-git`, and where/how can I find the error logs? (Not a total Linux n00b but not used i3 before.)

**Comment by rosekeyq** [comment]
> Same issue here. New vanilla Manjaro-ARM, installed LARBS via Luke's script, installation runs fine up to the very end then there's a split-second error message (too fast to read) and then the normal screen asking to logout and log back in.
> 
> 
> 
> I'm now in a kind of boot loop that @rosekeyq describes: login screen, black screen, back to login screen.
> 
> 
> 
> How can I get into the system now to install `libxft-bgra-git`, and where/how can I find the error logs? (Not a total Linux n00b but not used i3 before.)
Go to the login screen and hold ctrl + alt + f2 to bring you to tty2

**Comment by 5833tP2** [comment]
Thank you, @rosekeyq. I'm in!

I've tried to install `libxft-bgra-git` with `yay -S libxft-bgra-git` but I get the following error

```
(1/1) Parsing SRCINFO: libxft-bgra-git
 -> The following packages are not compatible with your architecture:
  libxft-bgra-git
Try to build them anyway?
```
I'm on `aarch64` not `x86` so took a punt and said Yes. The build seemed to go ok (no obvious errors, not that I really know what I'm looking for), but on reboot I still have the login screen - black screen - login screen cycle.

I can get into the system via tty2 (`ctrl + alt + f2` at the login screen) but that's not ideal. Is there any solution that will avoid this login loop problem?

**Comment by slappy96** [comment]
It seems something has changed with Xorg or package?.  I was unable to sucessfully boot into dwm with a vanilla LARBS install.  error was only resolved by installing entire xorg package.  The specific error after fresh install was: 
"etc/X11/xinit/xserverrc line 2 /usr/bin/X" ## paraphrase is that X or X symlink doesn't exist

I looked in /usr/bin and searched for X and found no Xorg or X symlink on non-working install.

I ventured into a working LARBS system and Xorg and X were there.

At any rate, the interim fix was to install entire pacman xorg collection

**Comment by carlikis** [comment]
Same issue ... installed `libxft-bgra-git` and xorg package, but login fails

**Comment by BaronInjusticia** [comment]
Apparently simple-mtpfs-git  has an error from the AUR. I dont know if this what makes the error.

**Comment by cigani** [comment]
if you install on manjaro install just the cli. installing any other DM will cause the issue because the i3 in your home will be mal-configured. causing i3 to fail. 

> Same issue here. New vanilla Manjaro-ARM, installed LARBS via Luke's script, installation runs fine up to the very end then there's a split-second error message (too fast to read) and then the normal screen asking to logout and log back in.
> 
> I'm now in a kind of boot loop that @rosekeyq describes: login screen, black screen, back to login screen.
> 
> How can I get into the system now to install `libxft-bgra-git`, and where/how can I find the error logs? (Not a total Linux n00b but not used i3 before.)

**Comment by 5833tP2** [comment]
Thanks, @cigani. Sorry for the delay in responding. I've had no luck installing Manjaro minimal cli. I'm running an ARM device and the ARM cli installer is not behaving. I seem destined never to try out dwm :(

**Comment by 5833tP2** [comment]
Update on installing LARBS on Manjaro-ARM. Success!

I gave up on trying to install Manjaro Minimal-cli. After a lot of hassle to get eh OS installed, the final result was a super-basic OS without Wifi out of the box and I did not have the energy to start from scratch with firmware updates and drivers, so ...

I installed Manjaro-I3, connected to my home wifi, updated the system, downloaded `larbs.sh` then removed i3. Rebooted to tty2, ran `larbs.sh`, then rebooted into the new environment. Success!

A couple of things I still have to fix:

1. the Manjaro graphical login screen still appears at boot time and asks me to login but this fails because there's no more i3. I `ctrl-alt-f2` into tty2 and login in from there. I don;t yet know how I can skip this graphical login screen step.
2. LARBS installs Brave but this is an x86 binary and I'm running aarch64 so it fails. There may be other surprises like that that I haven't found yet.

I'm irrationally excited about using `dwm` tiling window manager and suckless software. I hope that less truly is more. Thanks!

**Comment by ergpopler** [comment]
I am having this issue, x86 laptop, when i log in xorg says some weird error thing then makes me login again... i installed libxft-bgra-git, didn't solve anything.

**Comment by kiprasmel** [comment]
There could be other issues, but for me it was the `/etc/X11/xorg.conf` file -- since I have arch on a USB, the config, once calibrated to my laptop, works just fine, but if I plug the USB into some other computer and try to log in, Xorg throws the same `no screens found(EE)` error. Then, disabling the xorg config for the time being solves the issue -- I even wrote a short script for it since it came up so often:

```bash
#!/usr/bin/env bash

if [ -f "/etc/X11/xorg.conf" ]; then
	printf "sudo mv /etc/X11/xorg.conf /etc/X11/xorg.conf.disabled\n"
	sudo mv /etc/X11/xorg.conf /etc/X11/xorg.conf.disabled
elif [ -f "/etc/X11/xorg.conf.disabled" ]; then
	printf "sudo mv /etc/X11/xorg.conf.disabled /etc/X11/xorg.conf\n"
	sudo mv /etc/X11/xorg.conf.disabled /etc/X11/xorg.conf
else
	printf "/etc/X11/(xorg.conf|xorg.conf.disabled) not found!"
	exit 1
fi

```

**Comment by 9ahmed** [comment]
btw for the newbies, if u make an error in your config.h, your desktop wont boot. So read the system logs and fix any syntax errors u make while settings colors or keybinds 0.0

**Comment by LukeSmithxyz** [comment]
Firstly, to clarify, the LARBS script installs dwm, not i3 at all anymore. I suppose it's good to know some people are using dwm fine without even knowing they are using it.

As for people on non-x86 systems, there's nothing I can really do for you if you can't get `libxft-bgra` to compile. You'll have to take it up with whoever manages that in the AUR. That's an issue out of my control.

As to the issue of `xorg-server` not installing or pulling other required dependencies, I can't replicate this, but I might just add `xorg-apps` if that does it.

**Comment by kocotian** [comment]
there is also an alternative to temporarily remove all statusbar scripts in ~/.local/bin/statusbar/, so dwm will not crash
