### ISSUE TITLE
Suggestion for "pass" master key input with dmenu

### ISSUE THREAD

**Issue by Bumbadawg** [LukeSmithxyz/LARBS#296]
Sup, you can use https://github.com/ritze/pinentry-dmenu for using dmenu as your PGP pin entry password input program.
It helps to homogeneously use dmenu to seek for pass entries and input your master key. Dmenu is OP compared to GTK since it can overlap fullscreen apps like online games™️ that require to input your DRM-compliant 4 figures account passphrases amirite.

HF.

**Comment by LukeSmithxyz** [comment]
I'll test it around myself and see how glitchy it is. I'll add it in once I'm confident with it.
