### ISSUE TITLE
Optionality in Programs installed?

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/LARBS#30]
I'm thinking about removing the feature of the user choosing what programs to install at the first run in favor of just installing the same bare necessities and then giving some suggested programs in the offline README. As context:

## Browsers

Originally I gave users the choice of installing Waterfox, qutebrowser or Firefox. The AUR build of Waterfox is painfully long and often fails, so I don't include it anymore---and I don't actively maintain my qutebrowser configs. Firefox is, for all intents and purposes the default LARBS browser, so it will probably just be installed by default. I've also developed a custom profile with some minor cleanups and privacy features to make Firefox bearable by default.

## Document formatting

Originally I gave users the choice of whether to install TeX packages or Libreoffice or nothing for document creation. At this point, I think there's no point in having either (TeX is a huge install which probably turns people off in the middle, and LO is lame of course). I also don't feel that having pandoc is a good idea just because it's a long install. If users want any of these programs, they can easily install them later.

I will probably have R markdown installed by default though since R is installed for the calculator (R Markdown is only 2.4M more). It gives you well-formatted documents with much less drain.

## Other junk

Since I was giving users these options, I tacked on other options like terminal decorations, Blender, GIMP and some other things, but I might as well get rid of them. (I'll probably make GIMP installed by default though).

If anyone things that I should maintain these choices, say now or I'll probably change them very soon. It would just save some effort and time for everyone if these extra packages were left to the user to install.

**Comment by CecileGS** [comment]
Why not just move the feature to the end of the installer then? Something like "Congrats! You've installed all the basic necessities for a working system. Would you like to install some more optional packages? (Y/n)"

**Comment by meolar** [comment]
First, I like LARBS as it currently stands.  It's very convenient to have nearly everything I use installed the way you have it.  And having all the LaTeX stuff installed, time comsuming though it may be, is really useful.  Also, the installation process only happens once and then I have a very usable setup.

Next, I like having both Firefox and qutebrowser (which I am using as I write).  However, it was not a big deal to install the latter and fix the startup bugs in the config file (which didn't keep it from being useable anyway) if you don't feel like maintaining the config file.  The vim key bindings are really nice to use.

However, I also like CecileGS's suggestion if it isn't too much work on your part to implement.  Another altermative might be to add an explanation to the current choice list of what to install, so people who are in a hurry and don't care about LaTeX can choose not to install it.

**Comment by CecileGS** [comment]
Also if I may hazard another suggestion that just popped into mind; how about instead of a "offline guide" telling us what optional packages are recommended for the user, how about a "script with lines of code that you need to uncomment" in the style of Pacman's config file?

E.g. if you want to install `qutebrowser` in lieu of `Firefox`, it would be a matter of simply uncommenting the former and commenting out the latter - the user will still be forced to choose the software they want out of their own explicit volition, and most likely will also find this method to be less intrusive compared to all the other proposals made so far in this thread.

**Comment by LukeSmithxyz** [comment]
Okay thanks for the feedback. I've also gotten emails about this.

I think I'm going to remove the optional programs menu and replace it with a script that will come in the home directory of the voidrice repo. It's also double as a dependency installer for people who want to just clone the repo and use it without running LARBS (although less complete). I'm going to have to think about precisely what I want to be installed by default, but if I need public input, I'll make a new issue.

Ends up that #29 was partially caused by the options script as is, so I think that LARBS will be easier for me to maintain if I make it a more controllable post-install script anyway.
