### ISSUE TITLE
i am sans sans i am

### ISSUE THREAD

**Issue by cannyboy** [LukeSmithxyz/LARBS#300]
Somehow my fonts have gone wonky, and I seem to be without sans. I did a bit of pacman and yay installing and un-installing, so maybe that got rid of the mono sans somehow ..?

<img width="1272" alt="Screenshot 2020-11-18 at 16 34 10" src="https://user-images.githubusercontent.com/1590436/99560153-74cbc080-29bd-11eb-82c5-66188c502321.png">

Anyway, any idea on how to get back to normal?

**Comment by LukeSmithxyz** [comment]
It's monospace you're missing.

Noto Sans Mono and Liberation Mono are set as the default in the standard fontconfig file. If you uninstalled these, that would be the issue. You can just change `~/.config/fontconfig/fonts.conf` to add your own preferred mono font if you'd like.

**Comment by cannyboy** [comment]
thanks. `pacman -S noto-fonts` has solved my problem.
