### ISSUE TITLE
Hey how do i customize the possible window layouts?

### ISSUE THREAD

**Issue by ergpopler** [LukeSmithxyz/LARBS#303]
Hey I want to be able to customize the possible layouts so it can look like the way it does in this picture:

https://ibb.co/SmKrcXX

**Comment by anntnzrb** [comment]
This looks like 1 master window with 2 slave windows, apparently with zero gaps.

I suggest you check out the [provided pdf](https://larbs.xyz/dwm.pdf).
`Super+F1` on **LARBS**
