### ISSUE TITLE
dwm bar text alignment

### ISSUE THREAD

**Issue by delightfuldude** [LukeSmithxyz/LARBS#304]
I'm on a fresh arch and larbs install and the text in the dwm bar is aligned to the top. Is there a way to center it?
![dwmbar](https://user-images.githubusercontent.com/41424438/100192161-b1357a00-2ef1-11eb-87ae-d9bfe3c4cd8a.png)

**Comment by LukeSmithxyz** [comment]
I suppose you want the status text in the center of the bar while still all at the top?

There is no built-in option for that. If you want to patch it in, you can model it like this patch, which centers the window name:
https://dwm.suckless.org/patches/centeredwindowname/

**Comment by delightfuldude** [comment]
Sorry, but take a closer look to the screenshot I've posted before. The text (not the icons) are aligned to the top, there isn't any gap between the text and the bar (screen) border.
I think it's supposed to look like this:
![dwmbar2](https://user-images.githubusercontent.com/41424438/100235131-4a818200-2f2c-11eb-85f5-d604838e2752.png)
As you can see, the text is perfectly aligned in the center. Maybe there is a problem with the font? Do you have an fool-proof tutorial on how to change the font system wide?

**Comment by LukeSmithxyz** [comment]
If you're referring to the fact that your emojis are placed smaller/lower than your text, I suppose that's because a different font of different size is being used for the emoji. You might want to jigger with that.
