### ISSUE TITLE
xcompmbr

### ISSUE THREAD

**Issue by fuilip123** [LukeSmithxyz/LARBS#305]
Hi,
Everytime dwm starts up, xcompmgr makes the screen go gray for a second. I found the solution: change your .xprofile to "sleep 0.3 && xcompmgr &" instead of just "xcompbgr &". This is just a detail but it is annoying...

**Comment by LukeSmithxyz** [comment]
I suppose you want the status text in the center of the bar while still all at the top?

There is no built-in option for that. If you want to patch it in, you can model it like this patch, which centers the window name:
https://dwm.suckless.org/patches/centeredwindowname/
