### ISSUE TITLE
pulseaudio pulsemixer issue

### ISSUE THREAD

**Issue by 9ahmed** [LukeSmithxyz/LARBS#308]
sometimes when i boot into the larbs desktop my audio does not work. When i try running pulsemixer with the keybind, my screen just jitters. When i run it in terminal it says Falied to connect to pulseaudio: Connection refused. But when i reboot it usually starts working again

**Comment by LukeSmithxyz** [comment]
Are you on Arch or Artix? Did you install before or after fbc42104c01eef896c6c094c332eb7304d2cec02?

**Comment by 9ahmed** [comment]
> Are you on Arch or Artix? Did you install before or after [LukeSmithxyz/voidrice@fbc4210](https://github.com/LukeSmithxyz/voidrice/commit/fbc42104c01eef896c6c094c332eb7304d2cec02)?

i am on arch and i installed the larbs 2 days ago and arch about a month ago

**Comment by LukeSmithxyz** [comment]
Well do you have the lines depicted in that change, specifically in the xprofile file? If you do, you might want to delete the line. If you don't, you might want to add it.

It could be either cause as I'm not sure how it is on Arch now.

**Comment by 9ahmed** [comment]
i dont quite understand you, what change? what line?

**Comment by LukeSmithxyz** [comment]
The lines from the commit I linked above.

**Comment by mateusgomes01** [comment]
@NETLIFYHOSTINGAHMD 

Is your pacman updated and do you have refreshed arch keyrings? This happened with me but it was all my fault for running larbs.sh without checking for these two crucial things. My larbs build is now smooth and confy as intended
