### ISSUE TITLE
Mic input not being detected

### ISSUE THREAD

**Issue by 9ahmed** [LukeSmithxyz/LARBS#309]
my mic isnt being detected on discord or anywhere else

**Comment by 9ahmed** [comment]
issue solved by reinstalling arch and reinstalling larbs /shrug

**Comment by katrushenkov** [comment]
> issue solved by reinstalling arch and reinstalling larbs /shrug

Unfortunately this is not a issue solution, but sometimes it is the only way out for us...

**Comment by LukeSmithxyz** [comment]
He probably originally installed when pulse was broken.
