### ISSUE TITLE
Future direction of LARBS: wiki and CONTRIBUTORS.md

### ISSUE THREAD

**Issue by CecileGS** [LukeSmithxyz/LARBS#31]
LARBS isn't the most friendly open source project to be contributing for. There's an issue tracker which makes it easy for everyone to know what bugs need to be fixed and submit their patches for them, but other than that only Luke knows how he wants LARBS to look like and the endgame goal that he wants to work towards - Luke, if you share with us your vision then it would be a win-win for everyone.

Atm everyone is just doing their own thing by themselves, and instead of having a centralized forum for suggestions it's split between Github and Luke's forum.

Scope creep, duplication of efforts, and feature bloat are problems that'll inevitably become apparent as LARBS becomes bigger and better. Even if there's no big ambitions for LARBS, it would be super helpful for even a tiny team of volunteer devs to be on the same page in knowing what features need to be implemented or polished.

**Comment by LukeSmithxyz** [comment]
This isn't an "open source project", it's a bash script that installs a list of programs and switches a couple of switches. I don't want it to be "bigger and better", but smaller and less intrusive.

I want people to notice errors and push minor changes as they have been doing. But the script is so small that it would be much more stressful for to me have to telegraph minor goals to everyone and have to sort through and cherrypick strident and contradictory commits than it is now for me to just change things as needed.

There is no "development process" on this script as far as I'm concerned. It already does what I need it to do and I patch leaks or make things more elegant when needed.

**Comment by CecileGS** [comment]
Hmm okay, that's fair enough as LARBS is ultimately your creation.

**Comment by CecileGS** [comment]
And also my dude... This is very much an "open source project" in EVERY single definition of the term. When people say open source, they mean that the source code is publicly available for modification and auditing, whether or not it's simply a bundle of scripts or enterprise scale software. This is even moreso evident with the fact that LARBS is licensed under the GPLv3.

Even if your prospects for LARBS is a "short term personal thing of mine", there are other people who may not feel the same way as you do. It's a lot better to have a dozen devs working on the upstream of LARBS, than it is to have a dozen devs working on a dozen forks of LARBS. The former case means that LARBS will never live up to its full potential, while the latter means that it'll be easier for newfriends with not-so-much-technical-knowhow to be able to fork off their own version of an outstandingly well done LARBS for their own personal everyday needs.
