### ISSUE TITLE
Slow keyboard input when typing in zsh.

### ISSUE THREAD

**Issue by 9cy** [LukeSmithxyz/LARBS#314]
When I'm in insert mode within ZSH, the typing is slow. I've tried with DWM and with-out and anytime I'm using ZSH its slow. Anything else is fine, Nvim, Vim, other typing programs, but ZSH insert mode is slow. Is this just a config setting that I can change?

**Comment by LukeSmithxyz** [comment]
Is this a fresh install? Have you installed anything else on your system?

**Comment by 9cy** [comment]
> Is this a fresh install? Have you installed anything else on your system?

All I have performed before hand is setup my Pacman key, sync and refresh Pacman, and add a user.

**Comment by 9cy** [comment]
... I think I've just found out what was happing. After trying to figure out why this was happening, I noticed that only the first few letters would "lag". I think what's happening is that as the auto-completion engine is trying to figure out the command I'm about to use, and it's causing some slowness.

**Comment by LukeSmithxyz** [comment]
Well that shouldn't really be taking any noticeable time... Are you
using a computer with an ancient processor or something?

**Comment by 9cy** [comment]
That's what I don't understand either, I'm currently on a Ryzen 9 3900XT clocked in at 4.9 GHz so there shouldn't be any slowdowns, it could derive from hard drive speed from what I understand but I don't see why that would be noticeable either with modern drives.

**Comment by 9cy** [comment]
Alright, the final update to the sage... I HAD ONE OF MY WORK DRIVES MOUNTED AND IT WAS ITERATING OVER THOUSANDS OF FILES WHEN I TYPED EVEN ONE CHARACTER... The poor thing was trying to auto-complete for over 3000 files... Whew, got it un-mounted, works like a charm haha.
