### ISSUE TITLE
installing 'brave-bin' (27 of 21) for hours

### ISSUE THREAD

**Issue by nielsreinke** [LukeSmithxyz/LARBS#317]
am i doing something wrong if the LARBS installation gets stuck on this part?

i just installed some version of artix btw

**Comment by nielsreinke** [comment]
*(27 of 61)

**Comment by kiprasmel** [comment]
remove brave from [LARBS/progs.csv](https://github.com/LukeSmithxyz/LARBS/blob/master/progs.csv) & add your own browser (like [firefox-developer-edition](https://archlinux.org/packages/?name=firefox-developer-edition)) hehe

**Comment by lukerb52** [comment]
Is your internet particularly slow?

Run `yay -Scc` to clear the yay caches, then run `yay -S brave-bin`. This way, if it still doesn't work, you will see what step the installation is stuck on.
