### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by khanlesslinux** [LukeSmithxyz/LARBS#318]
I tried to install LARBS on top of an Artix/xfce install. I was missing a few xorg packages but after I installed them, the window manager glitched out and spat out a lot of font issues. 
![IMG_20201229_171802755](https://user-images.githubusercontent.com/76756268/103320424-e9514080-49fa-11eb-95b9-d151fdf48087.jpg)
![IMG_20201229_171807569](https://user-images.githubusercontent.com/76756268/103320428-ec4c3100-49fa-11eb-9638-ed0415b006cd.jpg)

**Comment by LukeSmithxyz** [comment]
You're neither running st or or dwm, so I can scarcely say how this is relevant to LARBS.
