### ISSUE TITLE
Pulseaudio cpu usage 100%

### ISSUE THREAD

**Issue by CoderBasis** [LukeSmithxyz/LARBS#319]
I've been trying with both your "necessary for Artix" line and without it but every time I exit dwm and reenter pulseaudio shoots to 100%. I cannot address the issue. My initial thought was that --exit-idle-time=-1 maybe was the problem, but apparently the issue persists. Any ideas?

**Comment by LukeSmithxyz** [comment]
I've actually noticed that occasionally, but I rarely exit and reenter, so I never looked into it. I originally expected it was because it tried to open to instances of pulse---that's why I have it check for an alread-running instance in the `xprofile`, but it might be something else.

I'll play around with it when I get the chance.

**Comment by CoderBasis** [comment]
Thanks, do so.m?n 11 jan. 2021 kl. 15:44 skrev Luke Smith <notifications@github.com>:
I've actually noticed that occasionally, but I rarely exit and reenter, so I never looked into it. I originally expected it was because it tried to open to instances of pulse---that's why I have it check for an alread-running instance in the xprofile, but it might be something else.
I'll play around with it when I get the chance.

?You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by LukeSmithxyz** [comment]
Fixed in the voidrice repo. I just had mistyped something obvious. Check the newest change to the xprofile and that will fix it.

**Comment by CoderBasis** [comment]
Thanks!ons 20 jan. 2021 kl. 20:56 skrev Luke Smith <notifications@github.com>:
Fixed in the voidrice repo. I just had mistyped something obvious. Check the newest change to the xprofile and that will fix it.

?You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
