### ISSUE TITLE
dwm needs to renew after boot (pywal)

### ISSUE THREAD

**Issue by AlbertoTrigo** [LukeSmithxyz/LARBS#322]
When using pywal (wal command) it doesn't modify the status bar color nor the border colors. You have to manually reset it after every boot.

**Comment by LukeSmithxyz** [comment]
Use the `setbg` script as a wrapper for pywal. It takes care of this.

**Comment by tienbuigia** [comment]
Hey Luke, I used `setbg` but still have to renew after every boot.
