### ISSUE TITLE
Existing user with btrfs/snapper .snapshots dir with ReadOnly snapshots chown issue

### ISSUE THREAD

**Issue by panabar** [LukeSmithxyz/LARBS#323]
First of all, thank you. The script is great. I've used and loved the script on my laptop. My issue came up when I wanted to replicate the setup that larbs provides on my desktop.

I have a desktop  artix/runit install on top of btrfs with a separate subvolume for my existing user and I use snapper to take snapshots  of my home and put them into ~/.snapshots. These are readonly snapshots.

Last night I've backed up my homedir and ran larbs.sh, gave it my current username. After installing the programs it started to issue chown commands recursively on my home dir, and got stuck for hours in the .snapshot pit. 

I ended up running larbs on a new user and copied my files from my old dir.

**Comment by LukeSmithxyz** [comment]
Okay. I don't actually think the `-R` option is necessary where it caused this problem, so I will test it briefly and probably remove it.
