### ISSUE TITLE
cron not enabled by default?

### ISSUE THREAD

**Issue by kiprasmel** [LukeSmithxyz/LARBS#324]
I was trying to figure out why my cron jobs weren't running. Turns out I didn't do `sudo systemctl enable cronie --now` (as per [1]).

Should we have this in the `larbs.sh` script?

[1] https://wiki.archlinux.org/index.php/Cron#Activation_and_autostart

**Comment by LukeSmithxyz** [comment]
No. Nothing on the dotfiles needs cronjobs. It's the user's responsibility and opportunity to enable it if they want.
