### ISSUE TITLE
setbg broken after update

### ISSUE THREAD

**Issue by CoderBasis** [LukeSmithxyz/LARBS#325]
Hello,
yesterday setbg/xwallpaper broke for me and outputs bad system call and invalid system call resp. The issue seems to be related to glibc: if I downgrade glibc I can set a wallpaper but dwm brakes and if I keep my current glibc dwm works but without wallpaper. 

What shall I do?

**Comment by LukeSmithxyz** [comment]
The issue has already been solved upstream. Install `xwallpaper-git` now if you want the fix now, otherwise wait a bit more for the update in the main repos.
