### ISSUE TITLE
correct location for screencast / mpv issue? -- Cannot find main.* for any supported scripting backend in: /home/beach/.config/mpv/scripts/mpvSockets

### ISSUE THREAD

**Issue by timbeach** [LukeSmithxyz/LARBS#326]
Hi, I'm running Artix runit base with LARBS installed immediately after base installed.
I'm noticing a couple things about mpv.

1. After creating a screencast using Mod+PrintScreen, when I try to view it with `mpv screencast.mp4` I get the error `Cannot find main.* for any supported scripting backend in: /home/beach/.config/mpv/scripts/mpvSockets`
Failed to recognize file format.` (obviously "beach" is my username on this machine)
2. (This may be a separate issue, but it seems related) When I try to use Mod+Shift+C I don't get the mpv window with feeding from /dev/video0. In fact, if I run `mpv /dev/video0` I get the same error as above `Cannot find main.* for any supported scripting backend in: /home/beach/.config/mpv/scripts/mpvSockets`

Much appreciated

**Comment by V1leDev** [comment]
I get the same kind of message every time I open up a video with mpv. The video plays correctly, but still.

**Comment by LukeSmithxyz** [comment]
Shoot lol. Try running `git submodule init` then `git submodule update` in the home directory and see if that fixes it.

**Comment by V1leDev** [comment]
Tried that, still the same error.

**Comment by LukeSmithxyz** [comment]
Okay. Just clone run `git clone https://github.com/wis/mpvSockets.git` and move the directory to `~/.config/mpv/scripts/mpvSockets` (the directory may already exist, just delete it).

This should automatically be fixed on the script now.

**Comment by V1leDev** [comment]
Okay tried that. Still the same error message. This seems like an mpv issue, you don't get this error right?

**Comment by LukeSmithxyz** [comment]
Well, it looks like the submodule is indeed working, and I think the error message is a red herring. Not sure what's going on, but it shouldn't be an issue. I'll look into suppressing or removing the error.

**Comment by V1leDev** [comment]
What exactly is this script used for anyway? I've read the README and it says something about creating a new socket for each mpv instance. Could you maybe explain?

**Comment by BachoSeven** [comment]
@V1leDev the `mpvSockets` submodule is used for instance in the `pauseallmpv` script, I personally also use it to queue mpv videos.
The warning you mentioned has been reported: https://github.com/wis/mpvSockets/issues/5
