### ISSUE TITLE
forecast

### ISSUE THREAD

**Issue by Jkek823** [LukeSmithxyz/LARBS#327]
I don't think this is a LARBS-specific issue but forecast isn't working for me. I tried curling wttr.in/$LOCATION manually and it didn't work either leaving me with pic related. I think $LOCATION is messed up but I'm not sure how I would go about fixing it since I don't know how it's generated and I couldn't find anything regarding "$LOCATION" online.
![32332A51-E752-43C6-B844-76539F311C34](https://user-images.githubusercontent.com/65468098/107827118-22980280-6d54-11eb-8adf-c44190ac0f3e.jpeg)
Thank you in advance for any assistance you can offer.

**Comment by LukeSmithxyz** [comment]
Read the text below. For whatever reason, `wttr` couldn't find your location.

The `$LOCATION` variable is for these circumstances, or for when you want to manually specify a location.
Just, say add `export LOCATION=yourcityname` to your `zprofile` and on reload it will search that location. If you don't manually set a `$LOCATION`, it will just do the default wttr query that tries to guess your location.

**Comment by Jkek823** [comment]
Thanks, Luke, that fixed it. :)
