### ISSUE TITLE
Setbg destroys transparency on open terminal windows

### ISSUE THREAD

**Issue by gammaleak** [LukeSmithxyz/LARBS#330]
uname -srm: Linux 5.10.16-artix1-1 x86_64
VGA compatible controller: Intel Corporation HD Graphics 5500
Driver: xf86-video-intel (i915)

When the setbg script changes the wallpaper, open terminal windows lose their transparency. This may be related to having python-wal installed as well, but I'm not entirely sure about that.

EDIT: If you press Alt-a/s in the terminal, the transparency comes back, and also seems to remember the level it was at previously (modified by one position lighter or darker).

**Comment by kronikpillow** [comment]
LARBS is just a arch installer, this belongs in lukesmithxyz/voidrice
