### ISSUE TITLE
Icons not working in lf after installing larbs

### ISSUE THREAD

**Issue by Anas-Sherif** [LukeSmithxyz/LARBS#331]
the icons in lf dont work in lf after installing larbs but they work fine in the terminal or vim

**Comment by LukeSmithxyz** [comment]
Well, what do you mean by "don't work"?

**Comment by Anas-Sherif** [comment]
they show question marks instead of icons

**Comment by Anas-Sherif** [comment]
> Well, what do you mean by "don't work"?

they show question marks instead of icons

**Comment by LukeSmithxyz** [comment]
What's you `$LANG` variable?

**Comment by Anas-Sherif** [comment]
> What's you `$LANG` variable?

en_CA.UTF-8

**Comment by dvsociety** [comment]
Same problem 
![pic-selected-220410-1618-49](https://user-images.githubusercontent.com/102924958/162629425-de466fc7-e836-4158-8242-337b8945e65e.png)

**Comment by Anas-Sherif** [comment]
> Same problem ![pic-selected-220410-1618-49](https://user-images.githubusercontent.com/102924958/162629425-de466fc7-e836-4158-8242-337b8945e65e.png)

Change your LANG variable to en_US.UTF-8

**Comment by dvsociety** [comment]
> 

It work in part. It has visual errors and stops working when restarting the terminal.

**Comment by dvsociety** [comment]
> > Same problem ![pic-selected-220410-1618-49](https://user-images.githubusercontent.com/102924958/162629425-de466fc7-e836-4158-8242-337b8945e65e.png)
> 
> Change your LANG variable to en_US.UTF-8

It work in part. It has visual errors and stops working when restarting the terminal.

**Comment by Anas-Sherif** [comment]
> > > Same problem ![pic-selected-220410-1618-49](https://user-images.githubusercontent.com/102924958/162629425-de466fc7-e836-4158-8242-337b8945e65e.png)
> > 
> > 
> > Change your LANG variable to en_US.UTF-8
> 
> It work in part. It has visual errors and stops working when restarting the terminal.

You have to edit edit /etc/locale.gen and uncomment en_US.UTF-8 then run `sudo locale-gen` & /etc/locale.conf and set it to en_US.UTF-8

**Comment by dvsociety** [comment]
> > > > Same problem ![pic-selected-220410-1618-49](https://user-images.githubusercontent.com/102924958/162629425-de466fc7-e836-4158-8242-337b8945e65e.png)
> > > 
> > > 
> > > Change your LANG variable to en_US.UTF-8
> > 
> > 
> > It work in part. It has visual errors and stops working when restarting the terminal.
> 
> You have to edit edit /etc/locale.gen and uncomment en_US.UTF-8 then run `sudo locale-gen` & /etc/locale.conf and set it to en_US.UTF-8

Not work for me

**Comment by Anas-Sherif** [comment]
> > > > > Same problem ![pic-selected-220410-1618-49](https://user-images.githubusercontent.com/102924958/162629425-de466fc7-e836-4158-8242-337b8945e65e.png)
> > > > 
> > > > 
> > > > Change your LANG variable to en_US.UTF-8
> > > 
> > > 
> > > It work in part. It has visual errors and stops working when restarting the terminal.
> > 
> > 
> > You have to edit edit /etc/locale.gen and uncomment en_US.UTF-8 then run `sudo locale-gen` & /etc/locale.conf and set it to en_US.UTF-8
> 
> Not work for me

Open a terminal and type `echo $LANG` and `echo $LF_ICONS` and show me what comes out.

**Comment by dvsociety** [comment]
> > > > > > Same problem ![pic-selected-220410-1618-49](https://user-images.githubusercontent.com/102924958/162629425-de466fc7-e836-4158-8242-337b8945e65e.png)
> > > > > 
> > > > > 
> > > > > Change your LANG variable to en_US.UTF-8
> > > > 
> > > > 
> > > > It work in part. It has visual errors and stops working when restarting the terminal.
> > > 
> > > 
> > > You have to edit edit /etc/locale.gen and uncomment en_US.UTF-8 then run `sudo locale-gen` & /etc/locale.conf and set it to en_US.UTF-8
> > 
> > 
> > Not work for me
> 
> Open a terminal and type `echo $LANG` and `echo $LF_ICONS` and show me what comes out.

Fixed, it was solved when I put the language of my country (Argentina).
