### ISSUE TITLE
Keypress of Ä, Ö, Å and some other keys outputting <ffffffff>

### ISSUE THREAD

**Issue by akke754** [LukeSmithxyz/LARBS#332]
I've been trying to get my keymap properly configured and working for the past couple of days in LARBS, I've tried everything that earlier issues have suggested and none of the solutions work. I did the keyboard configuration according to arch wikis page on it and i got most keys working, but a few keys did not work such as Ä, Å, Ö and they output <.ffffffff> in the terminal and in vim a question mark symbol. The keys work perfectly in brave. Does anyone know a solution to this?

**Comment by lionslancer** [comment]
If you're still having problems, I just dealt with this. You need to set `setxkbmap -layout se -option caps:super` in `~/.local/bin/remaps` as in #16.

**Comment by akke754** [comment]
That didn't fix it.

**Comment by lionslancer** [comment]
Okay, I can think of two more things I've changed that might be related.

First is to set the keyboard layout in `/etc/vconsole.conf`.

Second is to set up `/etc/locale.conf` appropriately, after generating all relevant locales obviously.
```
# For Swedish keyboard
LANG=sv_SE.UTF-8
# For English system language
LANGUAGE=en_US
```

**Comment by akke754** [comment]
Okay, now some buttons are outputting "?" instead of <.fffffff>  and one button started working.

**Comment by et-8** [comment]
I just made a fresh install of LARBS on Artix with runnit in Virtualbox. Default keyboard layout is Swedish.
My /etc/locale.gen
```
sv_SE.UTF-8 UTF-8
sv_SE ISO-8859-1
```
My /etc/vconsole.conf 
```
KEYMAP="sv-latin1"
```
My /etc/locale.conf 
```
LANG="sv_SE.UTF-8"
LC_COLLATE="C"`
```
Check settings with the `locale` command, outputs if all is correct:
```
LANG=sv_SE.UTF-8
LC_CTYPE="sv_SE.UTF-8"
LC_NUMERIC="sv_SE.UTF-8"
LC_TIME="sv_SE.UTF-8"
LC_COLLATE=C
LC_MONETARY="sv_SE.UTF-8"
LC_MESSAGES="sv_SE.UTF-8"
LC_PAPER="sv_SE.UTF-8"
LC_NAME="sv_SE.UTF-8"
LC_ADDRESS="sv_SE.UTF-8"
LC_TELEPHONE="sv_SE.UTF-8"
LC_MEASUREMENT="sv_SE.UTF-8"
LC_IDENTIFICATION="sv_SE.UTF-8"
LC_ALL=
```
**This only enables Ä, Ö, Å in a TTY.**
When switching user open a terminal with a login shell, otherwise the $LANG and other variables will be unset.
```
$ sudo su -
```

The keyboard layout changes back to English after `startx` command has run and you get into the Window Manager **DWM**.
**To solve that** I apply my preferred method from this issue #263.
```
/etc/X11/xorg.conf.d/00-keyboard.conf
```
```
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "se"
        Option "XkbModel" "pc105"
EndSection
```

> If you still have issues, write what you use Arch or Artix, the base install or installed with a desktop live cd and post your current language settings. Then I will try to reproduce your issue.

**Comment by akke754** [comment]
Okay I got it working! For some reason i was setting LC_CTYPE in ~/.config/x11/xprofile to se_FI.UTF-8 (supposed to be sv_FI.UTF-8), which is probably a typo i made somewhere along the way of setting the locale. Thanks for the help.
