### ISSUE TITLE
Changing colors with wal broke Brave notifications.

### ISSUE THREAD

**Issue by longdas** [LukeSmithxyz/LARBS#333]
Not _exactly_ sure what caused this but I believe it to be the fault of wal. Notifications from Brave now display as large ugly banners up top, covering dmenu. This is both for BAT ads or for notifications such as IPFS going online. Where can these notification prompts be edited? Are they part of dmenu, brave, or something else? 

Also unrelated, but where do you change the keybindings? Will changes in inputrc overwrite the ones that come already configured?

Thanks.

**Comment by wlw-codes** [comment]
Also having this issue, though it is not limited to just Brave notifications (at least for me)

**Comment by kronikpillow** [comment]
this is a issue you should report on lukesmithxyz/voidrice ... LARBS is just a Arch installer
