### ISSUE TITLE
question about su

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/LARBS#334]
hey luke, i picked up this from one of your videos from the past ...
i edit /etc/passwd and change the root users home directory to
root:x:0:0::/home/kronikpillow:/bin/zsh

and this is how i used to get my dotfiles sources by the root user when i did su to login to it ... 

recently, after a fresh LARBS reinstall, when I su, it doesn't source my dotfiles, but when I login to root, it does ... what could I be doing wrong? does larbs now disable the su user?

**Comment by LukeSmithxyz** [comment]
Su isn't a user, it's a command. Check its manual. Run `su -l` to treat it as a logon and read all your typical dotfiles.
