### ISSUE TITLE
Shows quick preview of dwm and wallpaper and bar, then back to console.

### ISSUE THREAD

**Issue by phneutral26** [LukeSmithxyz/LARBS#335]
error with some x program

**Comment by et-8** [comment]
Please give more info. Any error messages?

- Have you installed on **hardware** or **virtual machine**?
- **Arch** or **Artix** as base?
- On top of any desktop environment?
- Have you installed a **video driver** and **libxft-bgra-git**?

**Comment by phneutral26** [comment]
I installed on hardware, Arch as base. Normal Linux kernel. No, base install, directly installed larbs. No, i didnt install a video driver...

**Comment by phneutral26** [comment]
i could reinstall bc i uninstalled arch, but then you would have to wait a bit for the error messsage.

**Comment by et-8** [comment]
To find out what video driver you need  check the Arch wiki about video drivers. [https://wiki.archlinux.org/index.php/Xorg#Driver_installation](https://wiki.archlinux.org/index.php/Xorg#Driver_installation)

**Comment by phneutral26** [comment]
Thanks! Thats all?

**Comment by et-8** [comment]
The video driver should pull in the package [xorg-server-devel](https://archlinux.org/packages/extra/x86_64/xorg-server-devel/) automatically. It's been a long time since i installed on hardware and the Arch wiki installation guide has changed a little.
