### ISSUE TITLE
Uninstalling LARBS?

### ISSUE THREAD

**Issue by sysgrammer** [LukeSmithxyz/LARBS#336]
How do I uninstall your configs and larbs itself?

**Comment by jemadux** [comment]
move your home directory to other directory 
create a directory of your username in home 
and then give the ownershirp to that folder

**Comment by et-8** [comment]
LARBS doesn't come with an uninstaller yet.

**WARNING!!!**
_PLEASE DON'T EXECUTE THE COMMANDS IF YOU ARE UNSURE OF WHAT THEY WILL DO! THESE COMMANDS WILL REVERT THE SYSTEM TO BASE ARCH OR ARTIX, LEAVING YOU WITHOUT A DESKTOP ENVIRONMENT (GUI)._

_Test the process in a virtual machine first to see what is going to happen._
_To give an example, the progs.csv contains the package **man-db**, which when removed deletes all the **manpages** from the system._

To remove the dotfiles(configs), log in as _YOURLARBSUSER_ and from the home directory, run:
$ `chsh -s /bin/bash`
$ `git rm -r .`
$ `rm -rf .git`

To remove the programs (larbs itself), log out and log in again to **TTY 2** as root.
\# `curl -LO https://raw.githubusercontent.com/LukeSmithxyz/LARBS/master/progs.csv`
\# `cat progs.csv | cut -d "," -f2 | sed "/N/ d; /https/ d" > progs.txt`
\# `pacman -Rs - < progs.txt`
\# `rm progs.*`	
\# `rm larbs.sh`

Then,  still logged in as root, remove some leftovers from _YOURLARBSUSER_ home directory:
- \# `rm /home/YOURLARBSUSER/.Xauthority`
- \# `rm -r /home/YOURLARBSUSER/.config/BraveSoftware`
- \# `rm -r /home/YOURLARBSUSER/.config/mpv`
- \# `rm -r /home/YOURLARBSUSER/.config/nvim`
- \# `rm -r /home/YOURLARBSUSER/.config/pulse`
- \# `rm -r /home/YOURLARBSUSER/.config/shell`
- \# `rm -r /home/YOURLARBSUSER/.config/zsh`

- \# `rm -r /home/YOURLARBSUSER/.local/share/newsboat`
- \# `rm -r /home/YOURLARBSUSER/.local/share/nvim`
- \# `rm /home/YOURLARBSUSER/.local/share/weathereport`
- \# `rm -r /home/YOURLARBSUSER/.local/share/xorg`
- \# `rm -r /home/YOURLARBSUSER/.local/share/zathura`

- \# `rm -r /home/YOURLARBSUSER/.local/src/dmenu`
- \# `rm -r /home/YOURLARBSUSER/.local/src/dwm`
- \# `rm -r /home/YOURLARBSUSER/.local/src/dwmblocks`
- \# `rm -r /home/YOURLARBSUSER/.local/src/st`
- \# `rm -r /home/YOURLARBSUSER/.local/src/mutt-wizard`

Lastly:
- \# `reboot`
