### ISSUE TITLE
installing over existing wm

### ISSUE THREAD

**Issue by dirad** [LukeSmithxyz/LARBS#337]
Ran larbs.sh after a fresh installation of Artix with KDE Plasma. 
I want to have both.
But after logging out and back in, I only have Plasma as an option. 
Trying to run st throws an error also.

How do you switch from Plasma to dwm?

Thanks.

**Comment by et-8** [comment]
LARBS is supposed to run without a display manager. KDE Plasma rekommends the display manager sddm.

To switch from Plasma to dwm you need to add dwm to your display manager.
Add an entry to your display manager's session list by creating a `dwm.desktop` file in /`usr/share/xsessions/
`
```
[Desktop Entry]
Type=Xsession
Exec=dbus-run-session /usr/local/bin/dwm
TryExec=/usr/local/bin/dwm
Name=dwm
Comment=Log in using dwm window manager.
```
More info in the Arch wiki: [https://wiki.archlinux.org/index.php/Display_manager#Session_configuration](https://wiki.archlinux.org/index.php/Display_manager#Session_configuration)

**Note: At the login screen you will have to switch to TTY 2 and install libxft-bgra-git manually.**
$ `yay -S libxft-bgra-git`
Answer j and press enter.
Then do a reboot.
$ `sudo reboot`

What error does st show? I didn't get any.

**Comment by et-8** [comment]
I haven't seen that error before.
Did you execute `yay -S libxft-bgra-git`? That program didn't got installed in my test environment although the larbs script finished without errors. This a very important package. Also run a full system update/upgrade.

Adding the dwm.desktop only shows an entry  at the login screen, you can actually add that without having larbs or dwm installed and then that entry will do nothing.

**Comment by dirad** [comment]
the dwm.desktop actually loads dwm. It is very distinguishable from plasma.
I did [re]install libxft-bgra-git, after it wasnt installed by larbs, and after i had to first install libxft-bgra, replacing libxft-bgra-git because of some error.

**Comment by josephgerth** [comment]
> LARBS is supposed to run without a display manager. KDE Plasma rekommends the display manager sddm.

Uh, am I a moron? I didn't see this tip anywhere, so I'm pretty sure I did this wrong. I'm having several small issues with configs, and I think my system is confused. I initially installed Arch (using Arch Fi) and added the desktop environment with XFCE. Perhaps this was a mistake? Should I just clean install it? Any recommendations? Thanks!
