### ISSUE TITLE
question about gnome-keyring

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/LARBS#338]
looking at my htop, i notice that gnome-keyring is not being run ... are we actually using gnome-keyring or is it safe to remove?

reading from the Arch wiki my understanding is that if we use our own xinitrc that if the files in /etc/X11/xinit/xinitrc.d are not sourced on init, that gnome-keyring features wont work?

**Comment by jemadux** [comment]
gnome keyring just to unlock gpg

**Comment by kronikpillow** [comment]
as far as im aware luke uses pam-gnupg to unlock gpg, not gnome-keyring, so im wondering if this is bloat, since it's not running at all on my system

**Comment by jemadux** [comment]
on arch the pam-gnugp works fantastic when u unlock ...

**Comment by LukeSmithxyz** [comment]
I use pam-gnupg, but not everyone wants their key unlocked automatically. I suppose I could remove the gnome-keyring, but I'll tell you it causes a lot of confusion when people don't get a password prompt they're expecting from some program.
