### ISSUE TITLE
Question about how do i generate the progs.csv file?

### ISSUE THREAD

**Issue by Juliaria08** [LukeSmithxyz/LARBS#339]
I wanted to know how do i generate that file so i can easily give my own oneliner that gets your script with my own dotfiles and everything good so it is cool and i can try it wiout needing to manualy install the programs list installing yay and running ``yay -S /mnt/usb/progs.txt`` with a progs file from usb disk

**Comment by et-8** [comment]
The **progs.csv** file is just an _ordinary text file containing a comma seperated list_. Save the file with the **.csv** extension instead of the usual **.txt**.
If you  click  on the file here in the repo and then on ´Raw` in the upper right corner you will see how it is built.

**Comment by Juliaria08** [comment]
I cloud run p -Qq >> pacman-repos.txt and then use it to install?, Because i have switched window managers
