### ISSUE TITLE
lf file manager is not working

### ISSUE THREAD

**Issue by ruokz75** [LukeSmithxyz/LARBS#341]
i can get lf file manager working on new arch LARBS  install  
i get Initializing  screen: character set not supported 
thanks

**Comment by MocktardJackson** [comment]
Hi, 
I get the same error message with a clean Artix install. 
Can't find anything online about this so I'm gessing it comes from LARBS?
Thank you.

**Comment by kronikpillow** [comment]
actually it doesn't, lf works completely fine for me, and this issue has nothing to do with LARBS which is just a Arch installer, I can feel your pain Luke bro, no wonder your ignoring all these issue reports, ppl keep constantly adding them to the wrong place lmao 😂
