### ISSUE TITLE
Question about bm-files

### ISSUE THREAD

**Issue by Walkability** [LukeSmithxyz/LARBS#342]
Does anyone know how the top files in bm-files (bf, bd, cfx, cfb) get updated automatically?  I assume it was working originally, but after changing a few things, I do not see anything updating automatically. If anyone could tell me what mechanism was used to accomplish this it would be much appreciated.

**Comment by LukeSmithxyz** [comment]
There's a script called `shortcuts` in the scripts folder that does this. Vim automatically runs this script whenever any of these files are changed.
