### ISSUE TITLE
I get kicked out of the dwm-environment - serveral issues are listed:

### ISSUE THREAD

**Issue by MrMortima** [LukeSmithxyz/LARBS#344]
Dear community,

I installed the minimal Artix Linux and let LARBS run. The autoinstall finished without a problem. Now I log out of 'root' and log in my user account - i hit startx: For a sec the dwm-environment pops up as the X server shuts down.

 On the img I took you can see the tty shell with the issue report:

![IMG_0163 1](https://user-images.githubusercontent.com/82467205/114596276-b96b3780-9c8f-11eb-952e-fdac3791186c.JPG)

I hope you can help by giving me some instructions which I can follow!

Regards,
MrMortima

**Comment by phneutral26** [comment]
Did you solve it? A friend of mine has the same issue.

**Comment by phneutral26** [comment]
Oh, turned out, install libxft-bgra-git and your good to go
