### ISSUE TITLE
how to remove font 

### ISSUE THREAD

**Issue by meimei35** [LukeSmithxyz/LARBS#346]
After i used this script all my fonts for my browser and file managers have changed how can i remove this font because i cant change it back 
![image](https://user-images.githubusercontent.com/66698460/116958387-4aaa4a00-ac4f-11eb-82c2-e1aa8cdad016.png)

**Comment by Lin2Jing4** [comment]
To [remove](https://wiki.archlinux.org/title/pacman#Removing_packages) the [ttf-linux-libertine](https://archlinux.org/packages/community/any/ttf-linux-libertine/) package, try:
```perl
pacman -R ttf-linux-libertine
```

**Comment by kronikpillow** [comment]
actually just edit .config/fontconfig/fonts.conf and change the font to one you want there, voidrice uses fontconfig custom settings to force font unification across all programs ... 

on the other side of things, this belongs to lukesmithxyz/voidrice, LARBS is just a Arch installer

**Comment by LukeSmithxyz** [comment]
It's better to edit the fontconfig.
