### ISSUE TITLE
unable to change terminal specific shortcuts

### ISSUE THREAD

**Issue by pxpqpe** [LukeSmithxyz/LARBS#347]
hey there,
this issue is very specific to terminal usage. earlier when i want to move around a currently typing command , i used to move the cursor using ' CTRL+l_arrow  '  and to move right ' CTRl+r_arrow ' , like this there are certain shortcuts replaced by this larbs installation. first i thought this was just an issue with st , and switched to another terminal to check whether its working or not. but this is replaced systemwide. i just wanna use the default keyboard shortcuts that comes with the terminal. can anyone help me how to edit the config file for this shortcut

**Comment by LukeSmithxyz** [comment]
Read the manual. LARBS uses vi mode in the shell.
