### ISSUE TITLE
why it is not possible to switch to bash using chsh

### ISSUE THREAD

**Issue by prakash2033** [LukeSmithxyz/LARBS#348]
I fail to switch to bash using chsh which i normally would in any other distro/environment

I do 'chsh' and then pass on /bin/bash. But  everytime i relaunch terminal and echo $SHELL. I still get /bin/zsh.

Where exactly its been set to default to zsh always. I had looked at zshrc, profile, almost everywhere where i think would switch it back to zsh. Is it something set on user level?

**Comment by kronikpillow** [comment]
maybe you should refference to the Arch wiki for instructions? its quite simple really

chsh -s /bin/bash ... 

or edit /etc/passwd with a text editor, and change the /bin/zsh to /bin/bash for the root and your user ... althou I dunno why you would ever do that, zsh is so much superior

**Comment by prakash2033** [comment]
I figured out that reboot was needed for this. That’s why closed the issue. Thanks for responding.
