### ISSUE TITLE
passmenu (Mod+D) pinentry did not show

### ISSUE THREAD

**Issue by jayrexacilo** [LukeSmithxyz/LARBS#349]
i have freshly installed larbs and configure my password store.
steps i have done.
- imported my gpg file.
- pass init <my imported gpg>
- pass git remote add origin my.github
- pass git pull

after that, i tried to copy my stored pass. but no pinentry window show.
what i discovered is when i restart it the pinentry shows in the black screen on restart or whatever it is called.
how to fix this?

**Comment by joalcava** [comment]
Did you fixed? I'm facing the same issue
