### ISSUE TITLE
Dunst config file keeps resetting back to defaults

### ISSUE THREAD

**Issue by mache73k** [LukeSmithxyz/LARBS#350]
Hello, I want to make some changes to dunstrc in .config/dunst, but they only apply on active session, once I restart X server the config file (dunstrc) resets back to its defaults. I think this is a LARBS related issue because I can't reproduce it on other environments.

**Comment by kronikpillow** [comment]
this is actually a voidrice related issue, LARBS is just an Arch installer, your query belongs to lukesmithxyz/voidrice ... althou this isn't happening for me
