### ISSUE TITLE
about sudoers file 

### ISSUE THREAD

**Issue by jemadux** [LukeSmithxyz/LARBS#351]
I have tried in sudoers file to change the 
wheel to my username nothing happend 

When i uncomment the 
`%wheel ALL=(ALL) NOPASSWD`
for everything don't even ask a password 

By the default the main problem when i want to update my system with 
the icon in dwmblock doesnt not do that .... any help ?
also on artix when i press the mod and enter when i reboot the system do nothing  even 
if have wheel nopassword ...

**Comment by kronikpillow** [comment]
why would you change wheel to your username? o.O who does that? and why'd you run with NOPASSWD? 

just update your system with pacman -Syu and yay -Syu ... also you have the checkup script ... and third this belongs to lukesmithxyz/voidrice ... LARBS is just a Arch installer

**Comment by jemadux** [comment]
the problem on artix i can not run the reboot comand when i press super and backspace .
