### ISSUE TITLE
artix - dunst - brave 

### ISSUE THREAD

**Issue by jemadux** [LukeSmithxyz/LARBS#352]
hello guys again ... i choosed to use artix over arch ... 
but the main pain on my ass is that brave dont use dunst ... 

any way to fix that ? 
the problem is with artix cuz on arch linux notifcations sent into dunst ...

**Comment by kronikpillow** [comment]
use this on Artix, to get Brave notifications working on Artix ... 

https://gist.github.com/kronikpillow/f0446e29c9d73886f21f294b3883c334

place it in /etc/profile.d/dbus.sh

on other side of things, you would think that Artix users would be more oriented to what and where is supposed to go ... LARBS is just a arch installer, this belongs in lukesmithxyz/voidrice

**Comment by jemadux** [comment]
> actually no, you should probably read what I'v written in the first msg, and the gist i linked, and where to place it

true but if you install the newer version of larbs will broke it

**Comment by kronikpillow** [comment]
go to brave://flags/#brave-ads-custom-notifications and set to disable if you want to use native notifications, like dunst
