### ISSUE TITLE
zsh config files don't get sourced at login

### ISSUE THREAD

**Issue by shaharbest** [LukeSmithxyz/LARBS#354]
files ~/.zprofile and ~/.config/zsh/.zshrc don't get sourced at login.

I'm using clean installation of manjaro xfce.
it has LightDM as display manager.
both files don't get sourced when I login through the display manager and not after su command.

but.... they are both *do* get sourced if I use different tty and run startx.
every thing is fine after that but return like before if I use su command to login as different user (I made shahar2 and shahar3).

**Comment by shaharbest** [comment]
I discovered it is much easier to disable the DM.
I hope I'll succeed in the near future to replace Manjaro with Arch like a chad.

**Comment by kronikpillow** [comment]
just use the larbs script installer, no need to use manjaro

**Comment by shaharbest** [comment]
@kronikpillow 
I'm worried from the manual stuff I need to do when installing arch, so as a beginner I thought it will help to start with Manjaro. I intend to install Arch when I'll gain enough confidence.
