### ISSUE TITLE
Scrolling over dwmblocks causes script elements to progressively disappear from status bar

### ISSUE THREAD

**Issue by sbucek** [LukeSmithxyz/LARBS#355]
When scrolling over the status bar, for example to change volume, then each icon/plugin starts disappearing one by one until none is left and status bar is empty. Only restarting dwm using the 'renew dwm' option brings them back. 

Could this have anything to do with the settings in .xinitrc or xprofile?

**Comment by kronikpillow** [comment]
then you should have submited a ticket to the dwmblocks repository for 1, for 2 you should have checked if this is already reported, which  it is ... and there is a merge request by a user that completely fixes the issue, but Luke for some reason hasn't accepted it ... not sure why thou
