### ISSUE TITLE
Starting dwm from GDM does not load most of the configuration

### ISSUE THREAD

**Issue by sbucek** [LukeSmithxyz/LARBS#356]
When selecting dwm and starting it from GDM using the correct user, dwm opens up empty - without dwmblocks and without any shell settings/fonts and some keybindings don't work. 

As a workaround I have to change runlevel using Ctrl+Alt+F2, manually login with the appropriate user and run startx. Is there anything wrong with my dwm.desktop in /usr/share/xsessions?  Below is my current dwm.desktop content:

[Desktop Entry]
Type=Xsession
Exec=dbus-run-session /usr/local/bin/dwm
TryExec=/usr/local/bin/dwm
Name=dwm
Comment=Log in using dwm window manager.

**Comment by kronikpillow** [comment]
LARBS isn't intended to be used with a login manager, it uses xinit instead of a login manager and yes it's true, 90% of Luke's configuration doesn't get loaded on desktops with a login manager, or systems where you installed LARBS over a already existing system

**Comment by sbucek** [comment]
Thanks for your explanations @kronikpillow! Would be great however if this could be accepted as an enhancement request to ease the jump to DWM for noobs like me.
