### ISSUE TITLE
How to change font size?

### ISSUE THREAD

**Issue by g000444555** [LukeSmithxyz/LARBS#357]
Congratulations on this fantastic utility! I am trying to switch from Manjaro-i3 to arch linux with LARBS.

I have a 4k 40 inch monitor and everything looks very tiny, not only the terminal but all the applications including Brave and IntelliJ.

I am starting a new job and cannot spend time on investigating so I decided to drop the silly question here in the hope that someone might provide an answer.

What I want to do is:

1. Determine what is the current default font and font-size across all applications (system-wide non-app specific font and font size)
2. Set the default system-wide font and font-size for the current user or the entire installation

**Comment by LukeSmithxyz** [comment]
Xresources can be used to set font size and other things consistently across programs.

In the `xprofile` file, uncomment the `xrdb` line.

Then open that `xresources` file invoked and you can add lines like `*.font: monospace:size=16` to change the font size to 16.

Or replace the `*` with `dwm` or `st` or whathaveyou to set it only for a certain program you want.
