### ISSUE TITLE
Is this compatible with gitlab ?

### ISSUE THREAD

**Issue by kmj9** [LukeSmithxyz/LARBS#367]
I have a dotfiles on gitlab (clone of voidrice) and when I replaced $dotfilesrepo and $progsfile in larbs.sh with gitlab one's 
then I  try to make new install. It starts normal but skips progsfile and don't install apps.
I replaced $progsfile with : 

[ -z "$progsfile" ] && progsfile="https://gitlab.com/USERNAME/larbs/-/raw/master/progs.csv"

Is this working with gitlab or I do something wrong ?

**Comment by TrevCan** [comment]
It should be.... maybe it's because your repo is private? as long as you have access to the link that gives you the raw file it should be fine.

**Comment by kmj9** [comment]
> It should be.... maybe it's because your repo is private? as long as you have access to the link that gives you the raw file it should be fine.

In fact my repo is private but the script asking for password so it shouldn't be a problem.
I will need to try as repo public then it should work for sure.

**Comment by LukeSmithxyz** [comment]
You'll have to change some things if you want a private repo, but yeah you can specify any git repository url and give the password on the command line look up the git documentation and change the script accordingly.
