### ISSUE TITLE
Packages not installed when runnings larbs.sh

### ISSUE THREAD

**Issue by ryaeng** [LukeSmithxyz/LARBS#368]
I recently ran the script to configure LARBS on my machine. Upon login, I noticed that a few things weren't working properly: wallpaper not set, CAPS not working as ESC, no terminal transparency, etc. 

Upon attempting to run the setbg script, I received an error that xwallpaper wasn't installed. The Arch Repositories segment at the following URL notes, "As of June 2021, all Arch repositories are disabled by default."

https://wiki.artixlinux.org/Main/Repositories

According to that link, artix-archlinux-support must be installed and then repos needed to be appended to /etc/pacman.conf. It would appear that this must be done prior to the installation of packages in larbs.sh.

**Comment by grutan** [comment]
Yeah dont know why they excluded the repos tbh, got the same problem earlier and did the same soultion. So it's not really an issue. I ran it again just fixing the pacman.conf before running larbs.sh and it went totally fine.
