### ISSUE TITLE
Mod + F2 not working (and other issues)

### ISSUE THREAD

**Issue by TrevCan** [LukeSmithxyz/LARBS#369]
Hey,  I recently installed LARBS on a newly created user but I noticed a few weird things...

- Mod + F2 (and F3 as well) does not work, only works when calling the script `~/.local/bin/tutorialvids` and when getting the file mode bits it is executable for everyone, so maybe something to do with key bindings?? Volume keys work fine, which are Fn+F2 and F3, respectively.
- Vi-mode in zsh sort of works. If i add it to `~/.zshprofie` and add `set -o vi`, and relaunch zsh it does not work for some reason. But when I execute `set -o vi` from the terminal with zsh and not from a conf file, it works for some strange reason...
- Caps lock did not change to Ctrl/Mod on default. But this is an easy fix from my standpoint, since I already had a `.Xinitrc` script that maps the Caps lock key to Ctrl/Esc.

Edit;
System Specs:
- Lenovo Thinkpad T490
  - 16 GB RAM
  - 500 GB SSD 
  - Intel i7, 8th gen
  - discrete graphics mx250

I ran `# pacman -Syu` before installing LARBS and did it on a new user.

**Comment by LukeSmithxyz** [comment]
You're using a desktop manager?

**Comment by TrevCan** [comment]
Yeah, I'm running lightDM

**Comment by LukeSmithxyz** [comment]
LARBS is arrayed by default for systems without DMs.

Your issue is that the xprofile file is not being sourced. I don't know how lightdm works, but you need to ensure that it is being run on startup/login.

**Comment by TrevCan** [comment]
Thanks, I'll check it out.

**Comment by TrevCan** [comment]
@LukeSmithxyz I'd suggest adding an entry to the FAQ section of the pdf and the readme.
