### ISSUE TITLE
Paru error

### ISSUE THREAD

**Issue by Lunatic1985** [LukeSmithxyz/LARBS#370]
Installation fails (paru)

**Comment by engjpacheco** [comment]
This happens to me some times. only re run the sh larbs.sh command and works fine for me. Try to be more specific with your issue.

**Comment by Lunatic1985** [comment]
I re-run the command several times and stil fails, paru says that there is an error installing the package, just in the beginning of the installation.

**Comment by Lunatic1985** [comment]
I already tried and the same thing happens, the script tries to install that package anyway, I'll wait until luke fixes the problem, thanks

**Comment by LukeSmithxyz** [comment]
Not sure what to do with this assuming it is what I think it is.

paru sucks and breaks and can't handle errors as well as yay can.

When I have some time, I'll troubleshoot it and change the paru commands or replace them with a better AUR helper (I adopted paru flippantly without too much testing as yay is less maintained).

I haven't had the chance to test LARBS at all recently.

**Comment by Lunatic1985** [comment]
My network is fine, anyway I'll wait for the fix, I guess there is a better alternative to paru  :)

**Comment by engjpacheco** [comment]
Ok, luck buddy, regards from Mexico

**Comment by kronikpillow** [comment]
Works completely fine for me, installed LARBS yesterday, paru takes some time to build thou, as LARBS is not using the paru-bin, instead it builds from source

**Comment by LukeSmithxyz** [comment]
Yeah I might have the binary version installed. The compilation might be an unnecessary step. I'll figure it out.

**Comment by engjpacheco** [comment]
hi, I personally try this latest version of larbs with yay, and the installation was faster than the paru.
