### ISSUE TITLE
How do I change keyboard shortcuts?

### ISSUE THREAD

**Issue by jaydoc** [LukeSmithxyz/LARBS#375]
I installed Brave browser to Firefox and want to map mod + w to Firefox but am having trouble finding the file I need to edit to get this done. 

Any help would be appreciated. Thanks.

**Comment by TheYellowArchitect** [comment]
Super+F1 covers a lot of the basics, including configuration

All program/executable shortcuts via keys are in this path:
~/.local/src/dwm/config.h

Should be around line 162, pretty much replace the " -e brave" with "firefox" or whatever executable you use to launch firefox from the terminal, hope this helps :)

**Comment by jaydoc** [comment]
I managed to get it done differently. 

Edited the line 

export BROWSER="brave" 

to

export BROWSER="firefox"

~/.zprofile

Logged out and back in and now mod + w opens firefox without having to edit the dwm config file or recompiling it. 

Hope that doesn't cause any unintended consequences!
