### ISSUE TITLE
How do I search files?

### ISSUE THREAD

**Issue by TheYellowArchitect** [LukeSmithxyz/LARBS#376]
There is no 'locate' or 'updatedb' command in the terminal
And in lf (file manager), I do not know how to search recursively

**Comment by anntnzrb** [comment]
You mean literally searching for files...? Perhaps [find(1)](https://man.openbsd.org/find).

```sh
$ tree ~/.local/resources/

...
├── boxes-demo.txt
├── emoji
└── utf8-demo.txt
```

```sh
$ find ~/.local/resources/ -iname '*demo*'

~/.local/resources/boxes-demo.txt
~/.local/resources/utf8-demo.txt

```

**Comment by TheYellowArchitect** [comment]
I didn't know about the `tree` command, that's impressive. Doing `tree | grep "test.txt"` works but it's kinda bloated hahaha

The second command seems to work, `find -name 'test.txt'', thank you for this, it will certainly save me time in the terminal.
Though I have a question - I read the manual (it seems kinda outdated, as -d is deprecated), what is the difference of -iname and -name?

Slightly off-topic from the above, I won't close the issue, since I'm trying to understand how to search via the lf file manager, pressing `:!find name` and then redirecting to an entirely different screen instead of going there seems bloated
