### ISSUE TITLE
yay-bin causing install to stop

### ISSUE THREAD

**Issue by HiddenSquid321** [LukeSmithxyz/LARBS#382]
Whenever i run the install script ittries to install yay-bin but then it gives the error it couldn't install the AUR helper and then ends the installation iv'e tried removing yay from my system it doesn't seem to make a difference this error always seems to occur

**Comment by HiddenSquid321** [comment]
I removed the manual install() function from the install script and everywhere where it was called that fixed the issue but of course that is only a temporary fix

**Comment by Preetpal123** [comment]
It still doesn't work for me. Shows the same error "Failed to install AUR helper"

**Comment by Socerest2** [comment]
I have the same thing

**Comment by HiddenSquid321** [comment]
Yup I put in a pull request with a potential fix for the problem

**Comment by rbledsaw3** [comment]
The solution is to change `yay-bin` on line 194 to `yay`

I'll make a pull-request to change this.
