### ISSUE TITLE
Input devices unresponsive

### ISSUE THREAD

**Issue by joalcava** [LukeSmithxyz/LARBS#385]
I did a fresh install of arch and installed LARBS, the user session starts correctly, it displays the wallpaper and the mouse cursor is shown in the screen but it wont move, keyboard input also does not have any effect.
I can see the system is not dead because there are some numbers moving in the top bar and the time also updates correctly, it seems like its just the input devices that dont work.

**Comment by lukerb52** [comment]
Having the same issue on my LARBS laptop. everything works when on a live USB, and even logging in, but no input works once logged in, not even ctrl-alt-f2. The clock still ticks so I know that it is not frozen.
