### ISSUE TITLE
How to display all tabs?

### ISSUE THREAD

**Issue by Beni9889** [LukeSmithxyz/LARBS#386]
Hello, I'm quite new to larbs, and I'm wondering if there's a way to display all tabs all the time, because it's quite annoying if I have a designated workspace for everything

**Comment by krisdoodle45** [comment]
Use Super+0

**Comment by Beni9889** [comment]
That works but I'm looking for a solution that is permanent.

**Comment by LukeSmithxyz** [comment]
Uh... then just use one workspace...
