### ISSUE TITLE
Brave installation can be replaced from aur to universe repo

### ISSUE THREAD

**Issue by notreallydust** [LukeSmithxyz/LARBS#389]
There is a repo with extra packages (universe.artixlinux.org), brave can simple be installed with pacman -S brave-bin.

**Comment by LukeSmithxyz** [comment]
Okay. This must be new. I'll add it soon.

**Comment by LukeSmithxyz** [comment]
Actually, it looks like this is not actually in Arch yet, so I'll wait on that.

**Comment by notreallydust** [comment]
> Actually, it looks like this is not actually in Arch yet, so I'll wait on that.

In fact, it is only for Artix Linux, it can work for Arch Linux, but you MUST not touch or install any -runit or -s6 or -openrc, and the recent suite66, it can break arch linux

**Comment by notreallydust** [comment]
> Okay. This must be new. I'll add it soon.

https://wiki.artixlinux.org/Main/Repositories, you can read more there
