### ISSUE TITLE
Failed to install AUR helper.

### ISSUE THREAD

**Issue by jdial1** [LukeSmithxyz/LARBS#393]
On a fresh boot of a Arch Linux usb drive, the script fails with the error 'Failed to install AUR helper.'

**Comment by sophronesis** [comment]
Same problem, pacman update didn't help

**Comment by jarodvip** [comment]
Same problem

**Comment by MatiasLoiseau** [comment]
Same problem here ! With Manjaro i3 version

**Comment by MatiasLoiseau** [comment]
I tested with @Jberczel fix and i had the same problem

**Comment by Jberczel** [comment]
@MatiasLoiseau, @sophronesis, @jarodvip - that fix worked about two months ago when I did a fresh install.  Something else may have changed since then.  If I have some time this week, I'll try another fresh install and report back here.

**Comment by MatiasLoiseau** [comment]
Ok, thank you !

**Comment by Shido20** [comment]
@Jberczel , Any updates? I tried installing on a fresh arch install and it stops after displaying the error message: Failed to install AUR helper.

**Comment by ivory-security** [comment]
Hey! 

Mine failed in 4 different installs of different systems. That's when I realized I might be the dumb one, and decided to read through the script. It worked flawlessly once I tried it under sudo privileges. Go to your terminal, type `visudo` and edit the `%wheel` lines to allow privileges to users. 

Might be overkill, but just to be sure I ran the script with root by typing `su root` before running. Anyways, after that it worked like a charm in 2 different distros. Best of luck to your guys.

P.S.: Check line nº 196 to 198 of the script!

>#Allow user to run sudo without password. Since AUR programs must be installed 
#in a fakeroot environment, this is required for all builds with AUR. 
newperms "%wheel ALL=(ALL) NOPASSWD: ALL"

P.P.S.: Here's an useful [link ](https://www.vultr.com/docs/create-a-sudo-user-on-arch-linux/) to newbies like me!

**Comment by Shido20** [comment]
@ivory-security 
I just removed all lines containing 'AUR-helper' form the script; been using the rice for almost two months and no issues. 
I think your method might be more elegant though, so I'll keep it in mind next time I install the rice.

**Comment by M-Arnone** [comment]
Hey, 
I had the same error and I resolve it by simply doing this 
`
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si PKGBUILD
`
Then re-run the script with 
`
sudo sh larbs.sh
`
