### ISSUE TITLE
Not able to change default browser

### ISSUE THREAD

**Issue by VG08** [LukeSmithxyz/LARBS#402]
Hey so I want to change the default browser to firefox form brave, when I open the config.h file in rr. I see that the only 2 mentions of BROWSER are only to call it and I can't seem to find where it is defined to change it, could anyone tell where it is defined?

**Comment by pakudev** [comment]
`BROWSER` variable is defined in `.config/shell/profile`. You can change it to whatever you want and relogin for changes to take effect.

**Comment by VG08** [comment]
ok it worked thanks
