### ISSUE TITLE
the -p flag seems to be broken

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/LARBS#405]
recently i tried installing larbs with the -p flag so that i can use brave-bin instead of brave package, and to auto install some things that i find as missing dependencies of larbs and it's scripts, and when running with the -p flag what happens to me is that LARBS just quickly jumps trough the loop, and doesn't install absolutely anything

**Comment by pakudev** [comment]
I too had this problem, but the workaround that I did was fork all the necessary repos and change the `progs.csv` file and dotfiles repo in `larbs.sh` to point to my forked dotfiles. It worked, but I am not using LARBS anymore.
