### ISSUE TITLE
Problem installing libxft-bgra-git

### ISSUE THREAD

**Issue by grantusaus** [LukeSmithxyz/LARBS#409]
I see there were issues surrounding this package raised before. In the last few months I've had no issues with the larbs install script but recently was trying to install for a friend and noticed that the script starting hanging on this package. This meant the install script would not complete.

I commented out the line for this package and the script now completes. Afterwards I tried to install manually using
```
yay -S libxft-bgra-git
````
which returns
```
-> Cloning libxft git repo...
Cloning into bare repository '/home/user/.cache/yay/libxft-bgra-git/libxft' ...
```
And this too is hanging without completing.

This seems to be causing an inability to startx into dwm on login either manually or automatically. Just wondering if anybody else has seen this problem lately?

**Comment by L8nighter88** [comment]
Same issue. Fresh arch linux install from 20 minutes ago.

**Comment by L8nighter88** [comment]
Did your friend install arch manually?

**Comment by grantusaus** [comment]
> Did your friend install arch manually?

I was installing on his laptop for him as I'm more familiar with the install. I was installing Artix rather than Arch.

I just tried again and figured I'd wait a really really long (around 1 hr). It finally worked it just took a very long time. I had originally only libxft installed (not libxft-bgra) and it would load quickly to desktop then crash. libxft-bgra getting installed removes libxft as it conflicts and now allows me to boot to desktop.

I just found it strange that it took so long to download, install and clean up this package.

**Comment by L8nighter88** [comment]
Issue solved. Patience is always the answer.

**Comment by L8nighter88** [comment]
Disregard my previous comment. Just got on a fresh install of arch and it's the same problem again. Been sitting on installing libxft bgra for an hour already.

**Comment by SikkiLadho** [comment]
I am having the same problem, how much did it take for you?

**Comment by Akhilkrishnauk** [comment]
guess what.. Im getting the same issue.. I figured out that the issue isnt in yay's side since it downloads the things that is required to install. its that for some random reason this person's gitlab wont clone. I tried running just the curl command thats in the PKGBUILD code and that works on linux, but the git clone doesnt. I tried the git clone on my macbook and it seems to be able to clone just fine.. but on linux it just refuses to do so. I am indeed very confused.

**Comment by LytixDev** [comment]
> guess what.. Im getting the same issue.. I figured out that the issue isnt in yay's side since it downloads the things that is required to install. its that for some random reason this person's gitlab wont clone. I tried running just the curl command thats in the PKGBUILD code and that works on linux, but the git clone doesnt. I tried the git clone on my macbook and it seems to be able to clone just fine.. but on linux it just refuses to do so. I am indeed very confused.

It also takes ages to clean up, so it's not just an issue with gitlab. In fact, just clone the repository with git and it's instantaneous. The libxft-bgbra repo in the AUR is flagged as out of date.

**Comment by Zeftax** [comment]
I am stuck on this as well, but it is true that I am installing on an HDD, so I am happy to hear its just a prpblem of not being patient enough and I will go to sleep now. If its still not installed it n 3 hours, I will write here, because I doubt that much time could be caused by HDD. But it is after midnight already so imma go sleep now gn.

**Comment by Zeftax** [comment]
Yes, Waiting does fix it.

**Comment by SikkiLadho** [comment]
I had to wait for 45 minutes, and larbs finally did it.

**Comment by MDCHAMP** [comment]
Same issue, fresh ARCH and LARBS hangs as you describe. I left the LARBS script running with the libxft-bgra lines in and the script managed to complete overnight but the libxft-bgra was not installed when it finally finished. 

Now trying yay -S libxft-bgra-git  as above and will comment what happens. 

As reported above, also unable to start dwm (crashes after ~5 seconds).

**Comment by Akhilkrishnauk** [comment]
> Same issue, fresh ARCH and LARBS hangs as you describe. I left the LARBS script running with the libxft-bgra lines in and the script managed to complete overnight but the libxft-bgra was not installed when it finally finished. 
> 
> Now trying yay -S libxft-bgra-git  as above and will comment what happens. 
> 
> As reported above, also unable to start dwm (crashes after ~5 seconds).

The dwm crash is due to the emojis in dwmblocks. It installed for me after waiting a really long time. So what i did was that I installed that package with the `yay --sudoloop -S libxft-bgra-git` command to stop it from asking for sudo password again and i went to sleep. When i woke up it was all installed.

**Comment by MDCHAMP** [comment]
Just as I was reading your comment I noticed that I had timed out of a password request.... 

Thanks for the tip! I'll try it now and let you know how I get on.

**Comment by SikkiLadho** [comment]
> Just as I was reading your comment I noticed that I had timed out of a password request.... 
> 


If you just let larbs do it, it won't cause timed out password request issue. It will take the same time.(30-60 minutes)

**Comment by MDCHAMP** [comment]
`yay --sudoloop -S libxft-bgra-git` worked after about 3 minutes :) Thanks again for the tip!

> If you just let larbs do it, it won't cause timed out password request issue. It will take the same time.(30-60 minutes)

Its odd because larbs completed overnight yesterday but the libxft-bgra install was missing?

**Comment by dassi** [comment]
I think the root problem is on a failure of the gitlab installation running at https://gitlab.freedesktop.org/. I have seen a temporary warning message on that freedesktop site, which says that some repos have https issues. libxft-bgra-git tries to clone from the original libxft source, but that fails. I can not even clone that repo directly with git, like this:

`git clone https://gitlab.freedesktop.org/santilococo/libxft-bgra.git`

It just waits forever. Seems like we are trapped. I tried randomly some other repos at gitlab.freedesktop, some work, some not. Very strange.

**Comment by dassi** [comment]
... followup, found the "official" issue for the gitlab connectivity problems: https://gitlab.freedesktop.org/freedesktop/freedesktop/-/issues/407

**Comment by dassi** [comment]
Just for the record, if someone meanwhile tries to find a dirty solution:

It seems, that freedesktop is running an alternative git server instance (maybe deprecated) at cgit.freedesktop.org.

Here my (hopefully soon obsolete) dirty workaround for the line in larbs which installs libxft-bgra-git. I get the PKGBUILD, bravely tweak libxft to the alternative git URL (tiny case sensitive difference, bloody hell), and then make the package.

```
pushd /tmp
sudo -u $name yay --noconfirm --needed -G libxft-bgra-git
pushd libxft-bgra-git
sed -i "s/https:\/\/gitlab.freedesktop.org\/xorg\/lib\/libxft.git/git:\/\/cgit.freedesktop.org\/xorg\/lib\/libXft.git/" PKGBUILD
sed -i "s/_dir=libxft/_dir=libXft/" PKGBUILD
makepkg
makepkg --install
popd
popd

```

**Comment by timbeach** [comment]
I'll throw in my hat 🤠 and say that waiting it out solved it here 🙇

**Comment by LukeSmithxyz** [comment]
Jeez this is annoying. The fix really needs to be merged so we stop having to use this broken build.

Just posting so people know I am aware of this. Not much I can do about it now, but I might do something like the  *ad hoc* sed fix above if needbe.

**Comment by pakudev** [comment]
Hey, for people using the [chaotic-aur](https://aur.chaotic.cx/) repo it is very easy to fix this problem. You just install `libxft-bgra` from [that repo](https://pkgs.org/download/libxft-bgra), it doesn't compile from source instead you get the binary package built on their servers. I know this can be a security issue for some people, but it worked for me ✌️

**Comment by LukeSmithxyz** [comment]
I ran LARBS yesterday and everything, including the installation of this package worked without error or change. That's all I can say.

Looks like it is that the host screwed their DNS or SSH or git up or something. I'm going to close this issue because although this is greatly impeding use of LARBS, it's definitely not a LARBS problem and the onus is on them to solve it.

If they don't solve it, eventually I might have to mirror the git repo elsewhere and use that.

**Comment by nonetrix** [comment]
Same here just ended up going into another tty and typing ```killall yay``` and that seemed to bypass it
