### ISSUE TITLE
sxiv is abandoned, consider moving to nsxiv

### ISSUE THREAD

**Issue by johndovern** [LukeSmithxyz/LARBS#410]
Pretty much the title. [Here](https://github.com/muennich/sxiv) is the github page for sxiv, it is archived. [Here](https://github.com/nsxiv/nsxiv) is the github page for nsxiv. It works with your key-handler.

**Comment by LukeSmithxyz** [comment]
If given a choice, I'd prefer to use programs in the main repos, as opposed to AUR programs. When nsxiv is added to the main repos, I will happily set it as default if there are principled reasons to.

I wish they would've renamed this program to something more effable when forking it.

**Comment by 2084x** [comment]
fyi nsxiv is now in the extra repo
https://archlinux.org/packages/extra/x86_64/nsxiv/

**Comment by LukeSmithxyz** [comment]
Thanks for the notice. I will switch it all over now.
