### ISSUE TITLE
passmenu (Mod+D)

### ISSUE THREAD

**Issue by ralphaaa** [LukeSmithxyz/LARBS#413]
https://github.com/LukeSmithxyz/LARBS/issues/349

This issue was closed without a fix and I am experiencing the same issue.  After using mod+D and making a selection nothing happens.  When I leave dwm (mod+backspace) and exit to BASH...or is it zsh, or the command line (kek)? I see the prompt to enter my GPG password displayed.  

How mod+D works for me.  If I run pass -c somepassword in st, st will prompt for my GPG password.  While this is stored in the cache mod+D will work.  I could increase the time the GPG password is stored in the cache so this is less of an issue.

This is not an elegant solution however and I'm not sure where to even start trying to solve this.  Any help would be appreciated.

Cheers

**Comment by ayham291** [comment]
i think you mean your gpg pinentry program is the tui one.
in this case you can change your `~/.gnupg/gpg-agent.conf` and change the pinentry programm.

i use this option `pinentry-program /usr/bin/pinentry-gtk-2` in my `gpg-agent.conf` and a popup same as the one seen in lukes videos will prompt you to unlock your keys. for more options: [GnuPG ArchWiki - Pinentry](https://wiki.archlinux.org/title/GnuPG#pinentry)

also you should add `export GPG_TTY=$(tty)` in your `bashrc/zshrc`... i dont know if it is necessary but the wiki suggested it 

if you want for it to unlock your gpg keys on login:
1. your user password and the gpg key passphrase should be the same
2. get [pam-gnupg-git](https://github.com/cruegge/pam-gnupg) also seen/heard in a video from luke [PASS: a Password Manager & Two Factor Authentication (OTP) with no Cell Phone](https://www.youtube.com/watch?v=sVkURNfxPd4)
3. add `allow-preset-passphrase` to `gpg-agent.conf`

i think that should be all you have to do... hopefully this was what you were looking for :+1:

**Comment by ralphaaa** [comment]
Amazing, that did the trick.  Thanks!
