### ISSUE TITLE
Error says to use paru despite paru not being installed

### ISSUE THREAD

**Issue by nonetrix** [LukeSmithxyz/LARBS#414]
Sorry too lazy to take a real screenshot here is a old school screenshot
![PXL_20220110_231318010](https://user-images.githubusercontent.com/45698918/148853447-a5f13cd3-95f3-4b4b-8cff-624f3ae0a659.jpg)

**Comment by ayham291** [comment]
this is just an echo statement... i dont know why it has been changed from yay.

it doesnt matter since you can get it form yay as you already have done :+1:

**Comment by nonetrix** [comment]
Was able to find the code that prints this
https://github.com/LukeSmithxyz/voidrice/pull/1063
