### ISSUE TITLE
Color Conflict

### ISSUE THREAD

**Issue by josephgerth** [LukeSmithxyz/LARBS#415]
I'm having some issues getting the colorscheme to deploy correctly.
![pic-full-220110-1740-13](https://user-images.githubusercontent.com/66454240/148856034-ceace325-1d15-4596-8f26-650b3e8f302e.png)
On the left is the default, what I get when I login. On the right is what it should be.

Weirdly, if I open Vim and type `:color gruvbox`, I get the following hideous colors (light mode maybe, but horrible). I have to type in  `:color blue` first, and then I can type in the command to get the acceptable colors.
![pic-full-220110-1748-09](https://user-images.githubusercontent.com/66454240/148856868-cee229fe-ca76-4744-8f96-080df182687c.png)

I think the only thing I've changed in st is the transparency. I change some font sizes, since I have a 4K screen. Other than that, everything _should_ be default.

Any ideas? Thanks for your time.

Edit: I should add, I do not use pywal.

**Comment by ayham291** [comment]
i would suggest you use `Plug 'gruvbox-community/gruvbox'` and set `colorscheme gruvbox` in your init.vim

`gruvbox-community/gruvbox` is maintained and also works for me :)
