### ISSUE TITLE
Setbg doesn't work with at and cronjobs

### ISSUE THREAD

**Issue by ZulluBalti** [LukeSmithxyz/LARBS#416]
When I type this command in the terminal

`setbg /usr/share/backgrounds`

it works fine it randomly selects a picture, 

But when I try to use the same command using at and cronjob the background (wallpaper) isn't changing even tho the command is executing. I can also see that the link in /home/$USER/.local/share/bg is pointing to a new image but for some reason the wallpaper isn't updating

**Comment by LukeSmithxyz** [comment]
Closing this. Interesting issue, but the only way to solve it is by hackily getting the DBUS_SESSION_BUS_ADDRESS and perhaps other variables from some other process.
