### ISSUE TITLE
Allowing user to skip installing some programs using checklist

### ISSUE THREAD

**Issue by DusanLesan** [LukeSmithxyz/LARBS#417]
Are you interested in PR with code allowing user to see full list of programs from progs.csv before starting install process and allowing him to unselect unwanted programs?
The code is here https://github.com/DusanLesan/LARBS-1 until this issue is closed
It looks like this:
![pic-selected-220118-1059-08](https://user-images.githubusercontent.com/20520590/149919592-0c0e0fba-894f-464d-86d8-9ed287199f0f.png)

**Comment by kronikpillow** [comment]
this would actually be great, then we could include optional packages in the list ... as LARBS does come installed with some missing dependancies towards Luke's dotfiles
