### ISSUE TITLE
Fatal: not a git repository

### ISSUE THREAD

**Issue by hexcase** [LukeSmithxyz/LARBS#422]
I get a 
"Fatal: not a git repository (or any of the parent directories): .git
Failed to install AUR helper"
while running the larbs script.
I did try the pacman -Sy but it doesn't seem to fix it

**Comment by kztr** [comment]
I also had this issue, it seems to be a permissions problem. I fixed it by moving the script from `/root` to `/`.

**Comment by BDaddyTech** [comment]
> I also had this issue, it seems to be a permissions problem. I fixed it by moving the script from `/root` to `/`.

Thanks this worked for me also.
