### ISSUE TITLE
Failed to install AUR helper

### ISSUE THREAD

**Issue by Arbiterz** [LukeSmithxyz/LARBS#428]
sh larbs.sh 8.15s user 4.19s system 6% cpu 3:16.51 total when trying to install larbs.

**Comment by rustombhesania** [comment]
I'm also getting the error

**Comment by Lafixin** [comment]
Same. Please fix

**Comment by Lafixin** [comment]
Even after manual installation of yay it still fails on this step. About 2 hours ago larbs didn't stop on this step, and AUR helper installed fine. Something wrong on AUR side?

**Comment by moaazelsayed1** [comment]
This worked for me! https://github.com/LukeSmithxyz/LARBS/issues/393#issuecomment-1041540567

**Comment by romariorobby** [comment]
adding `git -C "$repodir/$1" in [manualinstall](https://github.com/LukeSmithxyz/LARBS/blob/master/larbs.sh#L93) function seems to work for me. 
```
sudo -u "$name" git -C "$repodir/$1" clone --depth 1 "https://aur.archlinux.org/$1.git" "$repodir/$1" # adding `git -C`
```

**Comment by xulepa** [comment]
I'm still having issues with the AUR helper, when using the rice. Tried the sudo suggest here https://github.com/LukeSmithxyz/LARBS/issues/393#issuecomment-1041540567 . Does someone has the same problem?

**Comment by whatsogingon1** [comment]
> I'm still having issues with the AUR helper, when using the rice. Tried the sudo suggest here [#393 (comment)](https://github.com/LukeSmithxyz/LARBS/issues/393#issuecomment-1041540567) . Does someone has the same problem?

yeah same
