### ISSUE TITLE
Shutdown and reboot scripts wont run (mod+backspace menu).

### ISSUE THREAD

**Issue by marciomaiajr** [LukeSmithxyz/LARBS#430]
By default, on a brand new larbs instalation (arch), the shutdown and reboot scripts, which are activated by the the mod+backspace menu, won't run.

I just instaled the polkit package and it fixed the problem. Aparently, the sysact script (.local/bin/sysact) tries to run the systemctl reboot/poweroff command, but it just fails silently.

I don't know if it's just a case of including the polkit package in the csv file or to have a fallback reboot/shutdown command for arch linux installs.

Best regards.

**Comment by kronikpillow** [comment]
yes i have the same problem on arch, had to install polkit to solve it .. i'm using the gnome one ...

**Comment by permafrost06** [comment]
Same problem on arch on virtualbox. polkit solves it. I guess this has something to do with permission and how the user is set up?
