### ISSUE TITLE
Why yay and not paru

### ISSUE THREAD

**Issue by se7en-x230** [LukeSmithxyz/LARBS#431]
I guess I can edit the install script and replace yay with paru?

**Comment by LukeSmithxyz** [comment]
Because paru sucks and breaks and can't be trusted to be run in the background. I don't know of all the 100 different AUR helpers, people always want this one.

There was a week or two when I acquiesced and made paru the default AUR helper, but everything was constantly failing to install.

**Comment by se7en-x230** [comment]
Thanks for the heads up.

Yay is not maintained anymore if I am not mistaken that's why I  switched to paru and never oncer had a problem

Replacing yay with XYZ helper after the install is not a problem anyway. I was just curious.

Amazing setup by the way. I run your labs on 3 computer since many years and customized it further.

Thanks for the work.
