### ISSUE TITLE
Can't launch any based programs after reinstallation

### ISSUE THREAD

**Issue by Lafixin** [LukeSmithxyz/LARBS#439]
So I messed up, as I guess, some libs when was trying to make some cli python-based program work, and after that I was getting errors about libs and, for instance, my mpd daemon stopped to work and also other things. So I decided to reinstall Arch, saving only home partition and recreating others following Luke's instruction. I installed LARBS now, but even zsh terminal doesn't launch, just like lf, mpv (only if I watch tutorials from "Mod+F2" menu), ncmpcpp and so on, only dmenu, Brave and zathura work fine. So what should I do to make it works?

**Comment by Lafixin** [comment]
Ok, I installed Artix instead and now it works fine somehow...

**Comment by Lafixin** [comment]
Does it matter which installation I do: BIOS or UEFI? Idk what I'm doing wrong....

**Comment by LukeSmithxyz** [comment]
Error was that st had not been installing after a git update. Should be fixed now.
