### ISSUE TITLE
When Mounting External SSD DMENU No Longer Works

### ISSUE THREAD

**Issue by NoStepSnek** [LukeSmithxyz/LARBS#446]
Just as the title says, once mounted via Super + F9, Super + D no longer works... along with a handful of other Super + " " commands. This forces a restart as I cannot open a terminal once DMENU is inoperable.

**Comment by anntnzrb** [comment]
Weird behavior, this belongs at [voidrice](https://github.com/LukeSmithxyz/voidrice) though.
