### ISSUE TITLE
Key bindings typo in a Mod+F1 manual

### ISSUE THREAD

**Issue by SleepingCat1** [LukeSmithxyz/LARBS#448]
Mod+F12 - Rerun ***kayboard*** mapping scripts if new keyboard is attached

**Comment by i-c-u-p** [comment]
the typo seems to be here: https://github.com/LukeSmithxyz/dwm/blob/master/larbs.mom#L220=
(pdf version: https://larbs.xyz/dwm.pdf)
i'll make a PR to fix it

**Comment by i-c-u-p** [comment]
> i made a [PR](https://github.com/LukeSmithxyz/dwm/pull/197) to fix it

it's merged, so this issue can be closed
