### ISSUE TITLE
Driver promt / location 

### ISSUE THREAD

**Issue by Drunkenpanda2000** [LukeSmithxyz/LARBS#45]
It's weird that i was't asked what driver i want to use.
Might you perhaps add a dialogue option ?

**Comment by LukeSmithxyz** [comment]
A driver? What do you mean? A driver for what?

**Comment by Drunkenpanda2000** [comment]
The driver wich i am referring to is the video card driver.
check if nvidia or amd

then ask Nouveau or propreitairy nvidia driver.

And download driver accordingly / use adjusted config files.


(Ok i diden't mean to react with a heart emoji and no reply it ws just becouse it was unclear in terminal browser how to react.)

**Comment by LukeSmithxyz** [comment]
If someone pushes a quick test to determine what video card driver is needed, I'll merge it, but I don't particularly know how to determine which one is appropriate for everyone's computer.

**Comment by Drunkenpanda2000** [comment]
i have the made some code but the final part is failing (if and is not working) also right now it only works for newer gfx cards. 
Can you five me push acces ?  i'd like to learn more about linux and expand uppon your work.

```
#!/bin/sh

#currently only works for relativly new models.

#function calling


#maybe more options with older drivers but i wanted to also just make it check automatically.
Option1="Empty"
Option2="Empty" 
Driver="Empty"
Card="Empty"
 
if lspci | grep -q NVIDIA; then
	 gfxa+=("Nvidia")
 else
  Option1="Proprietary NVIDIA driver"
  Option2="Open source nouveau driver"
  Card="Nvidia"
elif lspci | grep -q Amd; then
	 gfxa+=("Amd")
 else
  Option1="Proprietary Catalyst driver"
  Option2="Open Source AMDGPU driver"
  Card="Amd"
elif lspci | grep -q Intel; then
	 Driver="xf86-video-intel"
 else
 	echo It can not be!
fi

echo $Option1
echo $Option2

 cmd=(dialog --separate-output --checklist "Select Gfx driver using space:" 22 76 16)
 options=(1 "$Option1" on    # any option can be set to default to "on"
          2 "$Option2" off)
 choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
 clear
 for choice in $choices
 do
     case $choice in
         1)
             echo "First Option"
             selection="1"
             ;;
         2)
             echo "Second Option"
             selection="2"
             ;;
     esac
done

if [ Card="Amd" && selection="1" ];
  echo Catalyst
  install="Catalyst"
elif [ Card="Amd" && selection="2" ];
  echo AMDGPU
  install="AMDGPU"
elif [ Card="Nvidia" && selection="1" ];
  echo NVIDIA
elif [ Card="Nvidia" && selection="2" ];
  echo nouveau
else echo you found a bug

# pacman -S $install

```

**Comment by NonsenseBearer** [comment]
this code never install the intel driver, because you don'nt use the var Driver in the pacman -S at last

**Comment by NicTanghe** [comment]
@kaizetsubaki  i didn't really care about intel drivers yet.
Also, the script simply didn't work.

@LukeSmithxyz Did u close because u fixed or because of inactivity on my part ?
I ended up manually installing it at the time.
And later switched to windows now i wanna dual boot but lost a lot of my know-how.
