### ISSUE TITLE
Weird square after some emojis dwm

### ISSUE THREAD

**Issue by Inlife-raphael** [LukeSmithxyz/LARBS#459]
Hello,

I installed LARBS mostly successfully but the `shutdown` and the `renew dwm` emojis have a weird square after them. It's in DWM only, on `st` it's mostly well-shown even though the space after shutdown is already messed up. (`neovim`, `bat` and `cat`)

I've relaunched the LARBS script but not reinstalled it from scratch.

I've downloaded Voidrice by myself to overwrite again `~/.local/bin/sysact`.

Little remarks: `bat` shows some `~` around the lines that have those bugged emojis, reading `sysact` with Python shows that there are 6 bits rather than 4 and the script still works even though he has a buggy display

**Comment by kronikpillow** [comment]
install ttf-dejavu to remove the weird squares

**Comment by kronikpillow** [comment]
I dunno why,  but installing that font fixes the issue

**Comment by Inlife-raphael** [comment]
That fixed the issue before I even restart DWM! Thanks!

**Comment by kronikpillow** [comment]
yes, but i still am unable to figure out why that font solves the issue ... i havenot noticed anything specific in /etc/fonts/conf.d/ that would make the emojis display differently after installing the font ... i mean sure, the font installs some settings there to conf.d but ... still, unable to figure our which part actually solves the issue
