### ISSUE TITLE
Change AUR helper

### ISSUE THREAD

**Issue by alexjj** [LukeSmithxyz/LARBS#47]
Packer is listed as discontinued/problematic on the Arch wiki: https://wiki.archlinux.org/index.php/AUR_helpers#Discontinued_or_problematic

I’d suggest changing to something like yay.

**Comment by waltsims** [comment]
I agree... I installed after the fact.

**Comment by Drunkenpanda2000** [comment]
Or Aurman

**Comment by LukeSmithxyz** [comment]
Yeah since some other `packer` package was added to the main repo causing conflicts, I should do this. I'll decide which I like most and push the changes soon.

**Comment by LukeSmithxyz** [comment]
I've now changed the aurhelper to yay.
