### ISSUE TITLE
libxft-bgra-git build fails

### ISSUE THREAD

**Issue by tmp-412** [LukeSmithxyz/LARBS#471]
The `libxft-bgra-git` AUR package uses an outdated patch, so the build currently fails.

It seems that support for BGRA glyphs has FINALLY been [merged](https://gitlab.freedesktop.org/xorg/lib/libxft/-/merge_requests/12), so current workarounds are waiting for a new libXft release or creating a `libxft-git`PKGBUILD.

**Comment by LukeSmithxyz** [comment]
Man, if they finally merged this it will be such a massive relief when it starts hitting distros. Wow. Literally years of waiting for this...

In the meantime, yeah everything is broken lol. The onus is on Arch/Artix to get this out quick or on someone, as you said, making a new updated AUR PKGBUILD.

**Comment by tmp-412** [comment]
Yeah it was a huge annoyance, since the build fails every now and then so LARBS can't even be installed.

Arch updates packages when the developers release a new stable version, so in the case of libXft it can take months. If somebody could write up a PKGBUILD and publish it in the AUR with the aforementioned name, that would be nice :P

**Comment by navapk** [comment]
I solved it on my arch machine, by manually cloning it and installing it from there.

Here are the steps I did

1. `git clone https://gitlab.freedesktop.org/xorg/lib/libxft.git`
2. `cd libxft`
3. `sh autogen.sh --sysconfdir=/etc --prefix=/usr --mandir=/usr/share/man`
4. `sudo make clean install`

And it's done, refresh your dwm and it will just work.

**Comment by misopog** [comment]
is there a way to do it at startup ?

**Comment by navapk** [comment]
@misopog It's just one time setup.

**Comment by budRich** [comment]
https://aur.archlinux.org/packages/libxft-git

**Comment by tmp-412** [comment]
Appreciate it!

**Comment by tmp-412** [comment]
@LukeSmithxyz in the voidrice repo the shell profile file still warns if you haven't installed `libxft-bgra`, so see [this PR as well](https://github.com/LukeSmithxyz/voidrice/pull/1145)

**Comment by tmp-412** [comment]
@LukeSmithxyz it seems that you can't use the `--noconfirm` flag in pacman if there's a package conflict, so the `libxft-git` package doesn't install smh
