### ISSUE TITLE
Gentoo compatibility may improve the script

### ISSUE THREAD

**Issue by td5038** [LukeSmithxyz/LARBS#473]
You've heard of [Gentoo](https://gentoo.org) right? It is a source-based _meta-distribution_ based on something called [`Portage`](https://wiki.gentoo.org/wiki/Portage) which is based on something else called [ports collections](https://en.wikipedia.org/wiki/Ports_collection) pioneered by the good people that develop [_FreeBSD_](https://freebsd.org). You should first try applying your rice to Gentoo first, though it might be a rabbit-hole getting everything to build properly. I use one of your many scripts, called (mutt-wizard)[https://github.com/LukeSmithxyz/mutt-wizard] on Gentoo. So maybe you can try it. I'll put a similar suggestion to this for for (the Luke Desktop Environment)[https://github.com/LukeSmithxyz/voidrice], @LukeSmithxyz.

**Comment by firaenv** [comment]
You could just fork the script and modify it to compile everything needed.
