### ISSUE TITLE
Missing dwmblocks after installation

### ISSUE THREAD

**Issue by qoelk** [LukeSmithxyz/LARBS#481]
After fresh installation, everything seems to be working, but status bar (dwmblocks) is missing

**Comment by qoelk** [comment]
Laptop: Lenovo ThinkPad X220.
dwmblocks process is running, but nothing is seen on the top bar. Setting xrandr --dpi with small values is not helpful.

**Comment by KarolBank** [comment]
Did you try to press Super + b?

**Comment by qoelk** [comment]
Nope, I gave up and switched to i3
