### ISSUE TITLE
Fonts size mishmash 

### ISSUE THREAD

**Issue by wavic** [LukeSmithxyz/LARBS#487]
I installed some nerd fonts with the other user. Changed from lightdm to sddm. Some programs installed but nothing else.
However when I logged in with the larbs created user the fonts were so small that i can't litterally see anything. Tried to change the dpi. Nothing. Just some lighting icon appears bigger. Both panel and terminal fonts are too small to use. Can't figure out what went wrong.

**Comment by oliver-dvorski** [comment]
What font settings have you set in `~/.local/src/st/config.h` and `~/.local/src/dwm/config.h`?

**Comment by LukeSmithxyz** [comment]
Never trust a DM. They always do things their own way.

I'm going to guess that sddm is not calling the `xprofile` file anymore as it should. There the DPI is set by the command `xrandr --dpi 96`, along with other things.

Just have those commands run some other way or remove the DM.
