### ISSUE TITLE
broken volume limit with keyboard controls.

### ISSUE THREAD

**Issue by Tocoe** [LukeSmithxyz/LARBS#500]
I was playing around with pulseaudio, ended up switching back to pipewire and wireplumber. Volume caps out at 150% when i change through pulsemixer, but when using (MOD + SHIFT +) or my laptop F keys the volume is unbounded and will quickly shoot up to 500% and beyond. (I fear for my speakers haha.)

I poked around in dwm/config.h and found that both the mod+shift and F keys execute the same wireplumber command: `wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+` And I'm assuming this is how it should be... So what's going wrong? should pulsemixer be clamping it at some point? I'm a bit lost.

**Comment by LukeSmithxyz** [comment]
It's not broken. This is as it is intended. Volume has always be uncapped. If you want it lower, decrease it.
