### ISSUE TITLE
Weather Configuration

### ISSUE THREAD

**Issue by DanitiKain** [LukeSmithxyz/LARBS#51]
Can you provide some documentation on how the weather works within i3blocks and how to configure it.

**Comment by LukeSmithxyz** [comment]
The script used is in `~/.scripts/i3weather/` it just takes the output of `wttr.in` and formats with basic shell utilities it as it appears. There's really nothing else to add than that.

If you have specific questions related to the mechanics shell script, you can ask me via email. This isn't really a LARBS "Issue".
