### ISSUE TITLE
DWM Blocks and Hotkeys broken

### ISSUE THREAD

**Issue by CheddarAnon** [LukeSmithxyz/LARBS#512]
Hello, I wanted to add some functionality to vim and added two plugins: ColorMyPencils and Treesitter. I used Plug to add them. 

I rebooted and did some work on my windows partition, when I rebooted to my artix LARBS desktop I am faced with a grey screen, dwm blocks missing, and majority of hotkeys nonfunctional.

I'm assuming I broke something modifying vim but I am unaware of how to fix it. Any insight and help is welcome.

**Comment by CheddarAnon** [comment]
Continuing, It appears /home/USER/.local/src no longer exists. I'll try to replace it, but I am unsure why it is missing.

**Comment by LukeSmithxyz** [comment]
Uh, well I'm guessing you somehow deleted the whole directory. If your blocks are missing and screen is gray, you might've deleted `~/.local/bin` as well, or the entire local directory.

You'll have to reclone the voidrice repo and replace the bin directory for sure. You'll also probably want to redownload the source code for dwm, st, dwmblocks, et al.

**Comment by CheddarAnon** [comment]
Just fixed this. By doing what you said in a round about way. For posterity and those who stumble upon this in the future with weak linux/git skills like me. I ran larbs again, created a new user, copied their files into all of ~/.local. Everything is fine now.  

Thanks , not sure how or why it happened.
