### ISSUE TITLE
I would like to manage a way to disable the terminals bold text.

### ISSUE THREAD

**Issue by aabbccddeeffggj** [LukeSmithxyz/LARBS#532]
Hi, I went after it and there is a patch to add the feature of disabling bold text, but it didn't work, not sure if it is due to the modifications from LARBS or if the patch is not up to date for the current st version, or something else.
After that I try installing a new terminal emulator, xst, which is a fork that have the option to disable the bold text, I installed and indeed, it even came without the bold, but the keybindings (I think) are all messed up: when I press a key it prints normally, then if I press the same key right after again the key is printed twice; and there're also other irregularities too.
Anyone got a suggestion? I even uninstalled my entire system I setup with LARBS and installed Void to make everything from scratch for this sole reason, but when I got stuck in building it I finally accepted that what I was doing was stupid, and went back to LARBS, first I need to learn more things about Linux.
Thanks.

**Comment by aartoni** [comment]
Hey @aabbccddeeffggj can you give more context about the issue? I'm especially interested in:

- the name of the patch you installed;
- the exact step that you performed to install it;
- whether you ran `sudo make install` in the st directory after installing the patch.
