### ISSUE TITLE
LARBS  - Failed to install AUR helper

### ISSUE THREAD

**Issue by NicholasasaurusRex** [LukeSmithxyz/LARBS#538]
Tried to install multiple times now. Same exit error.

LARBS fails to install the AUR helper and exits.

**Comment by NicholasasaurusRex** [comment]
I got a work around. But it's certainly not a fix for LARBS.

If you have come across this in frustration trying to install LARBS for the same reason

"Failed to install AUR Helper"

This maybe a work around untill the issue gets fixed.

Step 1: Run the script:    sh larbs.sh    and let the script fail. 
Step 2: Added the newly created user you added from the script to the wheel group:    usermod -aG wheel username
Step 3: Install vi:    pacman -S vi
Step 4: Edit the sudoers file     visudo /etc/sudoers
Step 5: Uncomment this line:     # %whell ALL=(ALL:ALL) ALL
Step 6: Switch from the root user to the new user.    su username
Step 7: Change home directories:    cd
Step 8: Goto the directory yay is installed:    cd .local/src/yay
Step 9: Install yay:    makepkg -si
Step 10: Type:     exit
Step 11: Now as the root user again, run:     sh larbs.sh

**Comment by kam-daniel** [comment]
Thank you so much for creating this tutorial. I could not have continued with out your help!

**Comment by distress3** [comment]
I wonder is this issue is related to zsh and the PATH variable? When i followed Nicholas's instructions on how to bypass this issue, i first ran into problems with zsh not finding any commands. I had to run a bash prompt before i could do step 9.

**Comment by tlg-tg** [comment]
just install yay from source and then run the installer and make sure you have git installed

Tutorial:

sudo pacman -S git


cd /opt
sudo git clone https://aur.archlinux.org/yay-git.git
sudo chown -R user:user (your username) ./yay.git
cd yay-git
sudo pacman -S --needed base-devel
makepkg -si

and now just cd into the dir where you have the install script and run it 
sudo ./larbs.sh

**Comment by N72826** [comment]
> I got a work around. But it's certainly not a fix for LARBS.
> 
> If you have come across this in frustration trying to install LARBS for the same reason
> 
> "Failed to install AUR Helper"
> 
> This maybe a work around untill the issue gets fixed. The Steps below will just have you install yay manually. Then rerun the script.
> 
> Step 1: Run the script: sh larbs.sh and let the script fail. Step 2: Added the newly created user you added from the script to the wheel group: usermod -aG wheel username Step 3: Install vi: pacman -S vi Step 4: Edit the sudoers file visudo /etc/sudoers Step 5: Uncomment this line: # %whell ALL=(ALL:ALL) ALL Step 6: Switch from the root user to the new user. su username Step 7: Change home directories: cd Step 8: Goto the directory yay is installed: cd .local/src/yay Step 9: Install yay: makepkg -si Step 10: Type: exit Step 11: Now as the root user again, run: sh larbs.sh

This works thank you kindly.

**Comment by ShahramMohammed** [comment]
> I got a work around. But it's certainly not a fix for LARBS.
> 
> If you have come across this in frustration trying to install LARBS for the same reason
> 
> "Failed to install AUR Helper"
> 
> This maybe a work around untill the issue gets fixed. The Steps below will just have you install yay manually. Then rerun the script.
> 
> Step 1: Run the script: sh larbs.sh and let the script fail. Step 2: Added the newly created user you added from the script to the wheel group: usermod -aG wheel username Step 3: Install vi: pacman -S vi Step 4: Edit the sudoers file visudo /etc/sudoers Step 5: Uncomment this line: # %whell ALL=(ALL:ALL) ALL Step 6: Switch from the root user to the new user. su username Step 7: Change home directories: cd Step 8: Goto the directory yay is installed: cd .local/src/yay Step 9: Install yay: makepkg -si Step 10: Type: exit Step 11: Now as the root user again, run: sh larbs.sh

This worked but only after rebooting, otherwise X server would crash on user login

**Comment by fennomaani** [comment]
https://github.com/LukeSmithxyz/LARBS/blob/3f593b62975009a0b143f3557620f4287938c0c0/static/larbs.sh#L111

Removing `-D "$repodir/$1"` fixed the issue for me.

**Comment by bybv** [comment]
Why is this issue closed? Doing a fresh install with the script causes the error as yay is not installed, and it seems to require the workaround that @NicholasasaurusRex mentions, which is not elegant. 

Thank you!
