### ISSUE TITLE
WWAN doesnt recognise hardware

### ISSUE THREAD

**Issue by chomanery** [LukeSmithxyz/LARBS#544]
Hello everyone, after installing LARBS i found out that my WWAN isn't recognized. I was using linux mint and everything worked fine, but after the switch i can only use my wifi and wired ethernet. I'm new to linux that's why i started with linux mint and now i am ready to dive deeper. 
Thanks!

**Comment by smoorg** [comment]
What you're looking for is probably ModemManager. I used it myself in the past. [RTFM](https://wiki.archlinux.org/title/Mobile_broadband_modem#ModemManager). @chomanery close the issue please, its not relevant to LARBS.
