### ISSUE TITLE
Librewolf margins

### ISSUE THREAD

**Issue by konopimi** [LukeSmithxyz/LARBS#546]
This is not an issue, but I have not be able to find the librewolf configuration to get rid of the inner margins. Thanks

**Comment by CheesyChocolate** [comment]
do you mean letterboxing?
https://librewolf.net/docs/settings/#enable-letterboxing
this can be disabled from preferences. just search for letterboxing.

**Comment by konopimi** [comment]
Yes, I just found it, I was reading about it and understand it is to avoid fingerprinting, how does this work?

**Comment by konopimi** [comment]
Thanks, I just found it, and understood it is to avoid fingerprinting, cool
