### ISSUE TITLE
Sudo not prompting for root password for secondary user on Arch Linux

### ISSUE THREAD

**Issue by PabloMartinMoreno** [LukeSmithxyz/LARBS#555]
On an Arch Linux system, I have a secondary user who is a member of the "wheel" group. However, when this user attempts to run commands with sudo, they are not prompted for the root password, which is an undesired behavior for security reasons.

Steps Attempted:
    Edited the /etc/sudoers  and added 'wheel ALL=(ALL) ALL' 
    Edited the /etc/sudoers file with visudo and added rootpw to the Defaults section.
    Verified that the secondary user is in the "wheel" group using groups and usermod -aG wheel.
    Verified the permissions of the /etc/sudoers file and restored them with chmod 0440 /etc/sudoers.

I want it to prompt for the password when my secondary user uses sudo.

**Comment by YonatanShaked** [comment]
I had the same problem, you need to remove `/etc/sudoers.d/larbs-temp` which disables the prompt for the sudo password during the installation of LARBS.
