### ISSUE TITLE
/etc/profile.d/dbus is causing multiple instances of dbus

### ISSUE THREAD

**Issue by ZulluBalti** [LukeSmithxyz/LARBS#557]
Hi,

at larbs.sh line # 338
echo "export \$(dbus-launch)" >/etc/profile.d/dbus.sh

this causes mutiple instances of dbus, which results in weird behaviour on arch. 
To me brave was taking too long to open because of this. it was taking 30s to open brave.

**Comment by fesowowako** [comment]
@ZulluBalti You can modify that line to:
```sh
[ "$(readlink -f /sbin/init)" != "/usr/lib/systemd/systemd" ] && echo "export \$(dbus-launch)" >/etc/profile.d/dbus.sh
```

This change ensures that dbus-launch is only set for non-systemd systems, avoiding unnecessary delays. Alternatively, if you prefer, you can submit a pull request with this fix to benefit everyone.

**Comment by ZulluBalti** [comment]
thanks
