### ISSUE TITLE
Failed to Install AUR Helper

### ISSUE THREAD

**Issue by whatsogingon1** [LukeSmithxyz/LARBS#559]
I encountered an issue while running the installation script that prevented the installation of the AUR helper. I have tried several troubleshooting steps, but the problem persists. Here are the details of the issue:

Steps to Reproduce:

1.Run the installation script (larbs.sh).
2. Observe the error message during the installation process.

In a completely fresh Artix installation "failed to install AUR helper" shows up. After using debug outputs i believe the error is building yay. 

I've already checked permissions of the relevant files.
Verified that the user has sufficient privileges (member of the wheel group).
Tried reinstalling the AUR helper manually.
Reviewed and adjusted the sudoers configuration.
Gone on a few fresh Artix installs

I also recently just got this when I tried to do it again.

```
hint: Using 'master' as the name for the initial branch. This default branch name 
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will supress this warning, call: 
hint: 
hint: git config --global init.DefaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and 
hint: 'development'. The just-created branch can be renamed via this command:
hint; 
hint: git branch -m <name>
Failed to install AUR helper.
```

I've already tried everything that is listed here on Github Publicly.

**Comment by appeasementPolitik** [comment]
Does #553 fix it?

The problem for me was that makepkg was complaining that it didn't work because of `-D $repodir/$1"`, so I just removed that section in the `manualinstall` function, which fixed it. The user is already in the right directory at that point so that section shouldn't even be necessary anyway.

**Comment by fesowowako** [comment]
Well, seeing as the person who raised this issue hasn't responded, I'm going to address it myself. I've encountered the very same problem, and it was resolved following the application of the pull request you highlighted. However, despite these adjustments, the hints persist during the build process. Apart from these persistent hints, everything else appears to function correctly.

**Comment by whatsogingon1** [comment]
> Does #553 fix it?
> 
> The problem for me was that makepkg was complaining that it didn't work because of `-D $repodir/$1"`, so I just removed that section in the `manualinstall` function, which fixed it. The user is already in the right directory at that point so that section shouldn't even be necessary anyway.

Removing `-D $repodir/$1"` fixed it, just to update. Installation went smoothly afterwards.

**Comment by fesowowako** [comment]
> Removing `-D $repodir/$1"` fixed it, just to update. Installation went smoothly afterwards.

Well, I reckon you could pop up a pull request with that patch to give everyone a hand, and then maybe knock off the issue once it's sorted.
