### ISSUE TITLE
lf file manager stuck on "loading..." after previewing 2 or more files

### ISSUE THREAD

**Issue by zetef** [LukeSmithxyz/LARBS#561]
Specs:
```
lf -version
32.r13.g12e99fd
```

```
dwm -v
dwm-6.4
```

I am running a freshly installed version of LARBS as of 14 May 2024.

The problem:
After opening up lf with the Ctrl+O shortcut (and from terminal aswell, does not matter) the app does not preview more that 2 files and the previewer says only `loading...`. Directory previews work. I have not commited any changes to lfrc, but I have observed the following things: in htop there are 11 (!) `lf -last-dir-path=/tmp/same_tmp_file` and there are running 4 `lf -server` commands.

I do not know if this is an lf bug or a misconfigured LARBS but hopefully someone knows what's up and if this is normal behaviour. 

Thanks!

**Comment by fennomaani** [comment]
Pretty sure this is an issue with ueberzug.

I got it working by using the drop-in replacement [ueberzugpp](https://github.com/jstkdng/ueberzugpp).
The AUR package has not yet updated to fix [some positioning issues in st](https://github.com/jstkdng/ueberzugpp/issues/192) so you have to compile it manually for now.

**Comment by 2084x** [comment]
probably related to https://github.com/gokcehan/lf/issues/1725
but it should be working again after the new ueberzug release removed that dependency? https://github.com/ueber-devel/ueberzug/releases/tag/18.2.3

**Comment by fennomaani** [comment]
yeah works now
