### ISSUE TITLE
Some lightweight music players.

### ISSUE THREAD

**Issue by ZaxonXP** [LukeSmithxyz/LARBS#565]
Maybe it is good to add to the programs list following music players:

1) [cmus](https://en.wikipedia.org/wiki/Cmus) - lightweight ncurses music player which can be controlled remotely.
2) openmpt123 - command line player which can play [demo scene modules](https://modarchive.org/)

For the second I made some [scripts](https://github.com/ZaxonXP/modarchive_scripts) which allows to play a playlists from modarchive.org.

Kind regards,
Piotr

**Comment by 2084x** [comment]
larbs already includes mpd, mpc and ncmpcpp

**Comment by ZaxonXP** [comment]
Yes, but they are more complicated to set up. Where the cmus and openmpt123 are much simpler to configure and use.

**Comment by emrakyz** [comment]
`ncmpcpp`, `mpc` and `mpd` are much more modern and featureful while still providing simple, lightweight, easy to use functionality.

What is actually complicated? I do nothing specific to set them up. On Gentoo, I even disabled support other than opus and pipewire for mpd (you can see below):

1. Just start `mpd` with your WM, Compositor.
2. Add your playlist directory path to `mpd.conf`
3. Open `ncmpcpp` and press `u` to update the database.

media-sound/mpd-0.23.15-r1::gentoo was built with the following:
USE="opus pipewire -alsa -ao -audiofile -libmpdclient -bzip2 -cdio -dbus -ffmpeg -chromaprint -cue -curl -doc -eventfd -expat -faad -fifo -flac -fluidsynth -gme -icu -id3tag -inotify -jack -lame -libsamplerate -libsoxr -mad -mikmod -mms -modplug -mpg123 -musepack -network -nfs -openal -openmpt -oss -pipe -pulseaudio -qobuz -recorder -samba (-selinux) -sid -signalfd -snapcast -sndfile -sndio -soundcloud -sqlite -systemd -test -twolame -udisks -upnp -vorbis -wavpack -webdav -wildmidi -zeroconf -zip -zlib"

media-sound/mpc-0.35::gentoo was built with the following:
USE="-doc -iconv -test"

media-sound/ncmpcpp-9999::gentoo was built with the following:
USE="taglib -clock -outputs -visualizer"

**Comment by ZaxonXP** [comment]
The fact that there is database and deamon involved, from my perspective, is a big minus. 

I get used to select a folder with the music and add it to the playlist/queue.  No need for the background process to run when I do not need it. No need to take extra space/folders for database. Cmus has much simpler approach. And for that I thought could be a nice to have alternative to this ncmpcpp/mpc/mpd trio. 

For the openmpt123 I use it as I could not find a better player to play some mod's correctly.
