### ISSUE TITLE
screenkey not included in progs.csv, yet its included in dwm config.h

### ISSUE THREAD

**Issue by TheYellowArchitect** [LukeSmithxyz/LARBS#570]
dwm's config has the following line:
`{ MODKEY, XK_Scroll_Lock, spawn,	SHCMD("killall screenkey || screenkey &") },`
But screenkey doesn't exist in[ progs.csv](https://github.com/LukeSmithxyz/LARBS/blob/master/static/progs.csv)

Anyway, can't confirm if screenkey isn't a default package in artix, so can't confirm it's really an issue (aka screenkey doesn't exist after a LARBS setup)

**Comment by LukeSmithxyz** [comment]
I don't include screenkey because it's not really going to be used by end users who aren't recording videos. The F1 menu mentions it is not necessarily installed, although bound.
