### ISSUE TITLE
LARBS hangs at "Installing vim plugins..."

### ISSUE THREAD

**Issue by TomJansen** [LukeSmithxyz/LARBS#58]
There is a typo which prevents LARBS from installing. Line 209 it must be `dialog --infobox` instead of `dialog --info`. But after fixing this, LARBS still keeps hanging on this dialog. I don't know why this is happing though.

**Comment by LukeSmithxyz** [comment]
That's what I get pushing a change without testing it in application. I've commented the lines out for the time being.

Any ideas what's going wrong? I've tried it fixed on my name system and it works fine. In case it isn't clear, the line just running the `plugged` update command in vim.

`plugged` should be installed once the git repo is cloned and obviously git should already be installed. Not sure what's going on here though.

**Comment by LukeSmithxyz** [comment]
On that install, did the `voidrice` repository not clone properly?

What is in `/home/USER/.vim/autoload/`?

**Comment by TomJansen** [comment]
I was installing larbs in a vm. But the weird thing is that nothing is being written to the virtual disk after running larbs. Arch.vdi is just 2 megabytes (?!). Maybe it is because I did not check live iso in the options for the virtual machine. Will test that now.

**Comment by LukeSmithxyz** [comment]
Okay well LARBS has never been compatible with VMs anyway. I'll test this on a real machine later.
