### ISSUE TITLE
~/.scripts/remaps doesn't exist (or can't change the keyboard layout)

### ISSUE THREAD

**Issue by oscarcederberg** [LukeSmithxyz/LARBS#60]
i'm trying to swtich from us international to sv-latin1, but the config-file `~/.scripts/remap` doesn't exist. the `~/.scripts` directory does however exist, and contains the following files/directories:
`.getkeys   cron   pix   statusbar   tools   SCRIPTS.md   larbs.png   ttymaps.kmap   unix`

am i missunderstanding something in the `Mod+F1` document? please help, luke !!
i tried editing with both nano and vim, but none work, as the file doesn't exist!

**Comment by LukeSmithxyz** [comment]
The `remaps` script was filed into `~/.scripts/tools/` in a recent update. I only just now push changes to the documentation to reflect this.
