### ISSUE TITLE
System doesn't boot after installation of LARBS on Manjaro

### ISSUE THREAD

**Issue by alfbarb** [LukeSmithxyz/LARBS#62]
LARBS Readme.md says it should work on already configured systems, but are they only systems without a window manager installed?
I tried installing LARBS on a fresh install and switched to a terminal login as root using manjaro-gnome-18.0-stable-x86.64.iso
I selected an already created user that was made during the manjaro installation
The LARBS script finishes, but upon reboot I get the following error:

```
mount: /usr/lib/libmount.so.1: version `MOUNT_2.33` not found (required by mount)
mount: /usr/lib/libmount.so.1: version `MOUNT_2.33` not found (required by mount)
mount: /usr/lib/libmount.so.1: version `MOUNT_2.33` not found (required by mount)
/init: line 13: can't open /proc/cmdline no such file
:: running early hook [udev]
failed to prase kernel command line, ignoring: No such file or directory
starting version 239
:: running hook [udev]
::Triggering uevents..
:: running hook [keymap]
:: Loading keymap.. done.
:: running hook [resume]
ERROR: resume, no device specified for hibernation
:: mounting '' on real root
mount: /usr/lib/libmount.so.1 version `MOUNT_2.33` not found (required by mount)
You are not being dropped into an emergency shell
sh: can't access tty; job control turned off
```

System info:
Lenovo thinkpad T420 i5 4gb RAM 180GB ssd
manjaro-gnome-18.0-stable-x86.64

**Comment by LukeSmithxyz** [comment]
I suppose what happened is that you had a system with many un-upgraded packages and in installing a new program, it updated a particular dependency, but not something it depended on or vice versa.

I'll update the script to avoid this problem by having all your repositories updated at the beginning of the script.

To fix this on your current machine, boot into a live environment, mount your system, chroot into it and run `pacman -Syyu`.

**Comment by alfbarb** [comment]
Quick update:
You were right, just needed to update the packages.
After booting into i3 I couldn't open a terminal, so I read through your code/docs a bit.  I had to install st manually and then add the TERMINAL=st it to my .bashrc, pkill myself and log back in, now we're cooking :)  Thanks Luke
