### ISSUE TITLE
terminal shortcuts

### ISSUE THREAD

**Issue by focus85** [LukeSmithxyz/LARBS#65]
isn't the terminal shortcuts (i.e. cfib, d, e ... etc) works out of the box, or we have to do add each manually again? some reason any of the shortcuts work on my machine.

**Comment by LukeSmithxyz** [comment]
I can't really parse what you're asking at all.

The automatically generated aliases are produced by the `~/.scripts/tools/shortcuts` script. They are remade every time you edit one of the bookmark files `~/.bmfiles` and `~/.mbdirs`.

**Comment by focus85** [comment]
Luke thanks for the quick response. 
so the problem i have is that any of the shortcut aliases are not working in terminal. (e.g. bash: d: command not found : for the Document alias d).
