### ISSUE TITLE
starting over from fresh

### ISSUE THREAD

**Issue by stormsz** [LukeSmithxyz/LARBS#66]
Hey Luke, somewhat long time fan here! first time writing to you, let me just say  keep doing what your doing, you're awsome!

anyway, i finely got the hang of all the keybinds of all the programs you use and let me say they are awsome!
so i started editing stuff to my liking, the problem is that i have managed to brake the key layout, it reverts back to US, and the i3 blocks i have been  messing with gave me some problems, anyway i tried reinstalling but it wont start from fresh,at least the i3blocks...so is there an easy or manegable way of starting from scratch besides a full new instal arch install, i know i could delete the dot files but im gessing theres more hidden files in the system that needs to be removed. thanks and sorry for the erros.

**Comment by LukeSmithxyz** [comment]
If you run the LARBS script again (as root) and give the exact same username, it will overwrite all the old dotfiles and give you a clean system (it will not delete any of your user files that are not in the voidrice repository).

You could also do it manually (assuming you are your actually user and *not* root here):
```
git clone --depth 1 https://github.com/lukesmithxyz/voidrice /tmp/dotfiles
cp -rT /tmp/dotfiles ~
```

**Comment by LukeSmithxyz** [comment]
Obviously, to be clear, you could also just use git to update, but I'm making the assumption that you don't want to deal with git and just want a restart.

**Comment by stormsz** [comment]
Hello Luke. thanks for the info, i tried the rerun the script as root but the i3blocks kept giving me error, had to manualy remove the i3blocks packets and run the script again, thanks.
