### ISSUE TITLE
Initial install failing - sudoers related

### ISSUE THREAD

**Issue by richeyward** [LukeSmithxyz/LARBS#67]
Hey Luke.
I installed a fresh build of Arch using pacstrap, etc.  From that fresh build I ran LARBS which executed without errors.  startx however threw a few errors so I knew something wasn't installed correctly.

Looking at the source, I see the manual install of yay, which was not installed on my host post script run, so I knew something was broken. Replicating the steps in the script manually, I saw that the pacman installed apps installed fine.

Yay's manual install however showed an interesting error:

sudo -u "<username>" tar -zvf yay.tar.gz
"root is not in the sudoers file...."
It appears that the sudoers file is missing the following line....

root ALL=(ALL) ALL

Adding and rerunning LARBS seems to fix the issue,

**Comment by LukeSmithxyz** [comment]
I'm not quite sure how `root ALL=(ALL) ALL` wasn't in your sudoers file. LARBS only temporarily adds some lines to to the sudoers file, but doesn't delete any. I assume that when you write `sudo -i ""` you are omitting the username? Of course it shouldn't work if `$name` isn't defined by the script.

Did you do anything irregular in your original Arch install? Did you install sudo manually? Or base-devel?

**Comment by richeyward** [comment]
Hi Luke. Firstly, correction on the` sudo -u""` above.  The users username was in there, just the formatting in Github omitted it so it looks blank. The newly created user's name was in there.

Secondly, I recreated my steps... I installed Arch using the iso live image and pacstrap (base), and it seems that /etc/sudoers doesn't exist as sudo wasn't installed....

Manually installing sudo added the line by default, THEN running LARBS works.

For reference, I used the Arch install docs [here.](https://wiki.archlinux.org/index.php/installation_guide)

**Comment by LukeSmithxyz** [comment]
Okay. LARBS does explicitly install base-devel at the beginning now which should pull sudo... I'll double check this when i can.

On December 16, 2018 6:04:47 PM EST, Richey Ward <notifications@github.com> wrote:
>Hi Luke. Firstly, correction on the` sudo -u""` above.  The users
>username was in there, just the formatting in Github omitted it so it
>looks blank. The newly created user's name was in there.
>
>Secondly, I recreated my steps... I installed Arch using the iso live
>image and pacstrap (base), and it seems that /etc/sudoers doesn't exist
>as sudo wasn't installed....
>
>Manually installing sudo added the line by default, THEN running LARBS
>works.
>
>For reference, I used the Arch install docs
>[here.](https://wiki.archlinux.org/index.php/installation_guide)
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/LukeSmithxyz/LARBS/issues/67#issuecomment-447685082

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by krook1024** [comment]
I've just experienced this too when installing it on my X230. It's strange because I didn't have this issue when I installed larbs on my T530 just two days ago. 

I resolved this with doing `pacman -Rscn sudo` then reinstalling it and editing `etc/sudoers` manually, then proceeding with installing larbs, but with the sudoers file editing method commented out. It works fine now.

**Comment by LukeSmithxyz** [comment]
I realized today that I had misordered something in the script to cause this problem, bit I've also added a failsafe that should copy over the newly produced sudoers file if there are any problems.
