### ISSUE TITLE
How to do update?

### ISSUE THREAD

**Issue by usptact** [LukeSmithxyz/LARBS#69]
Hi Luke,

Thanks for this great, easy to install i3 configuration! I really like it!

I am curious how to pull updates from your repo to my system. There is this installation script but I can't figure out how to pull your most recent commits.

Thanks

**Comment by mirro-chan** [comment]
I don't know if it's the right way to do it, but whenever I want to update I just run the "larbs.sh" script again.
It will pull the latest changes automatically.
