### ISSUE TITLE
keymaps layout

### ISSUE THREAD

**Issue by TohtoriKuka** [LukeSmithxyz/LARBS#70]
Hi Luke,

Nice project. 

How can I change users keymap layout? As root I have my layout as I wanted it to be, but as user its changed and its hard to use for examble vim.

**Comment by LukeSmithxyz** [comment]
In LARBS, edit the `~/.scripts/tools/remaps` file; it's all there. This file just makes some keyboard changes on startup, but they may override your preferences.

**Comment by TohtoriKuka** [comment]
Hi,

I had to come back for this issue. Yes, I know how change keymap in terminal.

In the `~/.scripts/tools/remaps` file I uncommented the line `setxkbmap -layout us -variant altgr-intl -option caps:super¸` and changed the layout code with and without quotes. And commented in the other line. It wont work.

It works in terminal, but that is not the way to solve this. It should be automatic in every startup.

**Comment by LukeSmithxyz** [comment]
What keyboard layout is your system default? I don't know the ends and outs of all, but I suppose it's possible that it conflicts with the `altgr-intl` options (which I think is English specific) or the `caps:super` option. If it doesn't work after a restart you might want to remove one of those or keep both lines commented.

**Comment by TohtoriKuka** [comment]
I use finnish layout as a default.
I commented both lines and added line `setxkbmap 'fi'`. Now it works fine and wont work without quotes, because it is mixed in `if statement`.
I think your are right about conflicts with the `altgr-intl` or `caps:super`.

**Comment by Gfast2** [comment]
Hi,

I'm using German Keyboards. What I experienced is: I can change keyboard layout with `setxkbmap de`. But stuff like 'ä', 'ö'... would not been displayed in my terminal.

BTW: my "$LANG" return `en_US.UTF-8' under i3.  Parallel I installed xfce. sharing the same locale stuff I believe. Really GREAT if it would be, if I can ride with `LARS`.
