### ISSUE TITLE
How to change font-size in Terminal

### ISSUE THREAD

**Issue by Gfast2** [LukeSmithxyz/LARBS#71]
Hello Everyone,

gorgeous Project indeed! With Luke I'm starting to tasting & understanding why some people wanna leave Feature Rich Desktop-Eviroment and playing around with window system. I makes everything magic!

I drop-by here to ask my first question (sure, the newbee thing):
How can I change the font-size in Terminal? In `xfce` I can `ctrl` + `+`. But how this works in `i3`?

**Comment by luukvbaal** [comment]
This is not so much a matter of 'how it works in `i3`' as much as it is a matter of how does it work in the terminal emulator you're using. Assuming you're using Luke's `st` build, see the [readme](https://github.com/LukeSmithxyz/st/blob/master/README.md).

**Comment by Gfast2** [comment]
Hi @luukvbaal,

It's awesome! the related question of this one ist actually: _What is the Terminal in the LARBS?_ :thinking: 
Now everything would be rocked as I supposed. I really appriciate all you guys' patient & helps. If I go far enough here. I do think make contribution here.
