### ISSUE TITLE
Some issues in my setup.. Please help me

### ISSUE THREAD

**Issue by saifulapm** [LukeSmithxyz/LARBS#72]
I have seen a script in i3 config.. 

`bindsym $mod+Pause		exec --no-startup-id xcqr`

I just want to understand everything cleary.

Thanks

**Comment by saifulapm** [comment]
`bindsym $mod+Shift+r		exec --no-startup-id winresize`

I think this script for window resize. I am pressing $mod+Shift+r then dmenu showing Width and Height.. I am giving values like this.. 500x400

But Nothing happen..

**Comment by saifulapm** [comment]
`bindsym $mod+v split vertical
bindsym $mod+t			split toggle`

split not working when I am pressing mod+v/t.. Is this any bug ?

**Comment by saifulapm** [comment]
`bindsym $mod+p			exec --no-startup-id lmc toggle`
`bindsym $mod+o			sticky toggle`

Seems not working in my laptop.. Any idea ?

**Comment by LukeSmithxyz** [comment]
All of these questions are answered in the manual.
