### ISSUE TITLE
command notify-send not found/can't see dunst notifications

### ISSUE THREAD

**Issue by danielmpla** [LukeSmithxyz/LARBS#75]
Hello,

I have installed LARBS on a clean ArchLinux. I haven't seen any dunst notifications on my system yet (dunst is running). After I run dmenuunicode from the terminal it says "notify-send: command not found". I've searched through his repository and found one file which shows "/usr/bin/notify-send" so I looked for this file on my system and couldn't find it. I've seen on the dust side, that they define an alias for notify-send, however I also didn't find it his dot-files.

Has anybody an idea to solve this?

PS: I really like LARBS, thank you for sharing it!

**Comment by LukeSmithxyz** [comment]
Shoot... could you install `libnotify` and see if that provides it? Just
run a notify-send command in a new terminal.

I think I may've accidentally removed it when I removed another
dependency from the programs list.

**Comment by danielmpla** [comment]
Thank you! Installing 'libnotify' has resolved the issue.

**Comment by LukeSmithxyz** [comment]
Thanks for bringing this to my attention! I'll be sure to add it to the
dependency install list.
