### ISSUE TITLE
Making installation faster.

### ISSUE THREAD

**Issue by ispanos** [LukeSmithxyz/LARBS#76]
I'm using Manjaro and I'm not sure if its exactly the same on Arch but it just a suggestion.
In /etc/makepkg.conf there is this line:
 #MAKEFLAGS="-j2"
Could you add a sed command to change it to: 
MAKEFLAGS="-j$(nproc)" 
This way make will use all available cores and aur and git packages will install faster
It must be almost as simple as adding color to pacman, except for the double quotes . I haven't had any problems with that, so unless it can cause problems, why not add it to Larbs?

Source: https://wiki.archlinux.org/index.php/makepkg#Parallel_compilation

**Comment by LukeSmithxyz** [comment]
Interesting idea. It will be in the next push.

**Comment by luukvbaal** [comment]
The same can be used to speed op package compression, cool!
`COMPRESSXZ=(xz -T $(nproc) -c -z -)` in `/etc/makepkg.conf`.
Thanks for the idea.

**Comment by luukvbaal** [comment]
Actually `COMPRESSXZ=(xz -T 0 -c -z -)` achieves the same result
