### ISSUE TITLE
VIM and GVIM encountered while install

### ISSUE THREAD

**Issue by zakatura** [LukeSmithxyz/LARBS#77]
GVIM now conflicting with VIM 
Then i cant finish install
If i 

`sudo pacman -Rs vim`

Then install, it will error with gvim
Esle

`sudo pacman -Rs gvim`

Then install, it will error with htop-vim-git

Please help, thanks !

**Comment by zakatura** [comment]
I can install now, fix with 

```
sudo pacman -Rs vim
sudo pacman -Rs gvim
sudo pacman -Rs htop
curl -LO lukesmith.xyz/larbs.sh
bash larbs.sh
```

**Comment by LukeSmithxyz** [comment]
I pushed something without testing a bit ago that caused this. Removed for the time being.
