### ISSUE TITLE
Choosing "save-as" in firefox results in your entire screen turning white

### ISSUE THREAD

**Issue by samerickson** [LukeSmithxyz/LARBS#83]
I would like it to be simple to download images and files while using firefox, but there seems to be no download option, however there is a "save-as" option, but as the title suggests, it results in your entire screen turning white. Is there a fix for this? Or do you just have to use curl to download all images?

**Comment by LukeSmithxyz** [comment]
Firefox hasn't been modified at all other than a superficial profile change. I'm not sure what you mean by there being "no download option".

I've never heard of this kind of screen error. If it is something related to the custom profile, you can change/delete the default profile in `~/.mozilla/firefox/profiles.ini` and see if that changes anything. This might be some kind of error with the GTK downloader prompt, in which case I have no control over.

**Comment by samerickson** [comment]
Solved: The issue was that the file browser that would spawn was incredibly large due to me using `Xft.dpi: 192` in my `.Xresources`. All you have to do is resize it the first time using `$mod+U` and `$mod+Y` until it is a sensible size. **Alternately**: you can toggle the *float* on the window using `$mod+Shift+Space`.

**Comment by samerickson** [comment]
@LukeSmithxyz would it be reasonable to add a "common-issues.md" file as a sort of wiki as quirky issues like this arise? As this is not applicable to everyone, but anyone who tries to use LARBS with a HiDPI screen will.

**Comment by TomJansen** [comment]
@samerickson nm-tui cannot connect to WPA2 Enterprise, but nm-applet can for some reason...

**Comment by LukeSmithxyz** [comment]
@samerickson Add the following to the i3 config to permanently fix this:
```
for_window [window_role="GtkFileChooserDialog"] resize set 800 600
for_window [window_role="GtkFileChooserDialog"] move position center
```
You might want to play around with the size. Maybe I'll add lines to this effect to prevent this in other cases.

And yes, nm-applet is one of the only programs that actually creates WPA2 enterprise profiles. I've been looking for an equivalent to little success. I might add a note about it to the readme.
