### ISSUE TITLE
Opening i3 config using keybinding cfi results in vim error.

### ISSUE THREAD

**Issue by samerickson** [LukeSmithxyz/LARBS#84]
When in the `$HOME` folder typing `cfi` opens vim to `~/.config/i3/config` however, you are also greeted with the following vim error:
```
Error detected while processing /home/erickssb.config/nvim/init.:vim:
line 9: 
E117 Unknown function: plug#begin
line 10:
E492: Not an editor command: Plug 'junegunn/goyo.vim'
line: 11:
E492 : Not an editor command: Plug 'PotatoesMaster/i3-vim-syntax'
line 12: 
E495: Not an editor command: Plug 'jreybert/vimagit'
line 13:
E492: Not an editor command: Plug 'LukeSmithxyz/vimling'
line 14:
E492: Not an editor command: Plug 'vimwiki/vimwiki'
line 15:
E117: Unknown function: plug#end
Press ENTER or type command to continue
``` 

However using `vim .config/i3/config` operates normally.

**Comment by samerickson** [comment]
This might be an issue with the plugin manager as found here https://github.com/junegunn/vim-plug/issues/812.

**Comment by LukeSmithxyz** [comment]
This has to to with the switch from vim to neovim. I guess I forgot to change the plugin installation. Run this and see if it fixes the problem:
```
nvim -E -c "PlugUpdate|visual|q|q"
```

**Comment by LukeSmithxyz** [comment]
Actually, before you run that, run these commands:
```
mv ~/.vim/* ~/.config/nvim/
ln -s ~/.config/nvim ~/.vim
```
This should all be fixed in the script now, but I'm testing it.

**Comment by samerickson** [comment]
Works, thanks @LukeSmithxyz

**Comment by LukeSmithxyz** [comment]
Great. It should work without a problem on new installs now.
