### ISSUE TITLE
[ENHANCEMENT] Deprecate xwallpaper in favor of ImgMjk `display`

### ISSUE THREAD

**Issue by Gingersnap1991** [LukeSmithxyz/LARBS#85]
xwallpaper is redundant. ImageMagick includes a wallpaper setter already. It's already installed and far more feature rich.

Example: `display -window root "$WALLPAPER"`
Online Man Page: https://linux.die.net/man/1/display

**Comment by Gingersnap1991** [comment]
If your wallpaper is lower resolution than your monitor, `display` accepts image magick output. This will zoom-fit the image to the a given resolution.
`convert "$WALLPAPER" -geometry 1920x1080^ -gravity center -crop 1920x1080+0+0 - | display -window root -`

You can of course use other core xorg utilities to automate the capture of the display resolution:
`xdpyinfo | awk '/dimensions/{print $2}'`
or alternatively
`xdpyinfo  | grep -oP 'dimensions:\s+\K\S+'`

**Comment by Gingersnap1991** [comment]
Didn't think about that big guy. I'm sure it's possible in a _few_ lines by probing each screen, fitting, and stitching the result together but it would probably be about as long as xwallpaper's procedure but BASH and with less features.

Guess xwallpaper serves a purpose after all ;^), feel free to close.

**Comment by LukeSmithxyz** [comment]
Just to be clear, I would _like_ to remove this dependency, but I've tried implementing imagemagick and am too lazy to work it all out.
