### ISSUE TITLE
ttf-linux-libertine doesn't provide ttf-fonts anymore.

### ISSUE THREAD

**Issue by ispanos** [LukeSmithxyz/LARBS#86]
This is the current version: https://www.archlinux.org/packages/extra/any/ttf-linux-libertine/
This is the previous: https://web.archive.org/web/20171117172914/https://www.archlinux.org/packages/extra/any/ttf-linux-libertine/

Firefox, among other packages depends on ttf-font, which is no longer provided by any of the 4 font packages in progs.csv. 
So if you try to update, you are probably going to be prompted to choose a font package that provides `ttf-font`. Unless its only happening to me. If it's not just me, are you going replace `ttf-linux-libertine` or add a fifth font package?

**Comment by LukeSmithxyz** [comment]
I don't really understand what the problem is here. Are you just recommending I change font to minimize package number?

**Comment by LukeSmithxyz** [comment]
Well I'm autistic and 80MB is nothing to supply font coverage for different languages. That's one of the reasons noto-fonts is so big.

I don't know, maybe I'll have LARBS install one of the other packages, but if I do, I'd sort of like to swtich the serif/sans fonts to something offered by them as well to remove Linux Libertine. I'm not so attatched to it.

People are free to offer a font suggestion, because I'm not a big font n*rd myself.

**Comment by ispanos** [comment]
- noto-fonts (80MB) Made by google + noto-fonts-emoji (7.8MB) but I don't know if it can replace ttf-emojione and/ or ttf-emojione (?)
- ttf-bitstream-vera (584.7kB) www-old.gnome.org/fonts/ 
- ttf-caladea (242kB) by google.
- ttf-carlito (2.8MB) by google.
- ttf-croscore (6MB) by google - Chrome os core fonts.
- ttf-dejavu (10.2MB) based on bitstream-vera.
- ttf-freefont (10.8MB) GNU FreeFont
- ttf-droid (16.1MB) by google - part of android.
- ttf-liberation (4.1MB) by RedHat - this is the one I choose.
- ttf-ubuntu-font-family (4.1MB) - License: custom: Ubuntu Font License 1.0

Can anyone jump in and make an "educated" recommendation?

**Comment by ispanos** [comment]
@LukeSmithxyz Maybe replace `ttf-linux-libertine` with `noto-fonts`? 

And on second thought, would you care to replace ` ttf-symbola` and `ttf-emojione` with a single font package that includes all the necessary emojis? I guess you have a reason to include both of them, but could it be possible to replace them with `noto-fonts-emoji`? I'm only suggesting that is because noto-fonts-emoji is in the main repos.

**Comment by LukeSmithxyz** [comment]
noto-fonts-emoji look stupid so I don't use them. There might be an okay font in noto-fonts, but I would want to know what actually looks good before changing over.

**Comment by ispanos** [comment]
>noto-fonts-emoji look stupid so I don't use them.

I haven't seen them but I trust your judgement.  
It's not something urgent, but since larbs has the `--noconfirm` options it would be better to actually choose what fonts get installed rather than installing the default `ttf-font` package in the background.

**Comment by webkernel** [comment]
I just installed today Archlinux from scratch and LARBS. The icons (emoji) on my statusbar don't show up, except for battery charging symbols. I tried to find AUR ttf-emojione but it is no longer available. Is there a solution for this?

Thanks!

**Comment by LukeSmithxyz** [comment]
It's right here: https://aur.archlinux.org/packages/ttf-emojione/

Builds on my machine. Do you get an error?

**Comment by webkernel** [comment]
> It's right here: https://aur.archlinux.org/packages/ttf-emojione/
> 
> Builds on my machine. Do you get an error?

It's no longer available. I get a message saying I am trying to clone an empty repository.

**Comment by LukeSmithxyz** [comment]
That's not how you install something from the AUR. If you want to install it manually for some reason, download the snapshot and run `makepkg -si`. Otherwise use an AUR helper.

**Comment by webkernel** [comment]
Step 1:
$ git clone https://aur.archlinux.org/packages/ttf-emojione/
Step 2:
makepkg -si

This is what I wanted to do, but in Step 1 I get an error. There's nothing to fetch on that URL. That's my problem.

**Comment by LukeSmithxyz** [comment]
git is not involved in this process! Download the snapshot! It's on the right side! Or explicitly:
```
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/ttf-emojione.tar.gz
tar xvzf ttf-emojione.tar.gz
cd ttf-emojione
makepkg -si
```
If you can't do this, you should be using an AUR helper. You should be using an AUR helper even if you can do this.

**Comment by webkernel** [comment]
I just installed today Archlinux from scratch and LARBS. The icons (emoji) on my statusbar don't show up, except for battery charging symbols. I tried to find AUR ttf-emojione but it is no longer available. Is there a solution for this?

Thanks!

> git is not involved in this process! Download the snapshot! It's on the right side! Or explicitly:
> 
> ```
> curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/ttf-emojione.tar.gz
> tar xvzf ttf-emojione.tar.gz
> cd ttf-emojione
> makepkg -si
> ```
> 
> If you can't do this, you should be using an AUR helper. You should be using an AUR helper even if you can do this.

Thanks! No luck.
Tried curl -k https://github.com and nothing!

 makepkg -si
==> Making package: ttf-emojione 4.5-1 (Thu Apr 18 14:10:39 2019)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading emojione-android-4.5.ttf...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   611    0   611    0     0    909      0 --:--:-- --:--:-- --:--:--   907
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
==> ERROR: Failure while downloading https://github.com/maximbaz/emojione-fonts/releases/download/4.5/emojione-android.ttf
    Aborting...

**Comment by webkernel** [comment]
Disregard....
I changed to a wifi connection and did the install.
Many thanks!
