### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by brickrat** [LukeSmithxyz/LARBS#90]
Installed the LARBS.sh script
Now i get Error in top right corner -> Error: status_command process exited unexpectedly (exit 0)

**Comment by patosullivan** [comment]
Does it persist after you refresh i3 (`Mod + F2`)?

**Comment by pyaf** [comment]
@brickrat you need to install `i3blocks`

**Comment by dookiefied** [comment]
I'm having the same error with i3blocks installed, it does go away after I refresh i3 but it's annoying having to refresh it every time I boot my laptop. Running `i3blocks` in the terminal doesn't seem to give any errors so I'm clueless as to what could be causing this

**Comment by pyaf** [comment]
There is something which isn't installed, you'll have to debug i3blocks conf file then, there's a module being used but which isn't installed. Share me your .config/i3blocks/config file.

**Comment by dookiefied** [comment]
`command=~/.scripts/statusbar/$BLOCK_NAME
separator_block_width=15
markup=pango

#Spotify icon \uF1BC
[spotify]
label=
command=~/.scripts/statusbar/spotify.py
color=#81b71a
interval=5

#[music]
#label=🎼
#interval=once
#signal=11

#[news]
#label=📰
#interval=once
#signal=6

#[weather]
#interval=3600
#signal=5

#[mailbox]
#label=📬
#interval=180
#signal=12

[memory]
interval=30
label=🧠

[cpu]
interval=15
label=💻

[volume]
interval=once
signal=10

#[disk]
#interval=60
#command=disk /

#[disk]
#interval=60
#command=disk /home 🏠

[clock]
label=📅
interval=30

[internet]
interval=10
`

This is my i3blocks config, all of the modules are working. The only one I've added is the spotify module which works when spotify is running

**Comment by pyaf** [comment]
hmm. Not sure what's the issue then, you should look for anything which is being used by i3 config but isn't installed. Look for those which are executed at the startup.

**Comment by dookiefied** [comment]
Just an update, the error still occurs after redownloading and rerunning `sudo bash larbs.sh`. Luke, any idea? @LukeSmithxyz

**Comment by su1c1d3jerk** [comment]
Same exact issue here on a clean Manjaro i3 install.

**Comment by su1c1d3jerk** [comment]
> Did you create the user using larbs?

No, I overwrote the one made with the Manjaro installation (the installer said that could be done but maybe there's the issue (?))

> larbs.sh is not supposed to be run with sudo AFAIK. You need to log in as root to run it.

I did actually switch to root to run the script if that makes any difference

**Comment by ispanos** [comment]
>No, I overwrote the one made with the Manjaro installation (the installer said that could be done but maybe there's the issue (?))

Well I installed manjaro using  Manjaro-Architect (CLI-system) and everything worked fine. We create the user if Larbs already does that. I don't know if that the problem but I don't understand why people don't just use Architect if they want to use larbs on manjaro.

**Comment by LukeSmithxyz** [comment]
As I said in [LukeSmithxyz/voidrice/issues/204] and previous issues:

```
This is a longstanding problem of unknown origin to be frank. One (multiple) modules cause it, but it typically happens to me too infrequently to determine exactly what is going on.
```

Since dookiefied says he gets the problem with all of those modules comments, I would assume that the volume module is causing it, since the other two he has activated were not present when this problem began. I'm not exactly sure of the cause.

**Comment by su1c1d3jerk** [comment]
Commenting out the line `exec_always --no-startup-id mpdupdate` on `~/.config/i3/config` fixes it for me so I guess the problem is on ` ~/.scripts/statusbar/mpdupdate`

**Comment by LukeSmithxyz** [comment]
How often does it occur if you _don't_ comment that out though?

**Comment by LukeSmithxyz** [comment]
What happens if you keep `mpdupdate` in the i3 config, but move it below
the line that runs mpd?

**Comment by su1c1d3jerk** [comment]
Already tried that, no luck.

**Comment by su1c1d3jerk** [comment]
So I tried disabling mpdupdate in the i3 settings again and running it myself after the system had booted and it actually worked.

**Comment by LukeSmithxyz** [comment]
Great, that's what I was just going to ask you. Yeah, I think that if there's no mpd library configured, the `mpc` commands in `mpdupdate` and the statusbar `music` script interfere in some way.

Can other people do this and see if it solves the problem?

**Comment by patosullivan** [comment]
Yep, this solved it for me.

**Comment by dookiefied** [comment]
Commenting the mpdupdate line at the start of the i3 config did the trick for me as well. Just commenting out the module in i3blocks isn't enough.

I did look at the mpd config to see if the library is set up, and it is set up as ~/Music which is why I use when I /do/ listen to offline music which is rare. Though that led me to the discovery  that there's some error when I run mpd, but I'm in the middle of exams so I don't really have the motivation or time to try to fix it. Either way, mpd (or the mpd script) is what was causing the problem and I haven't had the status bar error pop up at boot ever since *knocks on wood*

**Comment by ZethJack** [comment]
Well what do you know? I didn't bother setting up MPD and it's library until I actually wanted to listen to some offline music, and well, mpd was giving me some trouble. Something about database file not existing even if it was clearly present, and refusing to acknowledge the path to my music folder (which was located in ~/Hudba). After a little bit of back and forth, I managed to make it behave and this seems to have solved the issue with the statusbar as well!

**Comment by LukeSmithxyz** [comment]
Okay, it's been a month without a peep. I'm going to say this is taken care of by the change above.
