### ISSUE TITLE
Changing Serif font system wide

### ISSUE THREAD

**Issue by sameer-manek** [LukeSmithxyz/LARBS#95]
By default it seems that larbs sets up with serif font system wide. How do you change this font to some other ones like roboto, etc?

**Comment by patosullivan** [comment]
Fontconfig, documentation is here: https://www.freedesktop.org/software/fontconfig/fontconfig-user.html

**Comment by fentas** [comment]
@LukeSmithxyz are u using serif font as default? It feels more like a bug, honestly. Everything feels and looks quite nice but then default sans serif?

Maybe this is a feature request? (able to configure a default system font)

**Comment by fentas** [comment]
Ok figured it out.
There is a dotfile linked into the system. `/etc/fonts/conf.avail/50-user.conf`
Just change that and you are good to go. @sameer-manek 

```sh
➜ cat .config/fontconfig/fonts.conf
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>

 <alias>
    <family>serif</family>
    <prefer><family>Droid Sans</family></prefer>
  </alias>
  <alias>
    <family>sans-serif</family>
    <prefer><family>Ubuntu</family></prefer>
  </alias>
  <alias>
    <family>sans</family>
    <prefer><family>Ubuntu</family></prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer><family>Ubuntu Mono</family></prefer>
  </alias>

</fontconfig>
```

**Comment by sameer-manek** [comment]
First of all, sorry for really late reply,
AND
Thanks
 @fentas , I was able to change my font with that. However, I think some applications are still stuck to serif.. vscode is one which I have personally encountered.

I dont think that holds true for electron applications because atom (being one) is immune to the problem.

![pic-full-190205-1651-00](https://user-images.githubusercontent.com/26008408/52270217-4a368200-2966-11e9-8490-219350ae9469.png)

Do you happen to have any idea what is causing this?

**Comment by fentas** [comment]
Hm wired. I am also using vscode but it's working for me. :/
Did you use my example above? If so, maybe you have to install `ttf-ubuntu-font-family`.
