### ISSUE TITLE
Terminal issues

### ISSUE THREAD

**Issue by fentas** [LukeSmithxyz/LARBS#96]
Hey first of all thanks for the repo and the effort you put into this. :+1:

**My system (fresh installed)**
- Manjaro i3
- Then installed LARBS

**Terminal**
- :bug: I usually use `strg+a` and `strg+e` to jump around. But `strg+e` does not work. It only inserts `^E`.
- :question: How do I scroll? Is there a way to enable touchpad scroll? If I scroll up it will also only insert `^E`.
- `delete` does not work. In a way, it copies the char underneath the cursor.

**Comment by patosullivan** [comment]
Luke has documentation on his ST build here: https://github.com/LukeSmithxyz/st/

**Comment by LukeSmithxyz** [comment]
The default readline mode in LARBS is vi mode. Check `man readline` for the differences, or edit/delete `~/.inputrc` to return to emacs mode.
