### ISSUE TITLE
Keyboard layout in larbs

### ISSUE THREAD

**Issue by parcias1dedo** [LukeSmithxyz/LARBS#99]
I have had a problem that makes using larbs impossible.
During install larbs overrides the vconsole.conf file and I havent been able to change my layout even with loadkeys.
I have tried many thing but there seems to be something within the script that overrides the config file so help me to change the layout or/and maybe add a way to change layout during installation.

**Comment by LukeSmithxyz** [comment]
What is in vconsole.conf now?

**Comment by parcias1dedo** [comment]
"KEYMAP=pt-latin1"
Before i installed larbs it worked fine

**Comment by LukeSmithxyz** [comment]
Oh. I thought you meant it was overwritten. Read the LARBS manual. Keyboard settings are set in `~/.scripts/tools/remaps`. One of the commands there is overwriting your settings.
